### PR TITLE
fix(cargo): Treat projects outside the analyer root as packages

### LINKED ISSUE #8571: [BUG] Cargo: submodules and local packages are being skipped
After the last releases, local packages and submodules that were defined with a 'path' in the Cargo.toml file are being skipped from the report file.

To reproduce it use a package dependency with a local path, for example:
```
# Cargo.toml
...
[dependencies]
bytes = { version = "^1.3", optional = true }
futures = "^0.3"
redis = { path = "../submodules/redis-rs/redis", features = ["aio", "tokio-comp", "tokio-rustls-comp", "connection-manager","cluster", "cluster-async"] }
logger_core = {path = "../logger_core"}

```
The generated NOTICE_DEFAULT file wouldn't contain attributions for both the `redis` and `logger_core` crates, as opposed to older ORT versions were these packages were included.

### PR DESCRIPTION
**Pull request by sschuberth**
E.g. when analyzing a single Cargo project in a sub-directory with a `cargo.toml` file that points to "path dependencies" in a parent directory, these dependencies should not be seen as projects but as packages. This restores the behavior from before 7522a0c.

Resolves #8571.

### CODE REVIEW

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt [hunk 1]
```diff
@@ -191,14 +191,18 @@ class Cargo(
...
         return listOf(ProjectAnalyzerResult(project, nonProjectPackages))
     }
 }
 
-private fun CargoMetadata.Package.isProject() = source == null
+private fun CargoMetadata.Package.isProject(root: File? = null): Boolean {
+    val path = id.substringAfter("path+file://", "").removeSuffix(")").ifEmpty { null }
+    val isWithinRoot = root != null && path != null && File(path).startsWith(root)
+    return source == null && isWithinRoot
+}
```
Comment (fviernau) [inline plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:205]: Tests still fail due to linkage type.

**Review by fviernau — CHANGES_REQUESTED** [review]

File: plugins/package-managers/cargo/src/funTest/assets/projects/synthetic/cargo-expected-output.yml [hunk 2]
```diff
@@ -12,10 +12,10 @@ project:
   declared_licenses_processed:
     spdx_expression: "Apache-2.0 OR MIT OR NOASSERTION"
   vcs:
-    type: ""
-    url: ""
-    revision: ""
-    path: ""
+    type: "Git"
```
Comment (fviernau) [inline plugins/package-managers/cargo/src/funTest/assets/projects/synthetic/cargo-expected-output.yml:15]: commit-msg: analyer -> analyzer

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt [hunk 3]
```diff
@@ -209,6 +215,10 @@ private fun CargoMetadata.Package.toPackage(hashes: Map<String, String>): Packag
     // https://github.com/rust-lang/cargo/pull/4920
     val declaredLicensesProcessed = DeclaredLicenseProcessor.process(declaredLicenses, operator = SpdxOperator.OR)
 
+    val vcs = repository?.let { VcsHost.parseUrl(it) }
+        ?: getLocalPath()?.let { PackageManager.processProjectVcs(it) }
```
Comment (fviernau) [inline plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:219]: This is using the result of `processProjectVcs()` as (unprocessed) `vcs`. 
Just in recent discussion, IIUC, this has been seen undesired. What do you think?
(Looking at other package managers, many places used `VcsInfo.EMPY`)

I'm not against this change, but believe this needs to be clarified first.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt [hunk 4]
```diff
@@ -191,14 +192,19 @@ class Cargo(
...
         return listOf(ProjectAnalyzerResult(project, nonProjectPackages))
     }
 }
 
-private fun CargoMetadata.Package.isProject() = source == null
+private fun CargoMetadata.Package.getLocalPath(): File? =
+    id.substringAfter("path+file://", "").ifEmpty { null }
+        ?.removeSuffix(")")?.substringBefore("#")?.let { File(it) }
+
+private fun CargoMetadata.Package.isProject(root: File): Boolean =
```
Comment (fviernau) [inline plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:206]: Looking at the signature, I have difficulties understanding what is expected to be passed as `root`. 
Can you help me understanding it? ..and can the name (root) be made more speaking ?

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt [hunk 5]
```diff
@@ -191,14 +192,19 @@ class Cargo(
...
+    source == null && getLocalPath()?.startsWith(root) == true
```
Comment (fviernau) [inline plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:207]: Can we have a code comment, explaining the idea besides the expression ?

**Review by fviernau — CHANGES_REQUESTED** [review]

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 4 above)
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:206]: I've added docs to clarify.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 5 above)
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:207]: I've extracted a speaking variable instead.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 3 above)
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:219]: I also recalled that discussion when writing this code and thought about it. The problem here is that without this code, a package that actually is a project outside of the working tree would not have *any* VCS information at all, neither processed nor unprocessed. Adding this code was the easiest way to fix that, even if strictly speaking the "bonus" of getting the unprocessed VCS non-empty for "real" packages would not be required.

Comment (fviernau) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:230]: > The problem here is that without this code, a package that actually is a project outside of the working tree would not have any VCS information at all, 

I do not understand this, can you help? (I wonder why not `vcs ? VcsInfo.EMPTY; vcsProcesses=...` is possible)

**Review by fviernau — CHANGES_REQUESTED** [review]

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 3 above)
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:230]: > I wonder why not `vcs ? VcsInfo.EMPTY; vcsProcessesed=...` is possible

Ah, I think I now got what you mean: Basically, use `processProjectVcs()` only for `vcsProcessed`. That I could do.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt [hunk 6]
```diff
@@ -191,14 +192,30 @@ class Cargo(
...
+            cargoPkg.takeUnless { it.isProject(workingDir) }?.toPackage(hashes)
         }
 
         return listOf(ProjectAnalyzerResult(project, nonProjectPackages))
     }
 }
 
-private fun CargoMetadata.Package.isProject() = source == null
+/**
+ * Return the local path for this Cargo package if applicable, or null if the Cargo package is not local.
```
[the remark this answers is not in the document]
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:203]: > Is this always an absolute path

Yes, because it's derived from `definitionFile` which is guaranteed to be absolute.

> should it be mentioned in the docs or even checked with an assertion?

I'm simply calling `absoluteFile` now to make it work in any case.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 3 above)
Comment (fviernau) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:230]: Should have been `=` instead of `?`, but you got it. 

You don't have to change it. I just wanted to have it clear, since in my NPMSupport improvements PR we discarded the changes for `vcs` unprocessed recently. And I believe it was because of rationale that it shouldn't be processed. I'm also fine with changing the decision and just keep your code as-is in this regard. up to you.

Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:230]: I've already changed it locally, and it reduces the diff in test output, so that's probably good thing for review readability anyway.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt [hunk 7]
```diff
@@ -191,14 +192,30 @@ class Cargo(
...
+        ?.removeSuffix(")")?.substringBefore("#")?.let { File(it) }
+
+/**
+ * Return whether this Cargo package is supposed to be regarded as an ORT project. The [workingDir] is used to check
+ * whether a local path Cargo package lies outside the project directory.
+ */
+private fun CargoMetadata.Package.isProject(workingDir: File): Boolean {
+    val isWithinWorkingDir = getLocalPath()?.startsWith(workingDir) == true
+
+    // If a package cannot be retrieved from anywhere but lies inside the working directory, treat it as a project.
```
[the remark this answers is not in the document]
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:216]: `analysisRoot` is constant per analyzer run, whereas `workingDir` changes with the `definitionFile`. We want the latter to understand whether a path dependency is out-of-tree of the *current* project the `definitionFile` belongs to.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (fviernau) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:203]: > Yes, because it's derived from `definitionFile` which is guaranteed to be absolute.

My question was about the `File` returned by `getLocalPath()` not about the parent of the `definitionFile`.

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (fviernau) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:216]: Hm, so what if we have a repository with these two files:
- `Cargo.toml`
- `dir/Cargo.toml`

Then `isProject( `Cargo.toml`)`  would either return `true` or `false` depending on which definition file is being currently processed. In my intuition the return value of whether a file is a project or not should remain constant 
in an analyzer result. (Maybe its just a matter of naming)  What do you think ?

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:203]: Yes, that's also guaranteed to be absolute (as it's derived from a URI).

[the remark this answers is not in the document]
Comment (fviernau) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt:203]: Would a `require` check make sense / mention in the function docs of `getLocalPath()` ?

File: plugins/package-managers/cargo/src/main/kotlin/Cargo.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt]: Thanks for insisting, I know know what confused me: The tests compare an isolated `ProjectAnalyerResult`, not a whole `AnalyzerResult`. This explains why the expected tests results actually should not change with this PR. I've manually verified that #8571 is still fixed.

[the remark this answers is not in the document]
Comment (fviernau) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt]: So, are you saying that the multiple definition files scenario I've mentioned works with this PR? (So, no issue there)

[the remark this answers is not in the document]
Comment (sschuberth) [reply plugins/package-managers/cargo/src/main/kotlin/Cargo.kt]: Your example, IIUC, only pledged for a given Cargo project to be consistently treated as an ORT project *or* as an ORT package *independently* of the current working directory. And yes, that's the case, and the current code now also resembles the original code more closely which was also using `analyzerRoot`:

https://github.com/oss-review-toolkit/ort/blob/adf14d48ec85fab9ab0ef6ec8250f644e1e29814/plugins/package-managers/cargo/src/main/kotlin/Cargo.kt#L130-L138

**Review by fviernau — APPROVED** [review]
