### PR TITLE
Fix processing of copyrights along with its performance issues

### LINKED ISSUE #3511: Performance issues with reporter (AsciidocTemplate + CycloneDX at least)
We experience problems with the reporter with very large projects. The issue can be seen with a vanilla scan of Keycloak (https://github.com/keycloak/keycloak).

Furthermore, we use the reporter options: `-f AsciidocTemplate,CycloneDX,NoticeTemplate,SpdxDocument,StaticHTML,WebApp`.

The report will usually just not finish - no stacktrace, nothing. If it finishes, the run takes > 1 hour on a 8 GB 4 CPU core machine.

Profiling revealed the biggest issue to be the `CopyrightStatementsProcessor.kt`:

- On my system, ORT never finished https://github.com/oss-review-toolkit/ort/blob/8fa22855c6e32d6f7e399fe5af41726ac7f0a5ef/utils/src/main/kotlin/CopyrightStatementsProcessor.kt#L146 - this can be fixed by making `    val originalStatements: List<String>` a `Set<String>` in `Parts`. What is the rationale here for needing a list if everything gets merged anyways? 
- When using the List <-> Set quickfix, the reporter still used a lot of time (in particular disclosure document and CycloneDX). About 60% of that time is spent with replacing regexes in https://github.com/oss-review-toolkit/ort/blob/8fa22855c6e32d6f7e399fe5af41726ac7f0a5ef/utils/src/main/kotlin/CopyrightStatementsProcessor.kt#L213 - the comment in this method seems to imply this is not necessary? I could try optimizing this method, but if it is only interesting for debugging purposes, I would tend to delete/replace it. 

RAM usage is about 4 GB (in particular due to loading a lot of copyrights) but that may still be acceptable.

### PR DESCRIPTION
**Pull request by fviernau**
Previously, `CopyrightStatements.process()` was called once per license finding file location by the `LicenseInfoResolver`.
This does not make sense and leads to poor performance as the `process()` function is not super fast (but fast enough if called only reasonably often). Once more, the license API was designed to hold the pre-processed copyright statements. This does not make any sense because the processing is different depending on the use case.

Do the processing properly, thereby reduce the number of calls to `process()` tremendously and change the design such that copyright statements are always processed on-the-fly. This fixes #3511.

### CODE REVIEW

File: helper-cli/src/main/kotlin/common/Utils.kt [hunk 1]
```diff
@@ -254,7 +254,10 @@ internal fun OrtResult.processAllCopyrightStatements(
         licenseInfoResolver.resolveLicenseInfo(id).forEach innerForEach@{ resolvedLicense ->
             if (omitExcluded && resolvedLicense.isDetectedExcluded) return@innerForEach
 
-            val copyrights = resolvedLicense.getResolvedCopyrights(omitExcluded).flatMap { resolvedCopyright ->
+            val copyrights = resolvedLicense.getResolvedCopyrights(
```
Comment (sschuberth) [inline helper-cli/src/main/kotlin/common/Utils.kt:257]: Commit message:

> Remove the BTW wrong processing of copyrights

Does "BTW" stand for "by the way"? If so, the title wording sounds a bit odd to me. Can you think of a way to reword it without using an abbreviation?

> This fixes and issue

"an issue"

> The reports can be computed in about 10 minutes.

Maybe "can *now* be computed"?

Generally, I'm wondering why the (seemingly rather sophisticated) tests that we have in this area apparently did not catch the issues described in the commit message. Could you maybe also add a comment on that to the commit message?

File: model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt [hunk 2]
```diff
@@ -64,6 +64,21 @@ data class ResolvedLicenseInfo(
 ) : Iterable<ResolvedLicense> by licenses {
     operator fun get(license: SpdxSingleLicenseExpression): ResolvedLicense? = find { it.license == license }
 
+    /**
```
Comment (sschuberth) [inline model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt:67]: Commit message: s/CycloneDexReporter/CycloneDxReporter/

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: helper-cli/src/main/kotlin/common/Utils.kt (hunk 1 above)
Comment (fviernau) [reply helper-cli/src/main/kotlin/common/Utils.kt:257]: All done.

File: model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt (hunk 2 above)
Comment (fviernau) [reply model/src/main/kotlin/licenses/ResolvedLicenseInfo.kt:67]: Done.

**Comment by sschuberth** [comment]
@fviernau is this indeed still a draft PR, or ready for review by now?

**Comment by fviernau** [comment]
> @fviernau is this indeed still a draft PR, or ready for review by now?

Thanks for the hint @sschuberth! I've removed the draft state.

**Review by sschuberth — APPROVED** [review]
