### PR TITLE
fix(Npm): Stop creating dangling packages for non-workspace projects

### LINKED ISSUE #9195: NPM's implementation of `skip-excluded-scopes` returns dangling packages
The scope is properly excluded, but the `Package` instances are still contained in the returned `ProjectAnalyzerResult`.
This is illustrated by `shrinkwrap-skip-excluded-scopes-expected-output.yml`.

Note: Probably there is a similar issue with other package managers inheriting from `Npm`.

### PR DESCRIPTION
**Pull request by fviernau**
According to the code comment directly above, adding the packages is necessary only for projects using workspaces, see also [1]. Executing the logic is not necessary for non-workspace projects and may lead to non-referenced packages in the result, for example when scope excludes are used. Fix that by executing the code only conditionally.

Note: The workspaces support for Pnpm and Yarn currently represents workspace submodules as non-referenced packages. This change is a preparation for fixing the workspace submodule representation.

Fixes #9195.

[1]: https://github.com/oss-review-toolkit/ort/pull/4034/files#diff-28d89c724dd945fe93dec5700d61d4dcdaab02f492e09613c8fee6ac5c76cbe6R363-R366

### CODE REVIEW

File: plugins/package-managers/node/src/main/kotlin/Npm.kt [hunk 1]
```diff
@@ -198,8 +198,11 @@ open class Npm(
 
         // Create packages for all modules found in the workspace and add them to the graph builder. They are
         // reused when they are referenced by scope dependencies.
-        val packages = parseInstalledModules(workingDir)
-        graphBuilder.addPackages(packages)
+        val isWorkspacesProject = (findWorkspaceSubmodules(workingDir) - workingDir).isNotEmpty()
```
Comment (mnonnenmacher) [inline plugins/package-managers/node/src/main/kotlin/Npm.kt:201]: For the shinkwrap test project, do you know why those now removed packages were actually installed in the first place, if they are not referenced from anywhere?

Comment (fviernau) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:201]: `npm` does not know about the scope excludes.

Comment (mnonnenmacher) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:201]: Thanks, I somehow missed that the test asset was specific to testing scope excludes.

**Review by mnonnenmacher — APPROVED** [review]
