### PR TITLE
GoMod: Fix support for replace directives

### LINKED ISSUE #5604: GoMod:  NoSuchElementException: Key xxx is missing in the map
In a project using GoMod as package manager and the `replace` directive in the `go.mod` definition file, the analyzer produces an issue caused by the following exception:

```
java.util.NoSuchElementException: Key com.acme/module is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
	at org.ossreviewtoolkit.analyzer.managers.GoMod.getModuleGraph$moduleInfo(GoMod.kt:155)
	at org.ossreviewtoolkit.analyzer.managers.GoMod.getModuleGraph$parseModuleEntry(GoMod.kt:159)
	at org.ossreviewtoolkit.analyzer.managers.GoMod.getModuleGraph(GoMod.kt:179)
	at org.ossreviewtoolkit.analyzer.managers.GoMod.resolveDependencies(GoMod.kt:100)
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:264)
	at org.ossreviewtoolkit.analyzer.PackageManagerRunner$run$3.invokeSuspend(Analyzer.kt:317)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

```

The "Key" in the exception message points to the module that is subject of a `replace` directive. The relevant part from `go.mod` looks as follows:

```
module com.acme/project

go 1.17

replace com.acme/module => vcs.acme.com/repos/com.acme.my.pkg.module.git v0.8.0

require (
	com.acme/module v0.8.0
	github.com/eclipse/ditto-clients-golang v0.0.0-20211126080925-0676267c80ac
	github.com/eclipse/paho.mqtt.golang v1.3.5
)

require (
	github.com/Azure/azure-sdk-for-go/sdk/azcore v0.20.0 // indirect
	github.com/Azure/azure-sdk-for-go/sdk/azidentity v0.12.0 // indirect
        ...
)

```
`go mod why` gives us:
```

$ go mod why -m -vendor com.acme/project
go: downloading vcs.acme.com/repos/com.acme.my.pkg.module.git v0.8.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.5
go: downloading github.com/eclipse/ditto-clients-golang v0.0.0-20211126080925-0676267c80ac
go: downloading golang.org/x/net v0.0.0-20211123203042-d83791d6bcd9
...
# com.acme/project
com.acme/project

```
ORT executes the `go list` command. Here the affected module is listed, together with the replacement package:

```
$ go list -m -json all
{
	"Path": "com.acme/project",
	"Main": true,
	"Dir": "/temp",
	"GoMod": "/temp/go.mod",
	"GoVersion": "1.17"
}
{
	"Path": "com.acme/module",
	"Version": "v0.8.0",
	"Replace": {
		"Path": "vcs.acme.com/repos/com.acme.my.pkg.module.git",
		"Version": "v0.8.0",
		"Time": "2022-01-12T06:35:03Z",
		"Dir": "/tmp/go/pkg/mod/vcs.acme.com/repos/com.acme.my.pkg.module.git@v0.8.0",
		"GoMod": "/tmp/go/pkg/mod/cache/download/vcs.acme.com/repos/com.acme.my.pkg.module.git/@v/v0.8.0.mod",
		"GoVersion": "1.17"
	},
	"Dir": "/tmp/go/pkg/mod/vcs.acme.com/repos/com.acme.my.pkg.module.git@v0.8.0",
	"GoMod": "/tmp/go/pkg/mod/cache/download/vcs.acme.com/repos/com.acme.my.pkg.module.git/@v/v0.8.0.mod",
	"GoVersion": "1.17"
}
{
	"Path": "github.com/Azure/azure-sdk-for-go/sdk/azcore",
	"Version": "v0.20.0",
	"Time": "2021-10-22T18:35:30Z",
	"Indirect": true,
	"Dir": "/tmp/go/pkg/mod/github.com/!azure/azure-sdk-for-go/sdk/azcore@v0.20.0",
	"GoMod": "/tmp/go/pkg/mod/cache/download/github.com/!azure/azure-sdk-for-go/sdk/azcore/@v/v0.20.0.mod",
	"GoVersion": "1.16"
}
...

```
The `GoMod` package manager evaluates the `Replace` property for the `com.acme/module` package and stores it internally under the `Path` specified there: `vcs.acme.com/repos/com.acme.my.pkg.module.git`. Then it executes the `go mod graph` command. As shown below, here the package is referenced via its original path and thus cannot be resolved:

```
$ go mod graph
com.acme/project com.acme/module@v0.8.0
com.acme/project github.com/Azure/azure-sdk-for-go/sdk/azcore@v0.20.0
com.acme/project github.com/Azure/azure-sdk-for-go/sdk/azidentity@v0.12.0
...

```

### PR DESCRIPTION
**Pull request by mnonnenmacher**
Change `getModuleInfos` to return a map which associates the module paths to the related module info. The keys of the map contain both, the paths of replaced modules and those of their replacements. This fixes support for replace directives which do not only replace the version but also the path of a module. Previously, this caused a `NoSuchElementException` because module infos where only associated to the path of the replacing module, but the output of `go mod graph` also contains the paths of replaced modules.

Fixes #5604.

### CODE REVIEW

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 1]
```diff
@@ -101,7 +101,7 @@ class GoMod(
         val projectDir = definitionFile.parentFile
 
         stashDirectories(projectDir.resolve("vendor")).use { _ ->
-            val moduleInfoForModuleName = getModuleInfos(projectDir).associateBy({ it.path }, { it })
+            val moduleInfoForModuleName = getModuleInfos(projectDir)
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt:104]: Commit message:

> module infos where only

"were"

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 2]
```diff
@@ -222,7 +222,7 @@ class GoMod(
      * Return the list of all modules contained in the dependency tree with resolved versions and the 'replace'
      * directive applied.
      */
-    private fun getModuleInfos(projectDir: File): List<ModuleInfo> {
+    private fun getModuleInfos(projectDir: File): Map<String, ModuleInfo> {
```
Comment (fviernau) [inline analyzer/src/main/kotlin/managers/GoMod.kt:225]: I remembered I tried to fix some bug with the replace directive but the approach ran into some other bug.
Maybe this is interresting to look at: https://github.com/oss-review-toolkit/ort/tree/go-mod-replace-directive-issue-fix

Comment (mnonnenmacher) [reply analyzer/src/main/kotlin/managers/GoMod.kt:225]: I'll adapt the test like you did in that commit to at least verify this fix also in the test. Let's see if it works.

Comment (mnonnenmacher) [reply analyzer/src/main/kotlin/managers/GoMod.kt:228]: I have added another replace directive to the test now, this showed that some more code changes were required to get the correct result, see the code comments.

**Comment by sschuberth** [comment]
Code-wise this is LGTM, but I'd appreciate @fviernau to approve as he's more familiar with the inner GoMod workings.

**Review by oheger-bosch — APPROVED** [review]
