### PR TITLE
fix(reporter): Add authors to concluded license

### LINKED ISSUE #9599: Package curations: In some cases, they authors don't show up in the Disclosure Document
Package curations are well described [here](https://oss-review-toolkit.org/ort/docs/configuration/package-curations#curations-basics).
There are situations where one does **not want to scan a package (with scancode)**, but instead give the appropriate license identifier and a list of authors in a curation file.

For this to work, some conditions must be met:

* The respective curation file of the package contains one or more `authors` (which might be prefixed by "Copyright (c) ..."
* It contains a `concluded_license`
* The ORT configuration has scanner option `scanner.skipConcluded: true`
* The ORT configuration has global option  `addAuthorsToCopyrights: true`

### To Reproduce

Steps to reproduce the behaviour:

Step 1: Set the ORT configuration as stated above under "conditions".

Step 2: Set up a simple NPM project, an example package.json could be:

```json
{
  "name": "Some name",
  "version": "0.0.1",
  "description": "Some description",
  "main": "index.js",
  "license": "ISC",
  "repository": {
    "type": "git",
    "url": "some valid url that can be reached"
  },
  "dependencies": {
    "mime": "1.6.0"
  }
}
```
So, just a single dependency to the _mime_ package.

Step 3: Manually trigger the ORT Analyzer

```sh
$ ort analyze -i . -o .
```
This create a result file _analyzer-result.yml_.

Step 4: Tweak the ORT Analyzer result

For simplicity sake, directly tweak this file with a curation for the mime package. Therefore, add the following section to the end of the _analyzer-result.yml_ file:

```
scanner: null
advisor: null
evaluator: null
resolved_configuration:
  package_curations:
    - provider:
        id: "ocaasPackageCurationProvider"
      curations:
        - id: "NPM::mime:1.6.0"
          curations:
            comment: "Test by John Doe"
            authors:
              - "Copyright (c) 2024 John Doe"
            concluded_license: "BSD-2-Clause"
```
You see, we are giving the mime package a different `concluded_license`and added `authors`.

Step 5: Manually trigger the ORT Scanner (scancode)

```sh
$ ort scan -i analyzer-result.yml -o . --skip-excluded
```
This will generate a result file _scan-result.yml_.

Step 6: Manually trigger the generation of reports

```sh
$ ort --info report -i scan-result.yml -o . -f PdfTemplate,WebApp
```
This generates the files _AsciiDoc_disclosure_document.pdf_ and _scan-report-web-app.html_.

### Expected behavior

In the Web App Report, we see for the _mime_ package:

* Authors: Copyright (c) 2024 John Doe
* Licenses -> Concluded SPDX: BSD-2-Clause
* Licenses -> Declared SPDX: MIT

So, yes, we have successfully overwritten the original author(s) and have changed the license from MIT to BSD-2-Clause.

And: You won't see any scan results in files, because the scanner (scancode) did not run for this package. This was intended.
Everything all right for the Web App Report.

In the Disclose Document, we **expect to see**  for the _mime_ package:

Package URL pkg:npm/mime@1.6.0

* has license BSD-2-Clause
* under this license, has "Copyright (c) 2024 John Do

Outcome: BSD-2-Clause license is displayed correctly, but **the copyright statement is missing**.

### Additional context

This problem only appears when either

* The ORT Analyzer initially did not detect a (declared) license at all
* The curation changes the license from A to B.

### First analysis and possible fix

I did a quite time consuming analysis and will provide a PR how it could be fixed (potentially).

### PR DESCRIPTION
**Pull request by wkl3nk**
Include authors for package dependencies when both `concluded_license` and `authors` are curated, and ORT is configured with the `addAuthorsToCopyrights` option enabled. This ensures that package authors appear under the respective concluded license in the Disclosure Document.

This behaviour applies when the Scanner option `skipConcluded` is enabled, having the effect that the scan stage is skipped for the particular package dependency in this case, and if either the _concluded_ license is different from the _declared_ license or if no license is _declared_ at all.

Fixes #9599.

### CODE REVIEW

**Comment by wkl3nk** [comment]
You may notice that the added code block is just a duplication of a code block that can be found already in code in the same file that handles copyright locations for **declared** licenses. So what this fix does is to apply the same mechanisms now also for **concluded** licenses.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt [hunk 1]
```diff
@@ -83,6 +83,26 @@ class LicenseInfoResolver(
                 licenseInfo.concludedLicenseInfo.concludedLicense?.also {
                     originalExpressions += ResolvedOriginalExpression(expression = it, source = LicenseSource.CONCLUDED)
                 }
+
+                licenseInfo.declaredLicenseInfo.authors.takeIf { it.isNotEmpty() && addAuthorsToCopyrights }?.also {
```
Comment (mnonnenmacher) [inline model/src/main/kotlin/licenses/LicenseInfoResolver.kt:87]: I'd like to understand better in which situation this is required. Is it when the concluded license contains licenses which are not present in the declared licenses?

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt [hunk 2]
```diff
@@ -83,6 +83,26 @@ class LicenseInfoResolver(
...
+                        copyrights = it.mapTo(mutableSetOf()) { author ->
+                            val statement = "Copyright (C) $author".takeUnless {
+                                author.contains("Copyright", ignoreCase = true)
+                            } ?: author
+
+                            ResolvedCopyrightFinding(
+                                statement = statement,
+                                location = UNDEFINED_TEXT_LOCATION,
+                                matchingPathExcludes = emptyList()
+                            )
```
Comment (mnonnenmacher) [inline model/src/main/kotlin/licenses/LicenseInfoResolver.kt:102]: Please move this to a helper function to avoid the duplication.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt (hunk 1 above)
Comment (wkl3nk) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:87]: If there is a curation, then in the Disclosure Document only the **concluded** license is displayed. The scanner stage is skipped for this particular package (option: _scanner.excludeConcluded_). So the information about the authors and copyrights (locations) comes from the curation file, and **not** from any lines in some pieces of code. What I saw in the code is is that the _declaredLicenses_ are given these dummy locations (from the curations file), while the _concludedLicenses_ don't get this information. From a logical perspective, as the source of the conclusion comes from the curation file, it would be logic to also add the authors from the curation file as "dummy" locations.

It is required when the ORT Analyzer is not able to pick up a license for a package. In a concrete case, this happened for the **SwiftPM** Analyzer and package [LicensePlist](https://github.com/mono0926/LicensePlist). As this package deals with licenses, there were a mass of false positives found by scancode, so it was decided to skip the scan step and instead write a curation, and add the author in the curation. This way, the license obligation to "include the copyright notice" could be met - if it would work.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt (hunk 2 above)
Comment (wkl3nk) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:102]: OK.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt [hunk 3]
```diff
@@ -98,23 +102,7 @@ class LicenseInfoResolver(
...
-                            } ?: author
-
-                            ResolvedCopyrightFinding(
-                                statement = statement,
-                                location = UNDEFINED_TEXT_LOCATION,
-                                matchingPathExcludes = emptyList()
-                            )
-                        }
-                    )
+                    locations += getAuthorsAsCopyrightTextLocation(it)
```
Comment (sschuberth) [inline model/src/main/kotlin/licenses/LicenseInfoResolver.kt:105]: As the change is quite complex to understand (at least for me), I'd appreciate doing more fine-granular commit steps:

1. Extract the existing code to a function and announce the upcoming reuse in the commit message. I believe the function name should not include the word "Text". I prose "resolveCopyrightFromAuthors" or similar.
2. Add a disabled test that fails. That allows to easily checkout that commit and enable the test to quickly convince yourself that there is an issue, and what it is about.
3. Apply the fix together with enabling the test.

**Review by sschuberth — CHANGES_REQUESTED** [review]
I didn't have time yet to review this content-wise, but I still plan to do so, but probably not before early next week.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt (hunk 3 above)
Comment (wkl3nk) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: Okay, I split it up in 3 separate commits to make more transparent what are pure refactorings, and which parts actually change the license/copyright resolution process logic.

File: model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt [hunk 4]
```diff
@@ -589,6 +610,22 @@ class LicenseInfoResolverTest : WordSpec({
...
+                    declaredLicenses = setOf("MIT"),
+                    concludedLicense = SpdxExpression.parse("BSD-2-Clause")
+                )
+            )
+
+            val resolver = createResolver(licenseInfos, addAuthorsToCopyrights = false)
+
+            val result = resolver.resolveLicenseInfo(pkgId)
+            result should containCopyrightStatementsForLicenseExactly("BSD-2-Clause")
+        }
```
Comment (mnonnenmacher) [inline model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt:628]: These new tests should be in a separate commit, they are not related to the extraction of the new function.

**Review by mnonnenmacher — CHANGES_REQUESTED** [review]
Except for the one comment this change looks good to me. @sschuberth Do you also want to have another look?

File: model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt (hunk 4 above)
Comment (sschuberth) [reply model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt:628]: And please use the more explicit `.config(enabled = false)` syntax.

File: model/src/test/kotlin/licenses/TestData.kt [hunk 5]
```diff
@@ -43,6 +43,7 @@ import org.ossreviewtoolkit.utils.spdx.toSpdx
 import org.ossreviewtoolkit.utils.test.scannerRunOf
 
 val authors = setOf("The Author", "The Other Author")
+val authorsWithCopyright = setOf("Copyright (C) 2024 The Author", "The Other Author")
```
Comment (sschuberth) [inline model/src/test/kotlin/licenses/TestData.kt:46]: Why does the variable name say "...WithCopyright" if at least the second entry comes without a Copyright?

File: model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt (hunk 4 above)
Comment (sschuberth) [reply model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt:628]: Or at least explain the syntax, which is uncommon in our code base, in the commit that adds the tests.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt [hunk 6]
```diff
@@ -83,6 +83,10 @@ class LicenseInfoResolver(
                 licenseInfo.concludedLicenseInfo.concludedLicense?.also {
                     originalExpressions += ResolvedOriginalExpression(expression = it, source = LicenseSource.CONCLUDED)
                 }
+
+                licenseInfo.declaredLicenseInfo.authors.takeIf { it.isNotEmpty() && addAuthorsToCopyrights }?.also {
+                    locations += resolveCopyrightFromAuthors(it)
```
Comment (sschuberth) [inline model/src/main/kotlin/licenses/LicenseInfoResolver.kt:88]: TBH, I still don't understand the details *why* this is necessary. Can it be that the real reason is not related to *having* a concluded license, but to *not* having a declared license, and so the below logic does not kick in?

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:88]: Or is it more like:

1. Copyrights / authors are associated with specific licenses.
2. A concluded license trumps all other licenses.
3. If both a concluded license and a declared license are present, but only the declared license has a Copyright / author associated, that will not be used as the concluded license it taken instead of the declared license.

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:88]: As @mnonnenmacher just explained to me, it's probably a mixture of both of the above: The problems occurs if there is a concluded license that is not also present as a declared license (which is esp. the case if there are no declared licenses).

File: model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt (hunk 4 above)
Comment (wkl3nk) [reply model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt:630]: I moved the tests into a separate commit. Enabled.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt (hunk 6 above)
Comment (wkl3nk) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:88]: Yes, I guess it happens if a.) _declared_ and _concluded_ license are not the same (overwritten in curation) or there is no _declared_ license at all.

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:88]: Hmm, you "guess" what you're fixing here? 😉 Us all having some more confidence in understanding what exact is being fixed would be great.

To document that, I propose a more concise commit message like the following (which also drops the explicit mention of the disclosure document, as the fix is not specific to that, and the fix is in the model, not in the reporter):

```
fix(model): Apply author to copyright mapping also for concluded licenses

As concluded licenses are supposed to trump other licenses, they are
usually taken instead of declared and detected licenses in reports. When
doing do, and the concluded license is not among the other licenses, any
author information that is configured to be mapped to copyright would be
dropped. To prevent that, apply the same author to copyright mapping that
is done for declared licenses also for concluded licenses.
```

File: model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt [hunk 7]
```diff
@@ -589,6 +589,45 @@ class LicenseInfoResolverTest : WordSpec({
             result should containCopyrightStatementsForLicenseExactly("LicenseRef-a")
             result should containCopyrightStatementsForLicenseExactly("LicenseRef-b")
         }
+
+        "resolve copyrights from authors in concluded license" {
```
Comment (sschuberth) [inline model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt:593]: Also here, you're not testing something that's specific to disclosure documents, so your commit message should not mention that. Any our test is in the model, not the reporter.

Comment (sschuberth) [reply model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt:593]: PS: I liked the previous approach with disabled test being added beforehand better, but this can stay as-is now from my perspective.

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt (hunk 6 above)
Comment (wkl3nk) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:88]: Thanks, I took over the commit message.

File: model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt (hunk 7 above)
Comment (wkl3nk) [reply model/src/test/kotlin/licenses/LicenseInfoResolverTest.kt:593]: Adapted the commit message.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt [hunk 8]
```diff
@@ -83,6 +83,10 @@ class LicenseInfoResolver(
                 licenseInfo.concludedLicenseInfo.concludedLicense?.also {
                     originalExpressions += ResolvedOriginalExpression(expression = it, source = LicenseSource.CONCLUDED)
                 }
+
```
Comment (sschuberth) [inline model/src/main/kotlin/licenses/LicenseInfoResolver.kt:86]: Unfortunately, I had a typo in my proposed commit message: "to be mapped to copyright" needs to say "to be mapped to copyright*s*".

**Review by sschuberth — CHANGES_REQUESTED** [review]
Just one more typo to fix 😄

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt (hunk 8 above)
Comment (wkl3nk) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt:86]: 1 typo fixed

**Review by sschuberth — APPROVED** [review]
