### PR TITLE
Scanner: Fail early on misconfigured criteria and version

### LINKED ISSUE #6581: Scanner: Frequent constraint violations on insertion to ProvenanceBasedPostgresStorage
When running scans against random projects with latest ORT, I usually see multiple occurences
of constraint violations in the logs. I'm running ORT's `scanner` command only on one machine, and no other `scanner` command does access the database in parallel.

```
WARN  Exposed - Transaction attempt #0 failed: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://github.com/janl/mustache.js.git, 813e273a658677852ab37e6f47c98a9d9352ccde, ScanCode, 31.2.1, --copyright --license --info --strip-root --timeout 300 --json-pp) already exists.. Statement(s): INSERT INTO provenance_scan_results (artifact_hash, artifact_url, scan_summary, scanner_configuration, scanner_name, scanner_version, vcs_revision, vcs_type, vcs_url) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://github.com/janl/mustache.js.git, 813e273a658677852ab37e6f47c98a9d9352ccde, ScanCode, 31.2.1, --copyright --license --info --strip-root --timeout 300 --json-pp) already exists.
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:64)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:141)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:127)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:71)
	at org.ossreviewtoolkit.scanner.storages.ProvenanceBasedPostgresStorage$write$1.invoke(ProvenanceBasedPostgresStorage.kt:144)
	at org.ossreviewtoolkit.scanner.storages.ProvenanceBasedPostgresStorage$write$1.invoke(ProvenanceBasedPostgresStorage.kt:143)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:215)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:241)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:240)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:190)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:249)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:160)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:146)
	at org.ossreviewtoolkit.model.utils.DatabaseUtils.transaction(DatabaseUtils.kt:120)
	at org.ossreviewtoolkit.scanner.storages.ProvenanceBasedPostgresStorage.write(ProvenanceBasedPostgresStorage.kt:143)
	at org.ossreviewtoolkit.scanner.Scanner.storeProvenanceScanResult(Scanner.kt:549)
	at org.ossreviewtoolkit.scanner.Scanner.runPathScanners(Scanner.kt:383)
	at org.ossreviewtoolkit.scanner.Scanner.scan(Scanner.kt:155)
	at org.ossreviewtoolkit.scanner.Scanner$scan$4.invokeSuspend(Scanner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runScanners(ScannerCommand.kt:232)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:159)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:76)
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://github.com/janl/mustache.js.git, 813e273a658677852ab37e6f47c98a9d9352ccde, ScanCode, 31.2.1, --copyright --license --info --strip-root --timeout 300 --json-pp) already exists.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:190)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:152)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:26)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:123)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:131)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62)
	... 39 common frames omitted
```

### PR DESCRIPTION
**Pull request by fviernau**
**To be merged after** #6665.

Fixes #6581.

BREAKING CHANGE:
- The scanner will now fail hard if this mis-configuration accurs instead of tolerating it with caching "disabled".

### CODE REVIEW

File: scanner/src/main/kotlin/Scanner.kt [hunk 1]
```diff
@@ -79,6 +84,18 @@ class Scanner(
...
+
+        scannerWrappers.values.flatten().distinct().forEach { scannerWrapper ->
+            scannerWrapper.criteria?.run {
+                val rangesList = createRangesList(minVersion, maxVersion)
+                val version = Semver.parse(scannerWrapper.details.version) ?: return@forEach
+
+                require(rangesList.isSatisfiedBy(version)) {
+                    "The version range [$minVersion, $maxVersion) specified in criteria for scanner " +
+                            "'${scannerWrapper.details.name}' is not satisfied by the available version: $version"
+                }
```
Comment (sschuberth) [inline scanner/src/main/kotlin/Scanner.kt:96]: As discussed at the OCD, I'm not sure whether this approach of failing hard is a good one, or whether we instead simply shouldn't try to *write* scan results outside of `[$minVersion, $maxVersion)` to the scan storage and emit a warning about that. That way locally still a newer scanner version could be tested while having a scan storage configured. And there would be some nice symmetry in that both read and write operations adhere to `[$minVersion, $maxVersion)`. I'm curious about the feedback from @mnonnenmacher here.

File: scanner/src/main/kotlin/Scanner.kt [hunk 2]
```diff
@@ -79,6 +84,18 @@ class Scanner(
         require(scannerWrappers.isNotEmpty() && scannerWrappers.any { it.value.isNotEmpty() }) {
             "At least one ScannerWrapper must be provided."
         }
+
+        scannerWrappers.values.flatten().distinct().forEach { scannerWrapper ->
+            scannerWrapper.criteria?.run {
```
Comment (mnonnenmacher) [inline scanner/src/main/kotlin/Scanner.kt:89]: IMO it would be better to just call `scannerWrapper.criteria?.matches(scannerWrapper.details)` here, this would also validate that the name and configuration match.

File: scanner/src/main/kotlin/Scanner.kt (hunk 1 above)
Comment (mnonnenmacher) [reply scanner/src/main/kotlin/Scanner.kt:96]: I think it's better to fail if the configured criteria don't match the scanner details, because it could be very difficult for the user to figure out what's going wrong. For testing a new version it's not so much effort to adjust the version range in the config. And if you don't want to add the results to the storage it's also easy to adjust the list of storage writers.

**Review by mnonnenmacher — CHANGES_REQUESTED** [review]

File: scanner/src/main/kotlin/Scanner.kt (hunk 1 above)
Comment (fviernau) [reply scanner/src/main/kotlin/Scanner.kt:96]: @mnonnenmacher this was my reasoning as well. The cost of misconfiguration is IMHO just to high to tolerate it.
Look at what I did: 
- I filed a bug for this `ConstraintViolation` log entries.  
- I stopped my task of running my scan of some project until I have time to investigate the issue
- did some debugging and found the cause after a while

If I had a misconfigured CI I would have cause potentially many hours of unneeded execution time due to the cache being basically disable unintendedly.

File: scanner/src/main/kotlin/Scanner.kt
Comment (sschuberth) [inline scanner/src/main/kotlin/Scanner.kt:1]: Commit message: I'm not sure this classifies as a "fix". Maybe rather a "feat"?

File: scanner/src/main/kotlin/ScannerCriteria.kt
Comment (sschuberth) [inline scanner/src/main/kotlin/ScannerCriteria.kt:1]: Commit message: I'm not sure this classifies as a "fix". Maybe rather "docs"?

File: scanner/src/main/kotlin/Scanner.kt
Comment (mnonnenmacher) [inline scanner/src/main/kotlin/Scanner.kt:1]: Typos in commit message:
* "do no*t** match"
* "scan results **will** be looked up"
* "avail**a**ble scanner"
* "misconfiguration"
* "it **is** better"

**Review by mnonnenmacher — CHANGES_REQUESTED** [review]

File: scanner/src/main/kotlin/Scanner.kt
Comment (mnonnenmacher) [reply scanner/src/main/kotlin/Scanner.kt:1]: Did you forget to push after changing the commit messages?

Comment (mnonnenmacher) [reply scanner/src/main/kotlin/Scanner.kt:1]: You still have the typo in "avail**a**ble scanner" and "misconfiguration" is written without a dash.

File: scanner/src/main/kotlin/Scanner.kt [hunk 3]
```diff
@@ -79,6 +79,15 @@ class Scanner(
         require(scannerWrappers.isNotEmpty() && scannerWrappers.any { it.value.isNotEmpty() }) {
             "At least one ScannerWrapper must be provided."
         }
+
+        scannerWrappers.values.flatten().distinct().forEach { scannerWrapper ->
+            scannerWrapper.criteria?.let { criteria ->
+                require(criteria.matches(scannerWrapper.details)) {
+                    "The scanner details of scanner '${scannerWrapper.details.name}' must satisfy the configured " +
+                        "criteria for looking up scan storage entries."
```
Comment (mnonnenmacher) [inline scanner/src/main/kotlin/Scanner.kt:87]: It would be good to also print the configured criteria, I would suggest to use this:
`... do not satisfy the configured criteria '${criteria}'.

**Review by mnonnenmacher — CHANGES_REQUESTED** [review]

File: scanner/src/main/kotlin/Scanner.kt (hunk 3 above)
Comment (fviernau) [reply scanner/src/main/kotlin/Scanner.kt:87]: I deliberately didn't do this as it is easy to look it up by scanner name.

Comment (mnonnenmacher) [reply scanner/src/main/kotlin/Scanner.kt:87]: It would be even easier if the criteria was in the log message and does not have to be looked up at all. After all, this is not an error that should occur often so I'm not sure why concise is important.
In general I prefer if error messages describe the error ("does not satisfy") instead of the requirement ("must satisfy"), but that's the nit-pick part.

Comment (mnonnenmacher) [reply scanner/src/main/kotlin/Scanner.kt:87]: No, I will not block this because of a nit pick.

**Comment by sschuberth** [comment]
@heliocastro also just posted this stacktrace in [Slack](https://oss-review-toolkit.slack.com/archives/C9NNJ54B1/p1746693567419129):

```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "provenance_scan_results_vcs_type_vcs_url_vcs_revision_scanner_n"
  Detail: Key (vcs_type, vcs_url, vcs_revision, scanner_name, scanner_version, scanner_configuration)=(Git, https://user@github.com/scipy/scipy-mathjax.git, 36f4c898f2255e0c98eb6949cd67381552d5ffea, ScanCode, 32.3.3, --copyright --license --info --strip-root --timeout 600 --license-references --json --prefer-file-license) already exists.
```

But his use-case is that he runs multiple independent `ort scan` CLI invocations in parallel.
