### PR TITLE
fix(reporter): Only write major / minor SPDX license list version info

### LINKED ISSUE #9606: SPDX 2.2 conformance (invalid `licenseListVersion` produced)
### Describe the bug

After generating a SPDX SBOM in an unmanaged project, the `licenseListVersion` is set to "3.25.0", but SPDX 2.2 only allows two digits, e.g., "3.25"

### To Reproduce

Run in an unmanaged project

1. Generate an analysis
2. Then do a scan
3. Finally create a report
    ```
    ./gradlew cli:run --args="report -i scan-result.json -o . -f SpdxDocument"
    ```
5. See error

The generated SPDX has a `licenseListVersion` with 3 numeric versions

### Expected behavior

I expected the `licenseListVersion` to conform to the SPDX 2.2 standard.

### Additional context

This happens in `Unmanaged` projects, as far as I know.

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #9606.

### CODE REVIEW

File: plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt [hunk 1]
```diff
@@ -172,7 +172,7 @@ internal object SpdxDocumentModelMapper {
                 comment = params.creationInfoComment,
                 created = Instant.now().truncatedTo(ChronoUnit.SECONDS),
                 creators = creators,
-                licenseListVersion = SpdxLicense.LICENSE_LIST_VERSION.substringBefore("-")
+                licenseListVersion = SpdxLicense.LICENSE_LIST_VERSION.split('.').take(2).joinToString(".")
```
Comment (kikofernandez) [inline plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt:175]: This solution works, but it may be more efficient this other implementation, saving the splitting and joining back
```suggestion
                val licenseList = SpdxLicense.LICENSE_LIST_VERSION
                licenseListVersion = licenseList.substring(0, licenseList.lastIndexOf("_"))
```

I do not really know much Kotlin, so take this with a pinch of salt.

**Review by fviernau — APPROVED** [review]

File: plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt (hunk 1 above)
Comment (sschuberth) [reply plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt:175]: While `lastIndexOf("_")` would need to use `"."` instead, it would also not work for something like "1.2.3.4" as the input. Not that I'm expecting that to happen, but you never know 😉

Comment (kikofernandez) [reply plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt:175]: true!

Comment (sschuberth) [reply plugins/reporters/spdx/src/main/kotlin/SpdxDocumentModelMapper.kt:175]: BTW, otherwise I would have simply used `substringBeforeLast('.')`.
