### PR TITLE
ClearlyDefinedService: Support deserializing invalid curations

### LINKED ISSUE #3559: Analyzer : Warnings with Clearly Defined Curation Provider
In our pipeline run, we got these warnings today :
```
11:46:44.299 [main] WARN  org.ossreviewtoolkit.analyzer.curation.ClearlyDefinedPackageCurationProvider - Getting curations for 'Maven:com.google.code.gson:gson:2.8.6' failed with: MismatchedInputException: Cannot deserialize value of type `org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Facet` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 31] (through reference chain: org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Curation["described"]->org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Described["facets"]->org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Facets["dev"])
11:48:54.544 [main] WARN  org.ossreviewtoolkit.analyzer.curation.ClearlyDefinedPackageCurationProvider - Getting curations for 'Maven:com.google.code.gson:gson:2.8.6' failed with: MismatchedInputException: Cannot deserialize value of type `org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Facet` from Array value (token `JsonToken.START_ARRAY`)
 at [Source: (okhttp3.ResponseBody$BomAwareReader); line: 1, column: 31] (through reference chain: org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Curation["described"]->org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Described["facets"]->org.ossreviewtoolkit.clients.clearlydefined.ClearlyDefinedService$Facets["dev"])
```

It seems something has changed in the responses from the Clearly Defined Curation Provider.

### PR DESCRIPTION
**Pull request by sschuberth**
ClearlyDefined now returns HTTP 404 errors for non-existing curations,
see [1]. Lower the log level from "warn" to "debug" as not having a
curation is just fine with us if none is available.

Resolves #3559.

[1] https://github.com/clearlydefined/service/issues/795

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

**Comment by nnobelis** [comment]
I agree with the fix but the not with the reasoning : shouldn't we wait until Clearly Defined team addresses the linked ticket ? 
Your original comment on the thread was only from one week ago....

**Comment by sschuberth** [comment]
> shouldn't we wait until Clearly Defined team addresses the linked ticket ?

Ideally yes, but my past experience teaches me that this might take long. Also, it's yet undecided if they really agree that returning an empty JSON instead is what they want. Also see [this question](https://github.com/clearlydefined/service/issues/795#issuecomment-780598277) of mine.

Bottom line, I'd like to make this change now to clean our logs, and if they agree returning 404 was unintended and they return an empty JSON instead, we simply revert this commit.

**Comment by nnobelis** [comment]
I agree

**Review by nnobelis — APPROVED** [review]

File: analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt [hunk 1]
```diff
@@ -91,7 +91,7 @@ class ClearlyDefinedPackageCurationProvider(server: Server = Server.PRODUCTION)
         } catch (e: HttpException) {
             e.showStackTrace()
 
-            log.warn { "Getting curations for '${pkgId.toCoordinates()}' failed with: ${e.collectMessagesAsString()}" }
+            log.debug { "Getting curations for '${pkgId.toCoordinates()}' failed with: ${e.collectMessagesAsString()}" }
```
Comment (oheger-bosch) [inline analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt:94]: Not sure whether it is overkill, but would it make sense to evaluate the response status and treat a 404 differently? It seems to be a regular return code and not actually an error condition, so one could argue that there is no need to log anything. OTOH, a different error might still deserve a log statement on a higher level as it is unexpected.

Comment (fviernau) [reply analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt:94]: If the ticket linked in the commit message was implemented, I believe a debug log is fine.
If they don't implement it then IMO it would make sense to remove the log statement.
IMO we could keep it as is to avoid some back and forth and just assume the ticket will be implemented (soon).

**Review by fviernau — APPROVED** [review]

File: analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt (hunk 1 above)
Comment (sschuberth) [reply analyzer/src/main/kotlin/curation/ClearlyDefinedPackageCurationProvider.kt]: > would it make sense to evaluate the response status and treat a 404 differently?

Good idea, done.

**Review by oheger-bosch — APPROVED** [review]
