### PR TITLE
Gleam Dynamic Resolution

### LINKED ISSUE #11245: Simplify Gleam package manager to require a lockfile
**Scenario**

Given a project which has dependencies but no lockfile, the package manager 
is unable to determine any transitive dependencies. It always creates an analyzer error
to indicate that the result is incomplete, and reports only direct dependencies.

**Problem**

The implementation tolerates the lockfile to be absent. This tolerance seems to introduce quite
a bit of complexity into the mapping logic from ORT's model to Gleam's model. For example,
the inheritance hierarchy of the dependeny classes, along with a bit of code redundancy.
This seems to be a high price for a use case which does not work anyway (transitive deps are missing).

**Proposal**

Change the package manager implementation, so that it fails reporting any dependencies at all,
instead of only the direct ones, if: `project has dependencies AND lockfile is absent`.

..and apply the unlocked code simplifications. That is, the code can assume, for each dependency an
entry in `GleamManifest.packages` to be present. 

Note: My current understanding is, that the dependency tree construction can then only be based on `GleamManifest.packages`, plus a couple of fetches via the `HexApiClient` for the metadata.

**Future**

Question: In case of an absent lockfile, could we generate it on-the-fly?

### PR DESCRIPTION
**Pull request by maennchen**
Check the individual commits for details.

Resolves #11245.

### CODE REVIEW

**Comment by maennchen** [comment]
It looks like we just ran out of disk space.

```
ERROR: failed to build: failed to solve: rpc error: code = Unknown desc = write /opt/askalono/askalono: no space left on device
```

I used this action before: https://github.com/BRAINSia/free-disk-space
It is able to clean up ~52Gb (+ 12Gb from the current cleanup command)

Should I add a commit for it or do you have a better idea?

File: plugins/package-managers/gleam/src/main/kotlin/GleamDependencyHandler.kt [hunk 1]
```diff
@@ -41,24 +41,16 @@ internal class GleamDependencyHandler : DependencyHandler<GleamPackageInfo> {
...
-    private fun tryLock(dependency: GleamPackageInfo): GleamPackageInfo =
-        when (dependency) {
-            is ManifestPackageInfo -> dependency
-            is DependencyPackageInfo -> manifestPackagesByName[dependency.name]?.let {
-                ManifestPackageInfo(it)
-            } ?: dependency
-        }
-
-    override fun identifierFor(dependency: GleamPackageInfo): Identifier = tryLock(dependency).toIdentifier(context)
+    override fun identifierFor(dependency: GleamPackageInfo): Identifier = dependency.toIdentifier(context)
```
Comment (fviernau) [inline plugins/package-managers/gleam/src/main/kotlin/GleamDependencyHandler.kt]: Could the generic type parameter of this entire class be changed to `ManifestPackageInfo`?

Apart from that, could the inheritance hierarchy with `GleamPackageInfo` be dropped, so that only `ManifestPackageInfo` remains?

File: plugins/package-managers/gleam/src/main/kotlin/Gleam.kt [hunk 2]
```diff
@@ -159,6 +149,47 @@ class Gleam internal constructor(
...
+            !hasDependencies -> GleamManifest.EMPTY
+
+            !GleamCommand.isInPath() -> {
+                issues += Issue(
+                    source = projectType,
+                    message = "No lockfile found and the 'gleam' command is not available in PATH. " +
+                        "No dependencies were resolved."
+                )
+                GleamManifest.EMPTY
+            }
```
Comment (fviernau) [inline plugins/package-managers/gleam/src/main/kotlin/Gleam.kt]: IIRC other package managers simply use the command without explicitly checking whether it is available. If this is true, I believe we should align to do the same here.

File: plugins/package-managers/gleam/src/main/kotlin/Gleam.kt [hunk 3]
```diff
@@ -159,6 +149,47 @@ class Gleam internal constructor(
...
+
+            else -> {
+                val process = GleamCommand.run(workingDir, "deps", "download")
+                if (process.isSuccess) {
+                    issues += Issue(
+                        source = projectType,
+                        message = "No lockfile found. Dependencies were resolved by running 'gleam deps download'. " +
+                            "The results may not be reproducible.",
+                        severity = Severity.WARNING
+                    )
```
Comment (fviernau) [inline plugins/package-managers/gleam/src/main/kotlin/Gleam.kt]: Also for consistency, should we also drop this warning, because dynamic resolution is only done in case ORT has been configured to do so (`allowDynamicVersions`)?

**Comment by sschuberth** [comment]
> Should I add a commit for it or do you have a better idea?

While I would like @mnonnenmacher to comment on that, I'm in favor of giving it a try, esp. if it also helps us to reduce custom code.

File: plugins/package-managers/gleam/src/funTest/assets/projects/synthetic/no-lockfile/gleam.toml [hunk 4]
```diff
@@ -4,5 +4,5 @@ licences = ["MIT"]
 
 [dependencies]
 gleam_stdlib = ">= 0.34.0"
-gleam_json = { git = "git@github.com:gleam-lang/json.git", ref = "main" }
+gleam_json = { git = "https://github.com/gleam-lang/json.git", ref = "main" }
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/assets/projects/synthetic/no-lockfile/gleam.toml:7]: I guess this change is now necessary as a real download happens, which otherwise would have required an SSH key. I believe this justifies a dedicated explanation in a preceding commit.

File: plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt [hunk 5]
```diff
@@ -35,12 +41,15 @@ import org.ossreviewtoolkit.analyzer.analyze
...
 import org.ossreviewtoolkit.analyzer.withInvariantIssues
+import org.ossreviewtoolkit.model.Severity
 import org.ossreviewtoolkit.model.config.AnalyzerConfiguration
 import org.ossreviewtoolkit.model.toYaml
 import org.ossreviewtoolkit.utils.common.div
 import org.ossreviewtoolkit.utils.test.getAssetFile
 import org.ossreviewtoolkit.utils.test.matchExpectedResult
 
+private object RequiresExternalTool : Tag()
+
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Please instead use `@Tags("RequiresExternalTool")` for the whole spec.

File: plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt [hunk 6]
```diff
@@ -87,18 +96,54 @@ class GleamFunTest : StringSpec({
...
+                definitionFile,
+                resolveScopes = true,
+                allowDynamicVersions = true
+            )
+        } finally {
+            projectDir.resolve("manifest.toml").delete()
+            projectDir.resolve("build").deleteRecursively()
+        }
+
+        result.issues.filter { it.severity == Severity.ERROR }.shouldBeEmpty()
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Prefer the infix notation: `should beEmpty()`

Comment (sschuberth) [reply plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Similar below.

File: plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt [hunk 7]
```diff
@@ -87,18 +96,54 @@ class GleamFunTest : StringSpec({
...
-            allowDynamicVersions = true
-        )
+        val result = try {
+            createGleam().resolveSingleProject(
+                definitionFile,
+                resolveScopes = true,
+                allowDynamicVersions = true
+            )
+        } finally {
+            projectDir.resolve("manifest.toml").delete()
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: To avoid this, consider copying the `gleam.toml` test asset to a directory created by Kotest's `tempdir()`, which are cleaned up automatically.

Comment (sschuberth) [reply plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Similar below.

File: plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt [hunk 8]
```diff
@@ -87,18 +96,54 @@ class GleamFunTest : StringSpec({
...
+            projectDir.resolve("build").deleteRecursively()
+        }
+
+        result.issues.size shouldBe 1
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Prefer: `should haveSize(1)`

File: plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt [hunk 9]
```diff
@@ -87,18 +96,54 @@ class GleamFunTest : StringSpec({
...
+        result.issues.first().run {
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Or actually, if you use the single issue, prefer `.shouldBeSingleton {`.

File: plugins/package-managers/gleam/src/main/kotlin/Gleam.kt (hunk 2 above)
Comment (sschuberth) [reply plugins/package-managers/gleam/src/main/kotlin/Gleam.kt]: Correct, we leave that check to the `ort requirements` sub-command.

File: plugins/package-managers/gleam/src/main/kotlin/Gleam.kt [hunk 10]
```diff
@@ -159,6 +149,47 @@ class Gleam internal constructor(
...
+                    parseManifest(manifestFile)
+                } else {
+                    issues += Issue(
+                        source = projectType,
+                        message = "No lockfile found and running 'gleam deps download' failed with exit code " +
+                            "${process.exitValue}. No dependencies were resolved.\n${process.stderr}"
+                    )
+                    GleamManifest.EMPTY
+                }
```
Comment (fviernau) [inline plugins/package-managers/gleam/src/main/kotlin/Gleam.kt]: For the else case, consider if calling `requireSuccess()` on `process` would be more consistent with other managers. (e.g. `if / else` would be eliminated.)

**Comment by sschuberth** [comment]
> I used this action before: https://github.com/BRAINSia/free-disk-space It is able to clean up ~52Gb (+ 12Gb from the current cleanup command)

It seems this is a fork of an unmaintained project. And there are many forks of the original project. Is there a good reason to choose this fork specifically?

**Comment by mnonnenmacher** [comment]
> > Should I add a commit for it or do you have a better idea?
> 
> While I would like @mnonnenmacher to comment on that, I'm in favor of giving it a try, esp. if it also helps us to reduce custom code.

I'm not in favor of depending on a barely adopted action where we have no idea if it will be kept up-to-date when the GitHub runners change. I'd prefer to check what this action is deleting that we are not deleting and then adapt our own code accordingly to stay in control.

@maennchen How much is this PR increasing the size of the Docker image? Could you add that information to the commit message?

**Comment by maennchen** [comment]
@mnonnenmacher The Gleam binary itself is small (~24 mb), the problem is the `go install` for cosign that takes over 3GB but is only needed for verification. I'll try installing cosign from the releases (missed that they provided) and cleanup in the same step. That way this should be a lot smaller.

**Comment by mnonnenmacher** [comment]
@maennchen FYI, CloudFlare is causing lots of 403 errors today when accessing Maven Central via GitHub Actions: https://status.maven.org/
I have retriggered the failed tests hoping that it works now.

File: plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt [hunk 11]
```diff
@@ -87,18 +97,37 @@ class GleamFunTest : StringSpec({
...
-        val definitionFile = getAssetFile("projects/synthetic/no-lockfile/gleam.toml")
-        val expectedResultFile =
-            getAssetFile("projects/synthetic/no-lockfile-expected-output-allow-dynamic-versions.yml")
+    "Resolve dependencies for a project without a lockfile if 'allowDynamicVersions' is enabled" {
+        val projectDir = tempdir()
+        getAssetFile("projects/synthetic/no-lockfile").copyRecursively(projectDir)
 
         val result = createGleam().resolveSingleProject(
-            definitionFile,
+            projectDir.resolve("gleam.toml"),
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Nit: Instead of `resolve()`, our custom `/` operator could be used.

File: plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt [hunk 12]
```diff
@@ -87,18 +97,37 @@ class GleamFunTest : StringSpec({
...
+        result.packages shouldNot beEmpty()
+        result.packages.map { it.id.name } shouldContain "gleam_stdlib"
+    }
+
+    "Resolve dependencies fails with error details for broken gleam.toml" {
+        val projectDir = tempdir()
+        getAssetFile("projects/synthetic/no-lockfile-broken").copyRecursively(projectDir)
+
+        val result = createGleam().resolveSingleProject(
+            projectDir.resolve("gleam.toml"),
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/funTest/kotlin/GleamFunTest.kt]: Nit: Instead of `resolve()`, our custom `/` operator could be used.

File: plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt [hunk 13]
```diff
@@ -0,0 +1,205 @@
...
+
+    return "cpe:2.3:a:$owner:$repo:$version:*:*:*:*:*:*:*"
+}
+
+/**
+ * Validate that a local path dependency stays within the analysis root directory.
+ * Returns true if the resolved path is within the analysis root.
+ */
+private fun isValidLocalPath(analysisRoot: File, workingDir: File, path: String): Boolean {
+    val resolvedPath = workingDir.resolve(path).canonicalFile
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt]: Nit: Instead of `resolve()`, our custom `/` operator could be used.

But for readability, I'd then rewrite this slightly to

```kotlin
val resolvedPath = workingDir / path
return resolvedPath.canonicalFile.startsWith(analysisRoot.canonicalFile)
```

File: plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt [hunk 14]
```diff
@@ -0,0 +1,205 @@
...
+            binaryArtifact = RemoteArtifact.EMPTY,
+            sourceArtifact = pkg.outerChecksum?.let {
+                RemoteArtifact(
+                    url = "https://repo.hex.pm/tarballs/${pkg.name}-${pkg.version}.tar",
+                    hash = Hash(it, HashAlgorithm.SHA256)
+                )
+            } ?: RemoteArtifact.EMPTY,
+            vcs = vcs,
+            vcsProcessed = vcs.normalize(),
+            sourceCodeOrigins = listOf(SourceCodeOrigin.ARTIFACT, SourceCodeOrigin.VCS)
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt:94]: Why does this not use the default of `null`?

File: plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt [hunk 15]
```diff
@@ -0,0 +1,205 @@
...
+            homepageUrl = hexInfo?.meta?.links?.get("Website") ?: "https://hex.pm/packages/${pkg.name}",
+            binaryArtifact = RemoteArtifact.EMPTY,
+            sourceArtifact = pkg.outerChecksum?.let {
+                RemoteArtifact(
+                    url = "https://repo.hex.pm/tarballs/${pkg.name}-${pkg.version}.tar",
+                    hash = Hash(it, HashAlgorithm.SHA256)
+                )
+            } ?: RemoteArtifact.EMPTY,
+            vcs = vcs,
+            vcsProcessed = vcs.normalize(),
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt]: This is the default and can be omitted.

File: plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt [hunk 16]
```diff
@@ -0,0 +1,205 @@
...
+            id = toIdentifier(),
+            cpe = generateCpe(pkg.repo.orEmpty(), pkg.version),
+            authors = emptySet(),
+            declaredLicenses = emptySet(),
+            description = "",
+            homepageUrl = toHomepageUrl(pkg.repo.orEmpty()),
+            binaryArtifact = RemoteArtifact.EMPTY,
+            sourceArtifact = RemoteArtifact.EMPTY,
+            vcs = vcs,
+            vcsProcessed = vcs.normalize(),
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt]: This is the default and can be omitted.

File: plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt [hunk 17]
```diff
@@ -0,0 +1,205 @@
...
+        val basePackage = Package(
+            id = toIdentifier(),
+            authors = emptySet(),
+            declaredLicenses = emptySet(),
+            description = "",
+            homepageUrl = context.project.homepageUrl,
+            binaryArtifact = RemoteArtifact.EMPTY,
+            sourceArtifact = RemoteArtifact.EMPTY,
+            vcs = VcsInfo.EMPTY,
+            vcsProcessed = VcsInfo.EMPTY,
```
Comment (sschuberth) [inline plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt]: This is the default and can be omitted.

File: plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt (hunk 14 above)
Comment (maennchen) [reply plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt:94]: Is this equivalent to null? When I wrote this part (earlier PR), I wanted to make it explicit to use the Artifact with higher priority than the VCS.

Comment (maennchen) [reply plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt:94]: It looks like this is needed to not flip the priority:

https://github.com/oss-review-toolkit/ort/blob/6fe0379885f747c46bce7386a2b57d330817be28/model/src/main/kotlin/config/DownloaderConfiguration.kt#L51

Comment (sschuberth) [reply plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt:94]: > I wanted to make it explicit to use the Artifact with higher priority than the VCS.

Ok, I just wanted to double-check on that. So this deliberately does not adhere to what's (possibly) globally configured.

**Comment by sschuberth** [comment]
This is LGTM now. @fviernau, do you also want to re-review regarding your requested changes?

File: plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt (hunk 14 above)
Comment (maennchen) [reply plugins/package-managers/gleam/src/main/kotlin/ManifestPackageInfo.kt:94]: Correct

**Comment by sschuberth** [comment]
> This is LGTM now. @fviernau, do you also want to re-review regarding your requested changes?

Let's get it merged for today's release and do any eventual improvements as follow-ups, as last time.

**Comment by sschuberth** [comment]
Merging despite the unrelated test failure(s).

**Review by sschuberth — APPROVED** [review]
