### PR TITLE
fix(PythonInspector): Improve the way project names are derived

### LINKED ISSUE #6524: Unable to determine a project name for Python project
I have installed the `python-inspector` package and added it to the PATH, it resolved most errors, however there is still one error that popped up

```
11:38:27.784 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.PackageManager - Resolving PIP dependencies for path 'setup.py' failed with: IllegalArgumentException: Unable to determine a project name for '/home/complab304pc30/Documents/django/setup.py'.
```

_Originally posted by @HardikRa in https://github.com/oss-review-toolkit/ort/issues/5159#issuecomment-1437912865_

### PR DESCRIPTION
**Pull request by sschuberth**
Actually use `requirementsName` if there is no `setupName`, improve the project name if there are both, and always use the relative path to the analyzer as a fallback.

Fixes #6524.

> **Note**
> This is a **breaking change** under some circumstances Python projects my get assigned different ids than before, which might affect existing curations.

### CODE REVIEW

File: analyzer/src/main/kotlin/managers/utils/PythonInspector.kt [hunk 1]
```diff
@@ -235,19 +235,17 @@ private fun PythonInspector.Result.resolveIdentifier(
...
     val hasRequirementsName = requirementsName.isNotEmpty()
 
     val projectName = when {
         hasSetupName && !hasRequirementsName -> setupName
-        // In case of only a requirements file without further metadata, use the relative path to the analyzer
-        // root as a unique project name.
-        !hasSetupName && hasRequirementsName -> PackageManager.getFallbackProjectName(analysisRoot, definitionFile)
-        hasSetupName && hasRequirementsName -> "$setupName-requirements$requirementsSuffix"
-        else -> throw IllegalArgumentException("Unable to determine a project name for '$definitionFile'.")
+        !hasSetupName && hasRequirementsName -> requirementsName
```
Comment (MarcelBochtler) [inline analyzer/src/main/kotlin/managers/utils/PythonInspector.kt:246]: As it was previously an explicit decision to _not_ use the `requirementsName` can you explain why that has to be changed?

Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/utils/PythonInspector.kt:246]: Was it? I do not recall that decision, nor did I read anything in the code about it. Do you remember any details? If it's about a potential project name / id clash, why should a `requirementsName` clash be more likely than a `setupName`?

Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/managers/utils/PythonInspector.kt:246]: > Do you remember any details?

No. But the code looks like it was an explicit choice by the author.

But I'm ok with the change as-is.

**Review by MarcelBochtler — DISMISSED** [review]

**Comment by sschuberth** [comment]
> But I'm ok with the change as-is.

Thanks. To be on the safe side I'll wait for another approval from @mnonnenmacher or @fviernau.

File: analyzer/src/main/kotlin/managers/utils/PythonInspector.kt (hunk 1 above)
Comment (mnonnenmacher) [reply analyzer/src/main/kotlin/managers/utils/PythonInspector.kt:246]: > If it's about a potential project name / id clash, why should a requirementsName clash be more likely than a setupName?

Because `setupName` comes from the metadata in `setup.py` and can be set to a meaningful value, but `requirementsName` ist just the name of the file. If a repository contains two directories with the same name and a requirements.txt, would this now lead to a name clash? For example, if there are multiple `test/requirements.txt`?

Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/utils/PythonInspector.kt:246]: Thanks for pointing me at that commit. Its message reads as if the problem was mostly with `requirements.txt` files in the project root, and the project root directly might not be very unique (e.g. in CI pipelines that run ORT on a temporary workspace).

So maybe just special-case `definitionFile.parentFile != analysisRoot`?

Comment (mnonnenmacher) [reply analyzer/src/main/kotlin/managers/utils/PythonInspector.kt:250]: The mentioning of the "project's base directory" in the commit message seems to be misleading, if it was only about a file in the root dir it would not cause a name conflict within the same analyzer run. Likely the issue was about requirements.txt files in multiple directories with the same name.
I think it would be a good idea to split the changes of the `else` and the `!hasSetupName && hasRequirementsName` branches into two separate commits, then we could easily revert one of them in case it leads to issues with many duplicate identifiers.

**Review by mnonnenmacher — APPROVED** [review]
