### PR TITLE
fix(gradle-inspector): Optimize memory by caching dependency subtrees

### LINKED ISSUE #9220: Gradle Inspector terminates with OutOfMemory
### Describe the bug

Since Ort versions 32.x and later, Gradle Inspector start to explode with Out of Memory crash.
Same unmodified code that worked with Ort 30.0.0.

### To Reproduce

Download [Demo Test tarball](https://dev.heliocastro.info/demo.tar.xz) and run `ort analyze -i . -o output`

### Expected behavior

Analyzer file to be created

### Console / log output

Add console and / or log output that shows the error and additional context.
No screenshots of plain text please, to keep text searchable.

```
 ______________________________                                                            
/        \_______   \__    ___/       The OSS Review Toolkit, version 33.1.0,              
|    |   | |       _/ |    |          built with JDK 11.0.24+8, running under Java 17.0.12.
|    |   | |    |   \ |    |          Executing 'analyze' as '***' on Mac OS X         
\________/ |____|___/ |____|          with 10 CPUs and a maximum of 8192 MiB of memory.    
                                                                                           
Environment variables:                                                                    
ORT_CONFIG_DIR = /Users/*****/data/ort-config                                           
ORT_DATA_DIR = /Users/****/.ort                                                        
HOME = /Users/******                                                                     
SHELL = /bin/zsh                                                                          
TERM = xterm-kitty                                                                        
http_proxy = *****
https_proxy = *****
JAVA_HOME = /opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home                
ANDROID_HOME = /Users/*****/.local/toolchains/android/android-sdk                       
                                                                                          
Looking for ORT configuration in the following file:
        /Users/*****/data/ort/config_host.yml

Looking for analyzer-specific configuration in the following files and directories:
        /Users/*****/code/testcode/.ort.yml
        /Users/****/data/ort-config/resolutions.yml
The following 1 package manager(s) are enabled:
        GradleInspector
The following 3 package curation provider(s) are enabled:
        RepositoryConfiguration, DefaultFile, DefaultDir
Analyzing project path:
        /Users/****/code/testcode
12:34:45.884 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/Users/****/code/testcode/.gradle' as it is hard-coded to be ignored.
12:34:45.908 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/Users/****/code/testcode/.git' as it is hard-coded to be ignored.
12:34:45.909 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/Users/****/code/testcode/src/test/resources' as it is hard-coded to be ignored.
12:34:45.911 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/Users/****/code/testcode/src/main/resources' as it is hard-coded to be ignored.
Found 1 GradleInspector definition file(s) at:
        build.gradle
Found in total 1 definition file(s) from the following 1 package manager(s):
        GradleInspector
12:34:45.941 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManagerRunner - Starting GradleInspector analysis.
12:34:45.944 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Using GradleInspector to resolve dependencies for path 'build.gradle'...
12:34:46.347 [DefaultDispatcher-worker-1] INFO  org.gradle.tooling.GradleConnector - The project at '/Users/DHXBWM7/code/cariad/user-push-service' uses Gradle version 8.5.0.
12:34:52.551 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.ort.OrtProxySelector - Proxy selector was successfully installed.
12:34:52.559 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.ort.OrtAuthenticator - Authenticator was successfully installed.
12:34:52.747 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.PackageManager - GradleInspector failed to resolve dependencies for path 'build.gradle': BuildException: Could not fetch model of type 'OrtDependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-8.5-bin.zip'.
Caused by: LocationAwareException: Java heap space
    Caused by: OutOfMemoryError: Java heap space
12:34:52.749 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - GradleInspector resolved dependencies for path 'build.gradle' in 6.802362833s.
12:34:52.752 [DefaultDispatcher-worker-1] INFO  kotlinx.coroutines.CoroutineScope - Finished GradleInspector analysis.
12:34:52.787 [main] INFO  org.ossreviewtoolkit.utils.config.ConfigurationResolver - Getting 0 package curation(s) from provider 'RepositoryConfiguration' took 117.834us.
12:34:52.787 [main] INFO  org.ossreviewtoolkit.utils.config.ConfigurationResolver - Getting 0 package curation(s) from provider 'DefaultFile' took 1.167us.
12:34:52.788 [main] INFO  org.ossreviewtoolkit.utils.config.ConfigurationResolver - Getting 0 package curation(s) from provider 'DefaultDir' took 457.25us.
Wrote analyzer result to '/Users/****/code/testcode/output/analyzer-result.yml' (0,00 MiB) in 306.559417ms.
The analysis took 6.859496s.
Found 1 project(s) and 0 package(s) in total (not counting excluded ones).
Applied 0 curation(s) from 0 of 3 provider(s).
Resolved issues: 0 errors, 0 warnings, 0 hints.
Unresolved issues: 1 error, 0 warnings, 0 hints.
There is 1 unresolved issue with a severity equal to or greater than the ERROR threshold.
```

*Or* manually specify:

* ORT version: 33.1.0
* Java version: 17.0.12
* OS: MacOS

### Additional context

Tried with Java 21, and with extended 16Gb memory option for both JAVA_OPTS and GRADLE_OPTS

### PR DESCRIPTION
**Pull request by wkl3nk**
In large projects with many dependencies, the GradleInspector plugin often runs out of Java heap space, even when allocated 2 GB. This is due to all dependencies being stored in a large tree structure, which consumes a significant amount of memory.

This change introduces a caching mechanism for dependency subtrees of components. Instead of traversing and storing the entire dependency tree every time, the cache is checked first. If a subtree for a component already exists in the cache, a reference to this cached data is used, reducing memory consumption significantly.

Fixes #9220.

### CODE REVIEW

**Comment by heliocastro** [comment]
I just checked and validated against the reproducible targets, including the demo on #9220. This patch was able to generate the output properly not showing the OutofMem behavior.
It may be a temporary solution or a definitive one; I would recommend merging it.

**Review by heliocastro — APPROVED** [review]
Looks good after the tests against the test repositories.

**Review by oheger-bosch — DISMISSED** [review]
Great fix, thank you very much @wkl3nk

File: plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt [hunk 1]
```diff
@@ -205,7 +206,10 @@ internal class OrtModelBuilder : ToolingModelBuilder {
                                 warnings += message
                             }
 
-                            val dependencies = selectedComponent.dependencies.toOrtDependencies(poms, visited + id)
+                            // Check if we have scanned the dependencies of this subtree before, and if so, reuse them.
+                            val dependencies = globalDependencySubtrees[id.displayName]
+                                ?: selectedComponent.dependencies.toOrtDependencies(poms, visited + id)
+                                    .also { globalDependencySubtrees[id.displayName] = it }
```
Comment (sschuberth) [inline plugins/package-managers/gradle-plugin/src/main/kotlin/OrtModelBuilder.kt:212]: Please use `getOrPut()` instead:

    val dependencies = globalDependencySubtrees.getOrPut(id.displayName) {
        selectedComponent.dependencies.toOrtDependencies(poms, visited + id)
    }

**Review by sschuberth — CHANGES_REQUESTED** [review]

**Comment by sschuberth** [comment]
> This is due to all dependencies being stored in a large tree structure, which consumes a significant amount of memory.

BTW, this is due to *GradleInspector* using [the same `GradleModel` as the "legacy" *Gradle* analyzer](https://github.com/oss-review-toolkit/ort/blob/main/plugins/package-managers/gradle-model/src/main/kotlin/GradleModel.kt) for easier comparison. That model has several problems, one is the mentioned memory usage, the other is that dependency cycles cannot really be modeled as you run into a chick-and-egg problem with package references (you cannot refer to a dependency before it was created, but in order to create it you need to know its dependencies).

Both problems could also be solved via https://github.com/oss-review-toolkit/ort/issues/8377 which uses textual IDs instead of objects for referring to dependencies. This approach would be closer to the `DependencyGraph` model anyway... it's indeed awkward that we first use a far less efficient (temporary) memory model in `GradleModel`, just to convert it to the more efficient `DependencyGraph` later, instead of using the more efficient model to begin with.

**Review by sschuberth — APPROVED** [review]
