### PR TITLE
fix(spdx): Convert hash value to lowercase when creating SpdxChecksum

### LINKED ISSUE #10659: SPDX report generation fails when encountering invalid checksums
### Describe the bug

When generating an SPDX SBOM, the report generation fails completely if a checksum validation error occurs in `toSpdxChecksum()`. This happens because exceptions thrown during SpdxChecksum initialization aren't caught, causing the entire report generation to be interrupted.

### To Reproduce

1. Have a package in your dependency graph with an invalid checksum (e.g., with uppercase hexadecimal symbols)
2. Run `ort report -i ... -o ... -f SpdxDocument`
3. See report generation fail with a validation error

### Expected behavior

The SPDX report generation should handle invalid checksums gracefully and log a warning.

### Console / log output

```
 ______________________________                                                
/        \_______   \__    ___/ The OSS Review Toolkit, version 64.0.0,        
|    |   | |       _/ |    |    built with JDK 21.0.7+6-LTS, running under Java
|    |   | |    |   \ |    |    Executing 'report' as 'ort' on Linux           
\________/ |____|___/ |____|    with 4 CPUs and a maximum of 5120 MiB of memory
                                                                               
Environment variables:                                                        
ORT_DATA_DIR = /home/ort/.ort                                                 
HOME = /home/ort                                                              
JAVA_HOME = /opt/java/openjdk                                                 
ANDROID_HOME = /opt/android-sdk                                               
                                                                              
Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml

Generating 'CycloneDX' report(s) in thread 'DefaultDispatcher-worker-2'...
Generating 'SpdxDocument' report(s) in thread 'DefaultDispatcher-worker-3'...
Generating 'WebApp' report(s) in thread 'DefaultDispatcher-worker-4'...
Exception in thread "main" java.lang.IllegalArgumentException: The checksum value must only contain lower case hexadecimal symbols.
	at org.ossreviewtoolkit.utils.spdxdocument.model.SpdxChecksum.validate(SpdxChecksum.kt:69)
	at org.ossreviewtoolkit.utils.spdxdocument.model.SpdxChecksum.<init>(SpdxChecksum.kt:62)
	at org.ossreviewtoolkit.plugins.reporters.spdx.ExtensionsKt.toSpdxChecksum(Extensions.kt:73)
	at org.ossreviewtoolkit.plugins.reporters.spdx.ExtensionsKt.toSpdxPackage(Extensions.kt:166)
	at org.ossreviewtoolkit.plugins.reporters.spdx.SpdxDocumentModelMapper.map(SpdxDocumentModelMapper.kt:142)
	at org.ossreviewtoolkit.plugins.reporters.spdx.SpdxDocumentReporter.generateReport(SpdxDocumentReporter.kt:118)
	at org.ossreviewtoolkit.plugins.commands.reporter.ReportCommand$run$reportDurationMap$1$1$1$1.invokeSuspend(ReportCommand.kt:303)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:586)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:829)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:717)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:704)
```

### Environment

```
 ______________________________
/        \_______   \__    ___/ The OSS Review Toolkit, version 64.0.0,
|    |   | |       _/ |    |    built with JDK 21.0.7+6-LTS, running under Java
|    |   | |    |   \ |    |    Executing 'requirements' as 'ort' on Linux
\________/ |____|___/ |____|    with 16 CPUs and a maximum of 4000 MiB of memor

Environment variables:
HOME = /home/ort
JAVA_HOME = /opt/java/openjdk
ANDROID_HOME = /opt/android-sdk

Looking for ORT configuration in the following file:
        /home/ort/.ort/config/config.yml

Scanners:
        - Askalono: Requires 'askalono' in no specific version. Tool not found.
        - BoyterLc: Requires 'lc' in no specific version. Tool not found.
        - Licensee: Requires 'licensee' in no specific version. Tool not found.
        * ScanCode: Requires 'scancode' in version >=30.0.0. Found version 32.4.1.

PackageManagers:
        + Bazel: Requires 'bazel' in version >=7.0.0. Could not determine the version.
        * Bower: Requires 'bower' in version >=1.8.8. Found version 1.8.14.
        + Buildozer: Requires 'buildozer' in no specific version. Found version redacted.
        * Cargo: Requires 'cargo' in no specific version. Found version 1.87.0.
        * CocoaPods: Requires 'pod' in version >=1.11.0. Found version 1.16.2.
        * Composer: Requires 'composer' in version >=1.5.0. Found version 2.8.10.
        * Go: Requires 'go' in version >=1.21.1. Found version 1.24.5.
        * Npm: Requires 'npm' in version >=6.0.0 and <11.0.0. Found version 10.9.2.
        + NuGetInspector: Requires 'nuget-inspector' in no specific version. Could not determine the version.
        * Pipenv: Requires 'pipenv' in version >=2018.10.9. Found version 2023.12.1.
        + Pnpm: Requires 'pnpm' in version >=5.0.0 and <11.0.0. Could not determine the version.
        * Poetry: Requires 'poetry' in no specific version. Found version 2.1.3.
        * PythonInspector: Requires 'python-inspector' in version >=0.9.2. Found version 0.14.0.
        * Sbt: Requires 'sbt' in version >=1.3.3. Found version 1.10.0.
        * Stack: Requires 'stack' in version >=2.1.1. Found version 3.7.1.
        * Swift: Requires 'swift' in no specific version. Found version 6.0.3.
        + Yarn: Requires 'yarn' in version >=1.3.0 and <1.23.0. Could not determine the version.

Other tools:
        * Conan: Requires 'conan' in version >=1.44.0 and <3.0.0. Found version 1.66.0.
        * Pub: Requires 'dart' in version >=2.10.0. Found version 2.18.4.

VersionControlSystems:
        * Git: Requires 'git' in version >=2.29.0. Found version 2.34.1.
        * GitRepo: Requires 'repo' in no specific version. Found version 2.54 (launcher).
        * Mercurial: Requires 'hg' in no specific version. Found version 7.0.3.

Prefix legend:
        - The tool was not found in the PATH environment.
        + The tool was found in the PATH environment, but not in the required version.
        * The tool was found in the PATH environment in the required version.

ScanCode license texts found in '/opt/scancode-license-data'.

Not all tools requirements were satisfied:
        ! Some tools were not found in their required versions.
        ! For some tools the version could not be determined.
```

### PR DESCRIPTION
**Pull request by luispflamminger**
Wraps `SpdxChecksum` creation in `runCatching` to handle validation failures, preventing failure of SPDX report generation when checksum validation fails.

This PR should fix #10659. More context is provided there.

### CODE REVIEW

**Comment by luispflamminger** [comment]
I'm still having some issues with failing tests.

Some tests in `org.ossreviewtoolkit.plugins.reporters.spdx.SpdxDocumentReporterFunTest` are failing because `hasExtractedLicensingInfos` is missing.

```
io.kotest.assertions.AssertionFailedError: expected:<[Addition at line 12]   "comment" : "some document comment",
  "hasExtractedLicensingInfos" : [ {
    "extractedText" : "ASMUS License\n\nDisclaimer and legal rights\n---------------------------\n\nThis file contains bugs. All representations to the contrary are void.\n\nSource code in this file and the accompanying headers and included \nfiles may be distributed free of charge by anyone, as long as full \ncredit is given and any and all liabilities are assumed by the \nrecipient.",
    "licenseId" : "LicenseRef-scancode-asmus"
  }, {
    "extractedText" : "To anyone who acknowledges that the file \"sRGB Color Space Profile.icm\" \nis provided \"AS IS\" WITH NO EXPRESS OR IMPLIED WARRANTY:\npermission to use, copy and distribute this file for any purpose is hereby \ngranted without fee, provided that the file is not changed including the HP \ncopyright notice tag, and that the name of Hewlett-Packard Company not be \nused in advertising or publicity pertaining to distribution of the software \nwithout specific, written prior permission. Hewlett-Packard Company makes \nno representations about the suitability of this software for any purpose.",
    "licenseId" : "LicenseRef-scancode-srgb"
  } ],
  "documentNamespace" : "spdx://4b2a09d9-f132-4158-acd2-5da897fd4aa1",
  "documentDescribes" : [ "SPDXRef-Project-Maven-proj1-grp-proj1-0.0.1" ],
  "packages" : [ {
    "SPDXID" : "SPDXRef-Project-Maven-proj1-grp-proj1-0.0.1",> but was:<[Addition at line 12]   "comment" : "some document comment",
  "documentNamespace" : "spdx://4b2a09d9-f132-4158-acd2-5da897fd4aa1",
  "documentDescribes" : [ "SPDXRef-Project-Maven-proj1-grp-proj1-0.0.1" ],
  "packages" : [ {
    "SPDXID" : "SPDXRef-Project-Maven-proj1-grp-proj1-0.0.1",
    "copyrightText" : "NONE",
    "downloadLocation" : "https://github.com/path/proj1-repo.git",
    "filesAnalyzed" : false,
    "homepage" : "https://example.com/proj1/homepage",
    "licenseConcluded" : "NOASSERTION",
    "licenseDeclared" : "MIT",
    "name" : "proj1",
    "versionInfo" : "0.0.1"
  }, {
    "SPDXID" : "SPDXRef-Package-Go-gopkg.in.yaml.v3-3.0.1",
    "copyrightText" : "Copyright (c) 2006-2010 Kirill Simonov",
    "downloadLocation" : "NONE",
    "externalRefs" : [ {
      "referenceCategory" : "PACKAGE_MANAGER",>
```

I'd appreciate any input on that.

**Comment by sschuberth** [comment]
> Some tests in `org.ossreviewtoolkit.plugins.reporters.spdx.SpdxDocumentReporterFunTest` are failing because `hasExtractedLicensingInfos` is missing.

IIRC that test will fail unless you have ScanCode installed, whose licenses are used here.

File: plugins/reporters/spdx/src/main/kotlin/Extensions.kt [hunk 1]
```diff
@@ -70,10 +70,14 @@ private fun Hash.toSpdxChecksum(): SpdxChecksum? =
...
         .find { it.name in algorithm.aliases }
         ?.let {
-            SpdxChecksum(
-                algorithm = it,
-                checksumValue = value
-            )
+            runCatching {
+                SpdxChecksum(
+                    algorithm = it,
+                    checksumValue = value
```
Comment (sschuberth) [inline plugins/reporters/spdx/src/main/kotlin/Extensions.kt]: IMO we should simply call `value.lowercase()` here instead. Exceptions should probably be caught on a higher level anyway.

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: plugins/reporters/spdx/src/main/kotlin/Extensions.kt (hunk 1 above)
Comment (luispflamminger) [reply plugins/reporters/spdx/src/main/kotlin/Extensions.kt]: Of course, that's a much better solution. I pushed a new commit.

**Comment by sschuberth** [comment]
> Converts the hash value to lowercase before instantiating SpdxChecksum
to prevent validation errors.

A wording nit: Like in the commit message title, please use imperative mood and say "Convert" instead of "Converts".

Also please add `Fixes #10659.` as a final paragraph to your commit message to auto-close your issue upon merge.

**Review by sschuberth — APPROVED** [review]

**Comment by sschuberth** [comment]
Merging despite the unrelated test failure(s).

**Comment by sschuberth** [comment]
Thanks for the contribution, @luispflamminger!

**Comment by luispflamminger** [comment]
Thank you for the quick feedback and merge!
