### PR TITLE
fix(model): Add special handling for licenses from Maven source artifacts

### LINKED ISSUE #10607: Archived license files not included in (all) reports when using the `ARTIFACT` source code origin
### Describe the bug

The license files contained in the source artifacts, found by the use of a custom pattern, are not included in the reported notice even though they are found by the archiver during the scan. Not just the plain text, but also PDF and HTML notices.

1. Provide custom configuration of `licenseFilePatterns`, for e.g. include `**/LICENSE*`
2. Run a scan on the repository that contains dependencies with source artifacts that include LICENSE files, in META-INF for e.g. - default scan already has archiver enabled
3. Run a report on the scan result
4. Check notice file - it doesn't include the file license info

### Expected behavior

File licenses found by the archiver should be included in the final notice.

### Console/log output

During scanning:

```
DEBUG org.ossreviewtoolkit.model.utils.FileArchiver - Adding 'META-INF/LICENSE' to archive.
```
I see that the LICENSE was found and included.

During reporting:

```
INFO  org.ossreviewtoolkit.model.utils.FileArchiver - Unarchived data for ArtifactProvenance(sourceArtifact=RemoteArtifact(url=https://repo.maven.apache.org/maven2/org/apache/tika/tika-core/3.2.0/tika-core-3.2.0-sources.jar, hash=Hash(value=328e6b6cbc9be6d5b31e38a34a3a90f9981b280a, algorithm=SHA-1))) to '/tmp/ort-LicenseInfoResolver-archive15339033700059155317' in 4.312064ms.
```
I can see the unarchiving happening, but no files getting picked up.

### Environment

* ORT version: ort-minimal:61.0.0
* Java version: 21
* OS: linux/amd64 (Docker)

`config.yml`:

```
ort:
  forceOverwrite: true
  licenseFilePatterns:
    licenseFilenames: [  "copying*",
                         "COPYING*",
                         "copyright",
                         "licence*",
                         "license*",
                         "*.licence",
                         "*.license",
                         "**/LICENCE*",
                         "**/LICENSE*",
                         "unlicence",
                         "unlicense"]
    patentFilenames: [ 'patents' ]
    otherLicenseFilenames: [ 'readme*' ]
  analyzer:
    skipExcluded: true
    enabled_package_managers: [ GradleInspector ]
  downloader:
    sourceCodeOrigins: [ARTIFACT, VCS]
    skipExcluded: true
  scanner:
    archive:
      enabled: true
      fileStorage:
        localFileStorage:
          directory: ${user.home}/.ort/scanner/archive
          compression: false
    # We don't want excluded stuff to be scanned, e.g. dev or test dependencies
    skipExcluded: true
    storages:
      local:
        backend:
          localFileStorage:
            directory: ${user.home}/.ort/scanner/results
            compression: false
      
    storageReaders: [local]
    storageWriters: [local]
  reporter:
    config:
      SpdxDocument:
        options:
          output.file.formats: json
          file.information.enabled: true
      CycloneDx:
        options:
          output.file.formats: json
```

### Additional context

I am running in Docker, with a common volume for each ORT workflow step. I can see that the archiver archives the files in the right directory (during scan), as well as that unarchiving is happening during the report step. In the template, the `package.licenseFiles` is empty, and therefore no license is included in the final notice.

The Docker commands I am using:

Scan:
```
docker run \
  --rm \
  --name ort-scan-backend \
  --platform linux/amd64 \
  -v "$PWD"/:/workingdir \
  -v "$repo_abs_path":/repo \
  -v "$PWD"/.gitconfig:/home/ort/.gitconfig \
  -v ~/.netrc:/home/ort/.netrc:ro \
  -v ~/.gradle/gradle.properties:/home/ort/.gradle/gradle.properties:ro \
  -v "$ORT_DOCKER_VOLUME":/home/ort/.ort \
  -e ORT_CONFIG_DIR=/workingdir/config-backend \
  "$ORT_DOCKER_IMAGE" --debug scan \
  -i /repo/ort/results/backend/analyzer-result.yml \
  -o /repo/ort/results/backend \
  | tee scan-backend.log
```

Report:
```
docker run \
  --rm \
  --name ort-report-backend \
  --platform linux/amd64 \
  -v "$PWD"/:/workingdir \
  -v "$repo_abs_path":/repo \
  -v "$PWD"/.gitconfig:/home/ort/.gitconfig \
  -v ~/.netrc:/home/ort/.netrc:ro \
  -v ~/.gradle/gradle.properties:/home/ort/.gradle/gradle.properties:ro \
  -v "$ORT_DOCKER_VOLUME":/home/ort/.ort \
  -e ORT_CONFIG_DIR=/workingdir/config-backend \
  "$ORT_DOCKER_IMAGE" --debug report \
  -f PlainTextTemplate,StaticHtml,WebApp,PdfTemplate,HtmlTemplate,CycloneDx,SpdxDocument \
  -O PlainTextTemplate=template.path=/workingdir/config-general/notice.txt.ftl,/workingdir/config-general/notice.json.ftl \
  --license-classifications-file /workingdir/config-general/license-classifications.yml \
  -i /repo/ort/results/backend/evaluation-result.yml \
  -o /repo/ort/results/backend/reports/ \
  | tee report-backend.log
```

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #10607.

### CODE REVIEW

**Comment by sschuberth** [comment]
@sasa-boros-cp, please verify whether this fixes your issue.

File: model/src/main/kotlin/licenses/LicenseInfoResolver.kt [hunk 1]
```diff
@@ -259,7 +260,15 @@ class LicenseInfoResolver(
...
             archiveDir.deleteOnExit()
 
-            val directory = (provenance as? RepositoryProvenance)?.vcsInfo?.path.orEmpty()
+            val directory = when (provenance) {
+                // In case of a repository, match paths relative to the VCS path.
+                is RepositoryProvenance -> provenance.vcsInfo.path
+
+                // In case of a source artifact, match paths relative to the archive root or a type-specific directory.
+                // TODO: Check if more types need special handling.
+                is ArtifactProvenance -> if (id.type == "Maven") "META-INF" else ""
```
Comment (mnonnenmacher) [inline model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: If the license file patterns do not match the `META-INF` directory, the archive will not contain such files. I think in addition you also need to adapt the license file patterns to include license files in `META-INF`.

Comment (sasa-boros-cp) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: This is one solution to the problem of extracting the files from the already prepared archive. As was mine, which was extracting "all" from it. 

But, as @mnonnenmacher said, this will not bring them in the archive (during scan), hence my change in the `FileArchiverConfiguration`. We need another change to also find the licenses in `META-INF`, for Maven source artifacts.

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: Oh right, I was somehow thinking we were using Maven source artifacts directly as license archives here. But of course we don't.

Comment (sasa-boros-cp) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: Is there any way I can contribute to bringing this further? Maybe if we can agree on the approach, so that I can contribute the needed changes?   It became a priority for us from the usage perspective, and I would like to contribute. 👍

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: @sasa-boros-cp, I just pushed my latest changes I had locally. They're not fully ready yet as I had to stop working on it due to other priorities, but I believe that should be the direction to go.

Comment (sasa-boros-cp) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: @sschuberth looks good. Type-specific handling as discussed. If you agree, I will take it over, and then you can review the changes.

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: > If you agree, I will take it over, and then you can review the changes.

Please hold your breath, @sasa-boros-cp 😄 I'm working on this as we speak.

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: > I'm working on this as we speak.

Done. Please try the proposed solution on your side @sasa-boros-cp.

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: Does the 🚀 mean it works for you, @sasa-boros-cp? 😺

Comment (sasa-boros-cp) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: At first, it meant: wow, that was fast. Now, it means: great job, it works. 😸 Tested locally with your branch and all the files from the META-INF folder are correctly included when the `licenseFilenamePattern` for them exists.

Comment (sschuberth) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: Great, thanks for checking. Did you also verify that the texts stemming from files in `META-INF` do end up in a report format that supports verbatim license texts?

Comment (sasa-boros-cp) [reply model/src/main/kotlin/licenses/LicenseInfoResolver.kt]: Yes, they do end up in the final reports. I tested on the custom notice FTL template, they are found in `package.licenseFiles` and are present with the full file content.

File: model/src/main/kotlin/utils/FileArchiver.kt [hunk 2]
```diff
@@ -68,35 +71,40 @@ class FileArchiver(
...
     /**
-     * Archive all files in [directory] matching any of the configured patterns in the [storage].
+     * Archive the files matching [patterns] inside [rootDirectory] and put them to the [storage]. The archive is
+     * associated with the given [provenance] and [id].
      */
-    fun archive(directory: File, provenance: KnownProvenance) {
-        logger.info { "Archiving files matching ${matcher.patterns} from '$directory'..." }
+    fun archive(rootDirectory: File, provenance: KnownProvenance, id: Identifier) {
+        val subdirectory = getSubdirectoryForProvenance(provenance, id)
+        val directories = setOf(rootDirectory, File(rootDirectory, subdirectory))
```
Comment (mnonnenmacher) [inline model/src/main/kotlin/utils/FileArchiver.kt]: Maybe `rootDirectory / subdirectory`?

File: model/src/main/kotlin/utils/FileArchiver.kt [hunk 3]
```diff
@@ -129,3 +137,16 @@ class FileArchiver(
...
+ * Get the (potentially [id]-type specific) nested path directory for the given [provenance].
+ */
+fun getSubdirectoryForProvenance(provenance: KnownProvenance, id: Identifier): String =
+    when (provenance) {
+        // In case of a repository, match paths relative to the VCS path.
+        is RepositoryProvenance -> provenance.vcsInfo.path
+
+        // In case of a source artifact, match paths relative to the archive root or a type-specific directory.
+        // TODO: Check if more types need special handling.
+        is ArtifactProvenance -> if (id.type == "Maven") "META-INF" else ""
```
Comment (mnonnenmacher) [inline model/src/main/kotlin/utils/FileArchiver.kt]: I think a comment explaining why "META-INF" is used in case of Maven would be helpful.
This changes makes the `FileArchiver` specific to the purpose of archiving license files, maybe we should also rename it to `LicenseFileArchiver` to emphasize that, AFAIK we never used it for any other task anyway.

File: model/src/test/kotlin/utils/FileArchiverTest.kt [hunk 4]
```diff
@@ -192,11 +199,24 @@ class FileArchiverTest : StringSpec() {
...
+
+            val archiver = FileArchiver(LicenseFilePatterns.DEFAULT.allLicenseFilenames, storage)
+            archiver.archive(workingDir, ARTIFACT_PROVENANCE, Identifier("Maven:::"))
+            val result = archiver.unarchive(targetDir, ARTIFACT_PROVENANCE)
+
+            result shouldBe true
+            with(targetDir) {
+                shouldContainFileWithContent("META-INF/LICENSE")
+            }
+        }
```
Comment (mnonnenmacher) [inline model/src/test/kotlin/utils/FileArchiverTest.kt:233]: Because it seems that we have no other tests for source artifacts, please also add a test with another type to verify that the root dir is used in that case.

File: model/src/main/kotlin/utils/FileArchiver.kt (hunk 3 above)
Comment (sschuberth) [reply model/src/main/kotlin/utils/FileArchiver.kt]: > I think a comment explaining why "META-INF" is used in case of Maven would be helpful.

Done.

> This changes makes the `FileArchiver` specific to the purpose of archiving license files

Not strictly, I believe, as also other metadata files contained in "META-INF" could be archived by adjusting the pattern, and the logic only applies if a non-empty `Identifier` with a type is provided.

> maybe we should also rename it to `LicenseFileArchiver` to emphasize that

If doing so, I'd like to postpone that to a future change.

Comment (sasa-boros-cp) [reply model/src/main/kotlin/utils/FileArchiver.kt]: My two cents here. We also plan to use it to include the `NOTICE` files in the final notice as it is sometimes needed, i.e., with `Apache 2.0`.

Comment (sschuberth) [reply model/src/main/kotlin/utils/FileArchiver.kt]: Good point. As a follow-up, I could probably implement [this first step](https://github.com/oss-review-toolkit/ort/issues/6399#issuecomment-1404700070).

Comment (mnonnenmacher) [reply model/src/main/kotlin/utils/FileArchiver.kt]: >> This changes makes the FileArchiver specific to the purpose of archiving license files

>Not strictly, I believe, as also other metadata files contained in "META-INF" could be archived by adjusting the pattern, and the logic only applies if a non-empty Identifier with a type is provided.

Yes, but it's not general purpose anymore, because it cannot be used for archiving any files outside the META-INF directory.

>> maybe we should also rename it to LicenseFileArchiver to emphasize that

> If doing so, I'd like to postpone that to a future change.

Sure, that was more an idea, the change request was because of the other comments.

**Review by mnonnenmacher — APPROVED** [review]

File: model/src/main/kotlin/utils/FileArchiver.kt (hunk 3 above)
Comment (sschuberth) [reply model/src/main/kotlin/utils/FileArchiver.kt]: > it cannot be used for archiving any files outside the META-INF directory.

I believe it can. Just customize the file patterns (and use and empty `Identifier`).

**Comment by mnonnenmacher** [comment]
@sschuberth I just disabled auto-merge because I'm not sure if this should be considered a breaking change because it renders all existing file archives for Maven packages useless (it's now only looking for files in META-INF which were not included in the archives before this change). At least we should add to the release notes that this change requires manually deleting all existing file archives for Maven artifacts and otherwise works only for newly scanned packages.

**Comment by sschuberth** [comment]
> I just disabled auto-merge

Sorry, I saw this too late, and thought I forgot to enable it.

> At least we should add to the release notes that this change requires manually deleting all existing file archives for Maven artifacts and otherwise works only for newly scanned packages.

Good point. Esp. as I believe it was so that we keep empty archives to signal that *no* matching files were found, correct?

**Comment by mnonnenmacher** [comment]
> > At least we should add to the release notes that this change requires manually deleting all existing file archives for Maven artifacts and otherwise works only for newly scanned packages.
> 
> Good point. Esp. as I believe it was so that we keep empty archives to signal that _no_ matching files were found, correct?

I don't remember if this is the case but it would make sense. Also, without the empty archive it would download the source again on each run only to find out that there are no files to archive, so I hope it is implemented that way.

File: model/src/main/kotlin/utils/FileArchiver.kt (hunk 3 above)
Comment (sschuberth) [reply model/src/main/kotlin/utils/FileArchiver.kt]: > Good point. As a follow-up, I could probably implement [this first step](https://github.com/oss-review-toolkit/ort/issues/6399#issuecomment-1404700070).

See https://github.com/oss-review-toolkit/ort/pull/10893.
