### PR TITLE
ScanCode: Strip all spaces when parsing (non-)configuration options

### LINKED ISSUE #6102: Scanner: crashes with some commandline format
Hi,

With a yaml configuration, a commandLine with a space at the end makes the scanner failed.

Example :
If I wrote this in the config.yml
```
      ScanCode:
        commandLine: '--copyright --license --info --strip-root --timeout 300 '
```
I get a error like this: 
```
10:33:27.403 [main] INFO  org.ossreviewtoolkit.scanner.Scanner - Scan of RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/vigna/fastutil.git, revision=4f2b7e260410788c0244e7abde1d8f3a1409343c, path=), resolvedRevision=4f2b7e260410788c0244e7abde1d8f3a1409343c) with path scanner 'ScanCode' started.
10:33:27.405 [main] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running '/opt/python/shims/scancode --copyright --license --info --strip-root --timeout 300  --processes 3 /tmp/ort-DefaultProvenanceDownloader3508651820998550611 --json-pp /tmp/ort-ScanCode12874450254444799066/result.json' in '/home/ort'...
Exception in thread "main" java.io.FileNotFoundException: /tmp/ort-ScanCode12874450254444799066/result.json (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at com.fasterxml.jackson.core.TokenStreamFactory._fileInputStream(TokenStreamFactory.java:262)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1030)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:3157)
	at org.ossreviewtoolkit.model.FileFormatKt.readTree(FileFormat.kt:94)
	at org.ossreviewtoolkit.scanner.scanners.scancode.ScanCode.scanPath(ScanCode.kt:184)
	at org.ossreviewtoolkit.scanner.Scanner.scanPath(Scanner.kt:523)
	at org.ossreviewtoolkit.scanner.Scanner.runPathScanners(Scanner.kt:369)
	at org.ossreviewtoolkit.scanner.Scanner.scan(Scanner.kt:154)
	at org.ossreviewtoolkit.scanner.Scanner$scan$4.invokeSuspend(Scanner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runScanners(ScannerCommand.kt:228)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:155)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:83)
```

but if I wrote this : 
```
      ScanCode:
        commandLine: '--copyright --license --info --strip-root --timeout 300'
```
there is no problem :-) 

Maybe a trim when reading this config value can add robustness

### PR DESCRIPTION
**Pull request by sschuberth**
Leading / trailing or multiple consecutive inner spaces led to empty arguments which, when passed to ScanCode, cause weird behavior, like the result file not being written. Fix that stripping any / multiple spaces when splitting options.

Fixes #6102.

Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>

### CODE REVIEW

File: scanner/src/main/kotlin/scanners/scancode/ScanCode.kt [hunk 1]
```diff
@@ -114,11 +114,15 @@ class ScanCode internal constructor(
...
 
-    private val configurationOptions = scanCodeConfiguration["commandLine"]?.split(' ')
-        ?: DEFAULT_CONFIGURATION_OPTIONS
-    private val nonConfigurationOptions = scanCodeConfiguration["commandLineNonConfig"]?.split(' ')
-        ?: DEFAULT_NON_CONFIGURATION_OPTIONS
+    private val configurationOptions = scanCodeConfiguration["commandLine"]?.let { commandLine ->
+        nonSpaceRegex.findAll(commandLine).map { it.value }
+    } ?: DEFAULT_CONFIGURATION_OPTIONS
+
+    private val nonConfigurationOptions = scanCodeConfiguration["commandLineNonConfig"]?.let { commandLineNonConfig ->
```
Comment (oheger-bosch) [inline scanner/src/main/kotlin/scanners/scancode/ScanCode.kt:123]: Some redundancy could be avoided by moving the Regex processing to a function, maybe an extension function on the map of scanner options, such as
`fun Map<String, String>.commandLineOptions(key: String, defaultOptions: Sequence<String>): Sequence<String>`

**Review by oheger-bosch — COMMENTED** [review]
It would be good to have tests to make sure that various variants of command line options are handled correctly by this approach.

File: scanner/src/main/kotlin/scanners/scancode/ScanCode.kt (hunk 1 above)
Comment (sschuberth) [reply scanner/src/main/kotlin/scanners/scancode/ScanCode.kt]: Your proposal is a tad too specific for my taste, so I came up with a more generic extension function that I can also use in other similar places.

**Review by oheger-bosch — DISMISSED** [review]

**Review by oheger-bosch — APPROVED** [review]

File: analyzer/src/main/kotlin/managers/Cargo.kt [hunk 2]
```diff
@@ -49,6 +49,7 @@ import org.ossreviewtoolkit.model.config.RepositoryConfiguration
 import org.ossreviewtoolkit.model.jsonMapper
```
Comment (oheger-bosch) [inline analyzer/src/main/kotlin/managers/Cargo.kt:49]: Commit message nit: "A condition ... needs to be *adjusted* now..."

**Review by oheger-bosch — APPROVED** [review]
