### PR TITLE
fix(vcs): Consider VCS configurations in cache lookup

### LINKED ISSUE #9795: VersionControlSystem.forURL(...) incorrectly returning cached VCS instance
### Describe the bug

There is an API to get a VersionControlSystem instance by `vcsUrl` and `configs`:

```kotlin
/**
  * Return the applicable VCS for the given [vcsUrl], or null if none is applicable.
  */
@Synchronized
fun forUrl(vcsUrl: String, configs: Map<String, PluginConfig> = emptyMap()) =
    if (vcsUrl in urlToVcsMap) {
        urlToVcsMap[vcsUrl]
    } else { ...
```

https://github.com/oss-review-toolkit/ort/blob/cb49aeb4722a04703e125ed31b925f9af9c45b18/downloader/src/main/kotlin/VersionControlSystem.kt#L72

As it can be seen, it looks up a simple cache by the `vcsUrl`, and returns a VCS instance if it exists for the given `vcsUrl`.

Unfortunately, it does take into regard the `configs`map.

While this is not a problem at all in 99% of the cases, there are automated test cases that intentionally try out different `configs` and with this implementation get a VCS instance from the cache that is not configured in the expected way. This makes these automated test cases unstable, as it depends on the order of their executions if there are successful or fail.

### PR DESCRIPTION
**Pull request by wkl3nk**
When looking up a VCS implementation by repository URL or by a working tree directory from the cache, also consider the requested VCS configurations.

Fixes #9795.

### CODE REVIEW

File: downloader/src/main/kotlin/VersionControlSystem.kt [hunk 1]
```diff
@@ -72,8 +72,8 @@ abstract class VersionControlSystem : Plugin {
         fun forUrl(vcsUrl: String, configs: Map<String, PluginConfig> = emptyMap()) =
             // Do not use getOrPut() here as it cannot handle null values, also see
             // https://youtrack.jetbrains.com/issue/KT-21392.
-            if (vcsUrl in urlToVcsMap) {
-                urlToVcsMap[vcsUrl]
+            if ((vcsUrl to configs) in urlToVcsMap) {
+                urlToVcsMap[(vcsUrl to configs)]
```
Comment (sschuberth) [inline downloader/src/main/kotlin/VersionControlSystem.kt:76]: No parentheses required here.

File: downloader/src/main/kotlin/VersionControlSystem.kt [hunk 2]
```diff
@@ -86,15 +86,16 @@ abstract class VersionControlSystem : Plugin {
 
                     else -> forType(type, configs)
                 }.also {
-                    urlToVcsMap[vcsUrl] = it
+                    urlToVcsMap[(vcsUrl to configs)] = it
```
Comment (sschuberth) [inline downloader/src/main/kotlin/VersionControlSystem.kt:89]: No parentheses required here.

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: downloader/src/test/kotlin/VersionControlSystemTest.kt [hunk 3]
```diff
@@ -117,4 +118,42 @@ class VersionControlSystemTest : WordSpec({
...
+            vcs shouldBe null
+        }
+
+        "return a VCS instance that can handle a Git repository URL" {
+            val repositoryUrl = "https://github.com/oss-review-toolkit/ort.git"
+
+            val vcs = VersionControlSystem.forUrl(repositoryUrl)
+
+            vcs shouldNotBe null
+            vcs!!.type shouldBe VcsType.GIT
```
[the remark this answers is not in the document]
Comment (wkl3nk) [reply downloader/src/test/kotlin/VersionControlSystemTest.kt:137]: A cool. I looked out for something like this.

**Review by sschuberth — APPROVED** [review]
I have some ideas how to make this nicer while maybe changing semantics a bit. But let's get this in as-is for tomorrow's release.
