### PR TITLE
fix(node): Make passing `--use-system-ca` conditional

### LINKED ISSUE #11306: New NODE_OPTIONS injection breaks old versions
## Describe the bug

Commit https://github.com/oss-review-toolkit/ort/commit/92ae1609df6e31453adcdc1cd3d442043b3d00b7 introduce a mandatory flag for CA required by modern version of NodeJS.

This broke every single older < 20 Node scans as this flag is not allowed/recognized.

```
Yarn failed to resolve dependencies for path '<folder>/package.json':
IOException: Running 'yarn install --ignore-scripts --ignore-engines --immutable'
failed with exit code 9:
node: --use-system-ca is not allowed in NODE_OPTIONS
```

## To Reproduce

```bash
nvm install 16
nvm use 16
npm install -g yarn@1
yarn init -y

cat > index.js << 'EOF'
console.log("Hello, World from Node 16 with Yarn 1.x!");
EOF

export NODE_OPTIONS="--use-system-ca"

node -e '
const fs = require("fs");
const pkg = JSON.parse(fs.readFileSync("package.json"));
pkg.scripts = pkg.scripts || {};
pkg.scripts.start = "node index.js";
fs.writeFileSync("package.json", JSON.stringify(pkg, null, 2));
'
```

## Expected behavior
No have any options injected or evaluate version before inject any version

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #11306.

### CODE REVIEW

File: plugins/package-managers/node/src/main/kotlin/npm/Npm.kt [hunk 1]
```diff
@@ -57,8 +58,17 @@ internal object NpmCommand : CommandLineTool {
...
+        // As of Node 23.8.0, which ships with NPM 10.9.2, there is support to use trusted CA certificates present in
+        // the system store.
+        val environment = if (Semver(getVersion()).isGreaterThanOrEqualTo("10.9.2")) {
+            mapOf("NODE_OPTIONS" to "--use-system-ca")
+        } else {
+            emptyMap()
+        }
+
+        return super.run(*args, workingDir = workingDir, environment = environment)
+    }
```
Comment (fviernau) [inline plugins/package-managers/node/src/main/kotlin/npm/Npm.kt]: commit-msg: Can you refer to https://github.com/oss-review-toolkit/ort/commit/92ae1609df6e31453adcdc1cd3d442043b3d00b7 and explain why this needs to be fixed only for NPM?

File: plugins/package-managers/node/src/main/kotlin/npm/Npm.kt [hunk 2]
```diff
@@ -57,8 +58,17 @@ internal object NpmCommand : CommandLineTool {
 
     override fun getVersionRequirement(): RangeList = RangeListFactory.create("6.* - 11.*")
 
-    override fun run(workingDir: File?, vararg args: CharSequence): ProcessCapture =
-        super.run(*args, workingDir = workingDir, environment = mapOf("NODE_OPTIONS" to "--use-system-ca"))
+    override fun run(workingDir: File?, vararg args: CharSequence): ProcessCapture {
+        // As of Node 23.8.0, which ships with NPM 10.9.2, there is support to use trusted CA certificates present in
+        // the system store.
+        val environment = if (Semver(getVersion()).isGreaterThanOrEqualTo("10.9.2")) {
```
Comment (fviernau) [inline plugins/package-managers/node/src/main/kotlin/npm/Npm.kt]: Do you think it is ok to depend on the NPM version instead of on the node version? 
(It's not guaranteed IIUC that always the NPM version is used which ships by default with the node version)

**Review by fviernau — CHANGES_REQUESTED** [review]

File: plugins/package-managers/node/src/main/kotlin/npm/Npm.kt (hunk 2 above)
Comment (heliocastro) [reply plugins/package-managers/node/src/main/kotlin/npm/Npm.kt]: Not really. because node has nothing to do with npm at all.

File: plugins/package-managers/node/src/main/kotlin/npm/Npm.kt (hunk 1 above)
Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/npm/Npm.kt]: This is obsolete now, I've fixed this for Yarn and PNPM, too.

File: plugins/package-managers/node/src/main/kotlin/npm/Npm.kt (hunk 2 above)
Comment (fviernau) [reply plugins/package-managers/node/src/main/kotlin/npm/Npm.kt]: True, makes sense.

Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/npm/Npm.kt]: This is also obsolete now as I'm checking the Node version (to also cover Yarn and PNPM).

File: plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt [hunk 3]
```diff
@@ -61,8 +62,13 @@ internal object YarnCommand : CommandLineTool {
 
     override fun getVersionRequirement(): RangeList = RangeListFactory.create("1.3.* - 1.22.*")
 
-    override fun run(workingDir: File?, vararg args: CharSequence): ProcessCapture =
-        super.run(*args, workingDir = workingDir, environment = mapOf("NODE_OPTIONS" to "--use-system-ca"))
+    override fun run(workingDir: File?, vararg args: CharSequence): ProcessCapture {
+        val environment = buildMap {
+            if (NodeCommand.hasSystemCaSupport) put("NODE_OPTIONS", "--use-system-ca")
```
Comment (fviernau) [inline plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt]: Consider `hasUseSystemCaOption` instead. 

Maybe this is slightly clearer, because IIUC in older versions it was possible to specify ca files manually already.

File: plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt [hunk 4]
```diff
@@ -49,8 +50,13 @@ internal object PnpmCommand : CommandLineTool {
 
     override fun getVersionRequirement(): RangeList = RangeListFactory.create("5.* - 10.*")
 
-    override fun run(workingDir: File?, vararg args: CharSequence): ProcessCapture =
-        super.run(*args, workingDir = workingDir, environment = mapOf("NODE_OPTIONS" to "--use-system-ca"))
+    override fun run(workingDir: File?, vararg args: CharSequence): ProcessCapture {
```
Comment (fviernau) [inline plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt]: out-of-scope: Would it make sense to, as a follow-up, adjust the overrides to override `fun run(vararg args: CharSequence, workingDir: File? = null, environment: Map<String, String> = emptyMap())` instead, to insert the node option into the given environment? (This way, the implementation would be effective for all overrides of `run()`.

**Comment by fviernau** [comment]
out of scope: Is there a reason why the logic does not apply also to Yarn2?

File: plugins/package-managers/node/src/main/kotlin/npm/Npm.kt (hunk 2 above)
Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/npm/Npm.kt]: > Not really. because node has nothing to do with npm at all.

Well, Node is the runtime of NPM, so you can't run NPM without Node (or a compatible runtime). And actually, `--use-system-ca` is a Node option, not an NPM option in the first place, that NPM just forwards to Node.

So I'd say that Node _does_ name something to do with NPM.

File: plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt (hunk 4 above)
Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/pnpm/Pnpm.kt]: Done in a new commit.

**Review by heliocastro — DISMISSED** [review]
Works on our side. Thanks.

**Comment by sschuberth** [comment]
> out of scope: Is there a reason why the logic does not apply also to Yarn2?

I guess because it uses the (so far "unsupported") `run()` override. But as that has changed now, I've added the logic to Yarn2, too.

File: plugins/package-managers/node/src/main/kotlin/NodeCommand.kt [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+
+import java.io.File
+
+import org.ossreviewtoolkit.utils.common.CommandLineTool
+
+import org.semver4j.Semver
+
+internal object NodeCommand : CommandLineTool {
+    // As of Node 23.8.0, there is support to use trusted CA certificates present in the system store.
+    val hasUseSystemCaOption get() = Semver(getVersion()).isGreaterThanOrEqualTo("23.8.0")
```
Comment (oheger-bosch) [inline plugins/package-managers/node/src/main/kotlin/NodeCommand.kt]: Instead of computing the value every time, should this be a lazy property? Otherwise, before every command execution, the version command is run.

**Review by fviernau — APPROVED** [review]

File: plugins/package-managers/node/src/main/kotlin/NodeCommand.kt (hunk 5 above)
Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/NodeCommand.kt]: I was a bit unsure about this, as theoretically the Node version _could_ change between calls.

Comment (oheger-bosch) [reply plugins/package-managers/node/src/main/kotlin/NodeCommand.kt]: Do you mean in the same Analyzer run or in some environment which executes multiple runs on the same JVM?

Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/NodeCommand.kt]: Yes. Like I said, it's a bit theoretical, but possible. I'm also thinking of tests / manual debugging where the Node version is switched at runtime to check something.

Comment (oheger-bosch) [reply plugins/package-managers/node/src/main/kotlin/NodeCommand.kt]: Hm, these are rather corner cases. I am a bit worried to let the production use case suffer because of this. A single execution of the version command may not be problematic, but if there are many calls, for instance, if metadata for many dependencies is to be resolved, this can accumulate. Also, the logs will probably get cluttered by the additional process invocations.

Could you maybe make the command a class rather than an object, so that it lives only in the scope of a single Analyzer run?

Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/NodeCommand.kt]: > Could you maybe make the command a class rather than an object, so that it lives only in the scope of a single Analyzer run?

Then I'm indeed rather making it a lazy property than requiring users to create an instance.
