### PR TITLE
fix(analyzer): Correctly determine the project name from Windows paths

### LINKED ISSUE #2900: Improve path handling on Windows
If the remote master of a GIT repository is set to "C:\RemoteMaster-Sample" (with a backslash) it will result in an analyzer error: 
```
'RemoteMaster-Sample' failed with: IllegalArgumentException: An identifier's properties must not contain ':' because that character is used as a separator in the string representation: type='Unmanaged', namespace='', name='C:\RemoteMaster-Sample', version='cXXXe'.
09:10 [Analyzer-1] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Resolving Unmanaged dependencies for 'RemoteMaster-Sample' took 1 s.
```

You have to set the remote master to "C:/RemoteMaster-Sample" (with a forward slash) in the GIT settings for oss-review-toolkit to work. It should not be required to change your GIT repository names for oss-review-toolkit to work.

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #2900.

Signed-off-by: Sebastian Schuberth <sschuberth@gmail.com>

### CODE REVIEW

File: analyzer/src/main/kotlin/managers/Unmanaged.kt [hunk 1]
```diff
@@ -101,10 +102,12 @@ class Unmanaged(
 
             else -> {
                 // For all non-GitRepo VCSes derive the name from the VCS URL.
+                val fileUrl = File(vcsInfo.url).takeIf { it.exists() } ?: File(URI(vcsInfo.url))
+
                 Identifier(
                     type = managerName,
                     namespace = "",
-                    name = vcsInfo.url.split('/').last().removeSuffix(".git"),
+                    name = fileUrl.name.removeSuffix(".git"),
```
Comment (fviernau) [inline analyzer/src/main/kotlin/managers/Unmanaged.kt:110]: Have you considered to (also) change the code which puts the `\` into `VcsInfo.url`?
E.g. should that be changed to put "invariant separator paths" in there always?

**Review by fviernau — APPROVED** [review]

File: analyzer/src/main/kotlin/managers/Unmanaged.kt (hunk 1 above)
Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/Unmanaged.kt:110]: I'll take a look at that idea and eventually create a follow-up PR later.

Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/Unmanaged.kt:110]: See https://github.com/oss-review-toolkit/ort/pull/6407.
