### PR TITLE
analyzer: Support references to local modules with `GoMod`

### LINKED ISSUE #7649: GoMod: Support for local / sub module dependencies
In mono repo setups with multiple modules, some of the modules may depend on other modules of the same repository.
In that case listing the modules with `go list` as done by `GoMod` yields more than one module with `Main=true`, whereas all such modules do not have a version. This in turn makes ORT's precondition check fail with:
```
IllegalArgumentException: Expected exactly one unique package without version but got Identifier
```
This is solely, because this use case has deliberately not yet been implemented. 

The problem can happen in the use cases:
1. Replacing a dependency with a local one (#6710)
    ```
    replace gitlab.com/myProject/myRepo/GoProject => ../localProject
    ```
2. Analyzing mono repos with references between modules (#6532, #6519)
   ```
    ort/cli/build/install/ort/bin/ort -P ort.analyzer.allowDynamicVersions=true analyze -i $GOPATH/src/k8s.io/kubernetes -o ~/kubernetesORTAnalyzerOutput -f JSON
   ```

There were multiple bugs filed for this. I've decided to close them in favor of this single consolidated enhancement ticket, also because it's not a bug but a missing feature: 
- #6710
- #6532
- #6519

Interesting things:
- https://github.com/golang/go/issues/40513#issuecomment-667328207
- https://go.dev/ref/mod#go-mod-file-replace
- ```
  go list -json -m all
  go: errors parsing go.mod:
  go.mod:18: replacement module without version must be directory path (rooted or starting with ./ or ../) 
  ```

### PR DESCRIPTION
**Pull request by fviernau**
The only way of referencing a module on the local file system from another is by specifying a relative or absolute path via a replace directive. This is currently not supported by ORT's Go Modules integration.

Implement that support, so that a reference inbetween two modules on the local file system gets represent as a `PackageReference` between the corresponding `Project`s (in ORT speak). However, keep on failing in case a referenced module is not located within the analysis root, because that would violate ORT's package manager API.

Fixes #7649.

### CODE REVIEW

File: analyzer/src/funTest/kotlin/managers/GoModFunTest.kt [hunk 1]
```diff
@@ -22,10 +22,12 @@ package org.ossreviewtoolkit.analyzer.managers
 import io.kotest.core.spec.style.StringSpec
 import io.kotest.matchers.collections.shouldHaveSize
 import io.kotest.matchers.should
+import org.ossreviewtoolkit.downloader.VersionControlSystem
```
Comment (sschuberth) [inline analyzer/src/funTest/kotlin/managers/GoModFunTest.kt:25]: Wrong import ordering (also below).

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 2]
```diff
@@ -220,15 +220,20 @@ class GoMod(
 
         return if (version.isBlank()) {
             // If the version is blank, it is a project in ORT speak.
-            check(main) { "Found a local module dependency which is not supported." }
-
             checkNotNull(dir) { "For projects, the directory is expected to not be null." }
 
+            val projectDir = File(dir)
+
+            require(projectDir.absoluteFile.startsWith(analysisRoot.absoluteFile)) {
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt]: As `analysisRoot` is absolute by convention, you can drop `.absoluteFile` here.

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 3]
```diff
@@ -220,15 +220,20 @@ class GoMod(
...
+                "A replace directive references a module in '${projectDir.absolutePath}' outside of analysis root " +
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt]: How about using `val projectDir = File(dir).absoluteFile` in line 225 so you can just use `$projectDir` here, and also simplify line 227?

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 4]
```diff
@@ -241,6 +246,19 @@ class GoMod(
         }
     }
 
+    private fun getProjectName(projectDir: File): String {
+        projectDir.resolve("go.mod").let { goModFile ->
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt]: Consider using `also` instead of `let` as the return value does not matter.

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 5]
```diff
@@ -241,6 +246,19 @@ class GoMod(
...
+            require(goModFile.isFile) {
+                "Expected file '$goModFile.' which does not exist."
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt]: Is the dot after the variable intended?

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 6]
```diff
@@ -241,6 +246,19 @@ class GoMod(
...
+            }
+        }
+
+        val list = runGo("list", "-m", "-json", "-buildvcs=false", workingDir = projectDir)
+
+        return list.stdout.byteInputStream().use { JSON.decodeToSequence<ModuleInfo>(it) }.single().path
+    }
+
+
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt]: One superfluous blank line.

File: analyzer/src/testFixtures/kotlin/Extensions.kt [hunk 7]
```diff
@@ -63,19 +64,21 @@ fun PackageManager.resolveSingleProject(definitionFile: File, resolveScopes: Boo
...
 /**
- * Resolve the dependencies of a [definitionFile] which should create at least one project. All created projects will be
- * collated in an [AnalyzerResult] with their dependency graph.
+ * Resolve the dependencies of all [definitionFiles] which should create at least one project. All created projects will
+ * be collated in an [AnalyzerResult] with their dependency graph.
  */
-fun PackageManager.collateMultipleProjects(definitionFile: File): AnalyzerResult {
-    val managerResult = resolveDependencies(listOf(definitionFile), emptyMap())
+fun PackageManager.collateMultipleProjects(vararg definitionFiles: File): AnalyzerResult {
+    val managerResult = resolveDependencies(definitionFiles.toList(), emptyMap())
```
Comment (sschuberth) [inline analyzer/src/testFixtures/kotlin/Extensions.kt:71]: Prefer `.asList()` to avoid a conversion.

**Review by sschuberth — CHANGES_REQUESTED** [review]

**Review by sschuberth — DISMISSED** [review]

File: analyzer/src/funTest/kotlin/managers/GoModFunTest.kt [hunk 8]
```diff
@@ -93,12 +95,28 @@
...
+                "<REPLACE_DEFINITION_FILE_PATH_UTILS>" to expectedDefinitionFilePathUtils,
+                "<REPLACE_PATH_UTILS>" to expectedDefinitionFilePathUtils.substringBeforeLast('/')
+            )
+        )
     }
 })
+
+private fun getDefinitionFilePath(definitionFile: File): String {
+    val projectDir = definitionFile.parentFile
+    val vcsDir = VersionControlSystem.forDirectory(projectDir)!!
```
[the remark this answers is not in the document]
Comment (fviernau) [reply analyzer/src/funTest/kotlin/managers/GoModFunTest.kt]: If pushed once more to fix this.

**Review by sschuberth — APPROVED** [review]
