### PR TITLE
PubCacheReader: Fix handling of Git dependencies

### LINKED ISSUE #5196: Pub: Support Git dependency definitions
If a `pubspec.yaml` contains a [git dependency definition](https://docs.flutter.dev/development/packages-and-plugins/using-packages#dependencies-on-unpublished-packages):
```
dependencies:
  carousel_pro:
    git:
      url: https://github.com/jlouage/flutter-carousel-pro.git
      ref: master
```

The analyzer fails with the error:
```
issues:
  'Pub::pubspec.yaml:':
  - timestamp: "2022-03-28T11:53:08.317041Z"
    source: "Pub"
    message: "Resolving Pub dependencies for 'pubspec.yaml' failed with: IOException:\
      \ Could not find package info for carousel_pro"
    severity: "ERROR"
```

This breaks the analyzer run and no valid dependency tree is created.

### PR DESCRIPTION
**Pull request by MarcelBochtler**
The `packageInfo` for Pub's Git dependencies contain different
information as for hosted dependencies. Fix the path construction for
dependency resolution from Pub's cache.

Resolves #5196.

### CODE REVIEW

**Comment by sschuberth** [comment]
> contain different information as

contains different information than

File: analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt [hunk 1]
```diff
@@ -0,0 +1,104 @@
...
+
+    val reader = PubCacheReader()
+
+    beforeSpec {
+        // Prepare expected cache directories.
+        val pubCacheDir = if (Os.isWindows) {
+            File(Os.env["LOCALAPPDATA"], "Pub/Cache")
+        } else {
+            Os.userHomeDirectory.resolve(".pub-cache")
+        }
```
Comment (sschuberth) [inline analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:46]: Can we instead make `PubCacheReader.pubCacheRoot` `internal` and use it?

File: analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+
+        gitPackageCacheDir = pubCacheDir.resolve("git")
+            .resolve("$PACKAGE_NAME-$RESOLVED_REF")
+            .also { it.mkdirs() }
```
Comment (sschuberth) [inline analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:50]: Maybe better use `safeMkdirs()`? Same below.

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+
+        hostedPackageCacheDir = pubCacheDir.resolve("hosted")
+            .resolve("oss-review-toolkit.org")
+            .resolve("$PACKAGE_NAME-$PACKAGE_VERSION")
+            .also { it.mkdirs() }
+
+        println(hostedPackageCacheDir)
```
[the remark this answers is not in the document]
Comment (MarcelBochtler) [reply analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:57]: Sorry debug leftover :)

File: analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+    }
+
+    afterSpec {
+        gitPackageCacheDir.delete()
+        hostedPackageCacheDir.parentFile.deleteRecursively()
```
[the remark this answers is not in the document]
Comment (MarcelBochtler) [reply analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:62]: To do that, I would need a possibility to adjust the `PubCacheReader.pubCacheRoot` in the production code. Do you think this is worth the effort?

[the remark this answers is not in the document]
Comment (sschuberth) [reply analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:53]: Nope, probably not.

[the remark this answers is not in the document]
Comment (MarcelBochtler) [reply analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt]: Done.

File: analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+
+private const val PACKAGE_NAME = "non-existing-package"
+private const val PACKAGE_VERSION = "0.0.0"
+private const val RESOLVED_REF = "0000000000000000000000000000000000000000"
+
+class PubCacheReaderTest : WordSpec({
+    val tmpPubCacheDir = createSpecTempDir().also { Os.env["PUB_CACHE"] = it.absolutePath }
+    val gitPackageCacheDir = tmpPubCacheDir.resolve("git/$PACKAGE_NAME-$RESOLVED_REF")
+    val hostedPackageCacheDir =
+        tmpPubCacheDir.resolve("hosted/oss-review-toolkit.org/$PACKAGE_NAME-$PACKAGE_VERSION")
```
Comment (sschuberth) [inline analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:38]: If I didn't count wrong, this should actually fit into a single line.

File: analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+
+    beforeSpec {
+        // Prepare expected cache directories.
+        gitPackageCacheDir.safeMkdirs()
+        hostedPackageCacheDir.safeMkdirs()
+    }
+
+    afterSpec {
+        tmpPubCacheDir.deleteRecursively()
+    }
```
Comment (sschuberth) [inline analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:50]: This is not needed anymore with `createSpecTempDir`.

File: analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+class PubCacheReaderTest : WordSpec({
+    val tmpPubCacheDir = createSpecTempDir().also { Os.env["PUB_CACHE"] = it.absolutePath }
+    val gitPackageCacheDir = tmpPubCacheDir.resolve("git/$PACKAGE_NAME-$RESOLVED_REF")
+    val hostedPackageCacheDir =
+        tmpPubCacheDir.resolve("hosted/oss-review-toolkit.org/$PACKAGE_NAME-$PACKAGE_VERSION")
+
+    val reader = PubCacheReader()
+
+    beforeSpec {
+        // Prepare expected cache directories.
```
Comment (sschuberth) [inline analyzer/src/test/kotlin/managers/utils/PubCacheReaderTest.kt:43]: Is this comment still valuable?

**Review by sschuberth — CHANGES_REQUESTED** [review]

**Review by sschuberth — APPROVED** [review]
