### PR TITLE
fix(scanner): Filter scan results by scanner name

### LINKED ISSUE #7231: New detected licenses appears for SPDX project with submodule
Our customer has a repository containing a `project.spdx.yml` file. In this file, Git submodules, pointing to third party repositories, are referenced as packages.

In this repository, the customer defines a `license_finding_curations` in a `package_configurations` for one of these referenced packages. Thus, it should be possible to prevent rule violation for code in the third party repositories.

Unfortunately, since the 20.06, there `packages_configuration` are not applied anymore and the customer get some rule violations.

A minimal project reproducing the setup:
https://github.com/nnobelis/spdx-project

Last successful build: version 47bd691..

### PR DESCRIPTION
**Pull request by nnobelis**
When a project scanner is configured alongside a package scanner, the scan results could be duplicated if the provenances of those packages are overlapping (e.g. in the case of repositories with Git submodules). This commit addresses the bug by constructing a map of packages with their scanners and filtering the scan results using this map.

Fixes #7231.

**Breaking change: OrtResult deserialization is not backwards compatible.**

### CODE REVIEW

**Comment by nnobelis** [comment]
@fviernau The new test depends on my repository https://github.com/nnobelis/spdx-project which is not nice.

I saw you were using https://github.com/oss-review-toolkit/ort-test-data-scanner in your tests. Should we fork my repo in ORT or something ?

**Comment by sschuberth** [comment]
> Fixes 7231.

Missing `#` before the issue number.

File: model/src/main/kotlin/ScannerRun.kt [hunk 1]
```diff
@@ -72,6 +73,12 @@ data class ScannerRun(
     @JsonSerialize(converter = ScanResultSortedSetConverter::class)
     val scanResults: Set<ScanResult>,
 
+    /**
+     * The scanners for each scanned package.
+     */
+    @JsonSerialize(converter = ScannersMapConverter::class)
```
Comment (sschuberth) [inline model/src/main/kotlin/ScannerRun.kt:79]: If the goal is to just sort the keys in the map by alphabetic string representation, using `@JsonPropertyOrder(alphabetic = true)` should be enough.

File: scanner/src/main/kotlin/Scanner.kt [hunk 2]
```diff
@@ -111,12 +111,16 @@ class Scanner(
...
         val projectScannerWrappers = scannerWrappers[PackageType.PROJECT].orEmpty()
         val packageScannerWrappers = scannerWrappers[PackageType.PACKAGE].orEmpty()
+        val scannersByPackages = mutableMapOf<Identifier, Set<String>>()
 
         val projectResults = if (projectScannerWrappers.isNotEmpty()) {
             val packages = ortResult.getProjects(skipExcluded).mapTo(mutableSetOf()) { it.toPackage() }
 
             logger.info { "Scanning ${packages.size} project(s) with ${projectScannerWrappers.size} scanner(s)." }
 
+            val projectScanners = scannerWrappers[PackageType.PROJECT].orEmpty().map { it.name }.toSet()
```
Comment (sschuberth) [inline scanner/src/main/kotlin/Scanner.kt:121]: Can we reuse `projectScannerWrappers` here?

File: scanner/src/main/kotlin/Scanner.kt [hunk 3]
```diff
@@ -137,6 +141,9 @@ class Scanner(
 
             logger.info { "Scanning ${packages.size} package(s) with ${packageScannerWrappers.size} scanner(s)." }
 
+            val packageScanners = scannerWrappers[PackageType.PACKAGE].orEmpty().map { it.name }.toSet()
```
Comment (sschuberth) [inline scanner/src/main/kotlin/Scanner.kt:144]: Can we reuse `packageScannerWrappers` here?

File: model/src/main/kotlin/ScannerRun.kt (hunk 1 above)
Comment (fviernau) [reply model/src/main/kotlin/ScannerRun.kt:79]: Wouldn't ordering the values be needed as well to be deterministic, to allow for use with expected results?

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+
+import org.ossreviewtoolkit.model.Identifier
+import org.ossreviewtoolkit.model.OrtResult
+import org.ossreviewtoolkit.model.PackageType
+import org.ossreviewtoolkit.model.fromYaml
+import org.ossreviewtoolkit.utils.test.getAssetFile
+import org.ossreviewtoolkit.utils.test.shouldNotBeNull
+
+class MultipleScannersTest : WordSpec({
+    "Scanning a set of packages with overlapping provenance" should {
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:33]: How about sth. like the following?
```
"Scanning a project and a package with overlapping provenance and non overlapping scanners" should {
      "return scan results with non-overlapping scanners"
```

"

File: scanner/src/funTest/assets/analyzer-result_for_multiple_scanners.yml [hunk 5]
```diff
@@ -0,0 +1,124 @@
+---
+repository:
```
Comment (fviernau) [inline scanner/src/funTest/assets/analyzer-result_for_multiple_scanners.yml:2]: This just contains one package and one project. Would it make sense to create it programatically instead?

File: scanner/src/main/kotlin/Scanner.kt [hunk 6]
```diff
@@ -72,7 +72,7 @@ import org.ossreviewtoolkit.utils.spdx.toSpdx
 const val TOOL_NAME = "scanner"
 
 @Suppress("TooManyFunctions")
-class Scanner(
+data class Scanner(
```
Comment (fviernau) [inline scanner/src/main/kotlin/Scanner.kt:75]: Why `data class`?

File: scanner/src/main/kotlin/Scanner.kt [hunk 7]
```diff
@@ -169,7 +176,8 @@ class Scanner(
             config = filteredScannerConfig,
             provenances = projectResults.provenances + packageResults.provenances,
             scanResults = projectResults.scanResults + packageResults.scanResults,
-            files = projectResults.files + packageResults.files
+            files = projectResults.files + packageResults.files,
+            scanners = scannersByPackages
```
Comment (fviernau) [inline scanner/src/main/kotlin/Scanner.kt:180]: I believe line 180 should be `projectResult.scanners + packageResults.scanners`.

(Which implies the logic you added above should instead go into the other overload of `scan()`)

What do you think?

**Review by fviernau — CHANGES_REQUESTED** [review]

File: scanner/src/main/kotlin/Scanner.kt (hunk 6 above)
Comment (nnobelis) [reply scanner/src/main/kotlin/Scanner.kt:75]: To be able to `copy()` the scanner with a different `scannerWrappers`: https://github.com/bosch-io/oss-review-toolkit/blob/b90e2a3b35ba8241be1d0d6d9c140d2a2cdebb71/scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt#L38

File: model/src/main/kotlin/ScannerRun.kt (hunk 1 above)
Comment (nnobelis) [reply model/src/main/kotlin/ScannerRun.kt]: @fviernau 
@sschuberth 
Is there a special annotation to do that of should I again create a converter ?

Comment (sschuberth) [reply model/src/main/kotlin/ScannerRun.kt]: > Is there a special annotation to do that of should I again create a converter ?

If the values in a map should be sorted as well, I believe you need a converter again.

File: scanner/src/main/kotlin/Scanner.kt (hunk 7 above)
Comment (nnobelis) [reply scanner/src/main/kotlin/Scanner.kt]: Yes it is better.

File: scanner/src/funTest/assets/analyzer-result_for_multiple_scanners.yml (hunk 5 above)
Comment (nnobelis) [reply scanner/src/funTest/assets/analyzer-result_for_multiple_scanners.yml]: Done. Could you please review the changes ? I think I over complicated it and don't need to build the dependency graph by hand.

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 8]
```diff
@@ -0,0 +1,114 @@
...
+        path = ""
+    )
+
+    val project = Project.EMPTY.copy(
+        id = createId("spdx-project"),
+        vcs = vcsProject,
+        vcsProcessed = vcsProject.normalize()
+    )
+
+    val scopes = mapOf(":spdx-project::default" to listOf(RootDependencyIndex(0, 0)))
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:93]: I believe that for this test it suffices to not link the package to the project at all.
So, you  could just omit any scopes and the dependency graph. Would that make sense?

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 9]
```diff
@@ -0,0 +1,114 @@
...
+
+    val pkg = Package.EMPTY.copy(
+        id = createId("spdx-dependency"),
+        vcs = vcsPackage,
+        vcsProcessed = vcsPackage.normalize()
+    )
+
+    val vcsProject = VcsInfo(
+        type = VcsType.GIT,
+        url = "https://github.com/nnobelis/spdx-project.git",
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:82]: This is using a repo under you namespace. I believe that you could just use any `test-data` repo under `oss-review-toolkit`. IIUC you are after overlapping provenances, not necessarily covering submodules. So, maybe https://github.com/oss-review-toolkit/ort-test-data-scanner can be used?

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 10]
```diff
@@ -0,0 +1,114 @@
...
+    val dependencyGraph = mapOf(
+        DEFAULT_NS to DependencyGraph(
+            listOf(pkg.id),
+            scopes = scopes,
+            nodes = listOf(
+                DependencyGraphNode(0, 0, PackageLinkage.STATIC)
+            )
+        )
+    )
+    val analyzerRun = AnalyzerRun.EMPTY.copy(
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:103]: Empty lines are a bit inconsistent. in this function.

File: scanner/src/main/kotlin/Scanner.kt (hunk 6 above)
Comment (fviernau) [reply scanner/src/main/kotlin/Scanner.kt:75]: I'm not sure about the data class thing, have you considered adding a parameter to `createScanner()` as alternative?

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 11]
```diff
@@ -0,0 +1,114 @@
...
+import org.ossreviewtoolkit.model.PackageLinkage
+import org.ossreviewtoolkit.model.PackageType
+import org.ossreviewtoolkit.model.Project
+import org.ossreviewtoolkit.model.RootDependencyIndex
+import org.ossreviewtoolkit.model.VcsInfo
+import org.ossreviewtoolkit.model.VcsType
+import org.ossreviewtoolkit.utils.test.shouldNotBeNull
+
+private const val DEFAULT_NS = "SpdxDocumentFile"
+private const val DEFAULT_VERSION = ""
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:41]: Would it make sense to replace above two constants with two constants of type `Identifier` ? (One for the package, one for the project
) ?

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 12]
```diff
@@ -0,0 +1,114 @@
...
+            scannerWrappers = mapOf(
+                PackageType.PROJECT to listOf(dummyScanners.copy(name = "Dummy2")),
+                PackageType.PACKAGE to listOf(dummyScanners)
+            )
+        ).scan(analyzerResult, skipExcluded = false, emptyMap())
+
+        "return scan results with non-overlapping scanners" {
+            ortResult.scanner.shouldNotBeNull {
+                val results = getScanResults(Identifier(DEFAULT_NS, "", "spdx-project", DEFAULT_VERSION))
+                results.map { it.scanner.name }.toSet() shouldBe setOf("Dummy2")
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:58]: I'd prefer if `toSet()` was dropped and `should containExactly("Dummy")` be used instead.

File: scanner/src/main/kotlin/Scanner.kt [hunk 13]
```diff
@@ -238,11 +239,16 @@ class Scanner(
             }
         }
 
+        val scannersByPackages = mutableMapOf<Identifier, Set<String>>()
+        val scannerNames = scanners.map { it.name }.toSet()
+        packages.associateByTo(scannersByPackages, { it.id }) { scannerNames }
```
Comment (fviernau) [inline scanner/src/main/kotlin/Scanner.kt:244]: Can be simplified:
```
val scannerNames = scanners.mapTo(mutableSetOf()) { it.name }
val scannerNamesByPackageId = packages.associateBy({ it.id }, { scannerNames })
```

**Review by fviernau — CHANGES_REQUESTED** [review]

File: model/src/main/kotlin/ScannerRun.kt [hunk 14]
```diff
@@ -29,6 +29,7 @@ import org.ossreviewtoolkit.model.config.ScannerConfiguration
 import org.ossreviewtoolkit.model.utils.FileListSortedSetConverter
 import org.ossreviewtoolkit.model.utils.ProvenanceResolutionResultSortedSetConverter
 import org.ossreviewtoolkit.model.utils.ScanResultSortedSetConverter
+import org.ossreviewtoolkit.model.utils.ScannersMapConverter
```
Comment (fviernau) [inline model/src/main/kotlin/ScannerRun.kt:32]: commit-message: This commit fixes a more general problem than what is described in the commit message. 

The scanner may used different set of scanners for scanning different packages. The same holds for projects. `ScannerRun` does not contain that information, and `ScannerRun.getScanResultsById()` just returns all scans matching the packages (nested) provenance, disregarding which scanners are to be used for the particular package. Extend the data model to contain that information and use it to adjust the internals of `getScanResultsById()` to adhere to the set of scanners to be used for the particular project or package.


----

Just as a hint: Which scanner to use for scanning a project / package depends on (haven't double checked):
- `--skip-excluded`
- `--skip-concluded`
- `--scanners`
- `--project-scanners

**Review by fviernau — CHANGES_REQUESTED** [review]

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt (hunk 9 above)
Comment (nnobelis) [reply scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:82]: I am really confused by this repository as there are no configuration file for any package managers ?!
How the project/package identifiers are supposed to look like ?

If I try to create a `Dummy::project:1.0.0` Project and  `Dummy::package:1.0.0` Package like you did in your `ScannerIntegrationFunTest`, the scanners are not workin.

I get a `ScannerDetails` with name `ProvenanceResolver` that contains a single issue:
`IOException: Could not resolve provenance for package 'Dummy::project:1.0.0' for source code origins [VCS, ARTIFACT].`.

File: model/src/main/kotlin/ScannerRun.kt (hunk 14 above)
Comment (nnobelis) [reply model/src/main/kotlin/ScannerRun.kt:32]: I don't understand the last sentence of your comment.

Comment (fviernau) [reply model/src/main/kotlin/ScannerRun.kt:32]: I suppose you mean the sentence below the horizontal line, I meant to list the things which can influence which scanner are to be used for a package / project.

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt (hunk 8 above)
Comment (nnobelis) [reply scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:93]: Yes, it is working !

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt (hunk 9 above)
Comment (nnobelis) [reply scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:82]: Yes I had a VCS info but in the end, the bug was caused by the dependency graph. When I removed it, the `ProvenanceResolver` error is gone.

File: model/src/main/kotlin/ScannerRun.kt (hunk 14 above)
Comment (nnobelis) [reply model/src/main/kotlin/ScannerRun.kt:32]: Understand. Maybe also `--package-types` ?

File: model/src/main/kotlin/ScannerRun.kt [hunk 15]
```diff
@@ -192,6 +200,8 @@ data class ScannerRun(
 
         val scanResultsByPath = resolutionResult.getKnownProvenancesWithoutVcsPath().mapValues { (_, provenance) ->
             scanResultsByProvenance[provenance].orEmpty()
+        }.mapValues { scanResults ->
```
Comment (fviernau) [inline model/src/main/kotlin/ScannerRun.kt:203]: Could you use `(_ , scanResults) ->` instead of just `scanResults ->` ?

File: model/src/main/kotlin/utils/SortedSetConverters.kt [hunk 16]
```diff
@@ -74,6 +75,11 @@ class ProvenanceResolutionResultSortedSetConverter :
     override fun convert(value: Set<ProvenanceResolutionResult>) = value.toSortedSet(compareBy { it.id })
 }
 
+class ScannersMapConverter : StdConverter<Map<Identifier, Set<String>>, Map<Identifier, Set<String>>>() {
+    override fun convert(value: Map<Identifier, Set<String>>) =
+        value.mapValues { it.value.toSortedSet() }.toSortedMap(compareBy { it })
```
Comment (fviernau) [inline model/src/main/kotlin/utils/SortedSetConverters.kt:80]: Quesion: Is it possible to call `toSortedMap` without parameter ?

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 17]
```diff
@@ -0,0 +1,97 @@
...
+import org.ossreviewtoolkit.model.Identifier
+import org.ossreviewtoolkit.model.OrtResult
+import org.ossreviewtoolkit.model.Package
+import org.ossreviewtoolkit.model.PackageType
+import org.ossreviewtoolkit.model.Project
+import org.ossreviewtoolkit.model.VcsInfo
+import org.ossreviewtoolkit.model.VcsType
+import org.ossreviewtoolkit.utils.test.shouldNotBeNull
+
+private val PROJECT_IDENTIFIER = Identifier("Dummy", "", "project", "1.0.0")
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:37]: Consider renaming this to just `PROJECT_ID`, same right below.

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 18]
```diff
@@ -0,0 +1,97 @@
...
+        val scannerWrappers = mapOf(
+            PackageType.PROJECT to listOf(dummyScanner.copy(name = "Dummy2")),
+            PackageType.PACKAGE to listOf(dummyScanner)
+        )
+        val ortResult = createScanner(scannerWrappers).scan(analyzerResult, skipExcluded = false, emptyMap())
+
+        "return scan results with non-overlapping scanners" {
+            ortResult.scanner.shouldNotBeNull {
+                val results = getScanResults(PROJECT_IDENTIFIER)
+                results.map { it.scanner.name }.toSet() should containExactly("Dummy2")
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:54]: The String `"Dummy2"` is ok, but `"Dummy"` is a bit magic. 
I propose to 1. inline the variable `dummyScanner` and also use the constructor parameter instead of `copy()`. This in turn allows to not make `DummyScanner` a data class.

```
PackageType.PROJECT to listOf(DummyScanner(name = "Dummy1")),
PackageType.PACKAGE to listOf(DummyScanner(name = "Dummy2"))
```

File: scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt [hunk 19]
```diff
@@ -0,0 +1,97 @@
...
+        vcs = vcsPackage,
+        vcsProcessed = vcsPackage.normalize()
+    )
+
+    val vcsProject = VcsInfo(
+        type = VcsType.GIT,
+        url = "https://github.com/oss-review-toolkit/ort-test-data-scanner.git",
+        revision = "97d57bb4795bc41f496e1a8e2c7751cefc7da7ec",
+        path = ""
+    )
```
Comment (fviernau) [inline scanner/src/funTest/kotlin/scanners/MultipleScannersTest.kt:81]: If I'm not missing anything `vcsPackage` and `vcsProject` are identical.
So, let's drop one of the two and rename the remaining to just `vcs`.

**Review by fviernau — CHANGES_REQUESTED** [review]

File: model/src/main/kotlin/ScannerRun.kt [hunk 20]
```diff
@@ -72,6 +73,12 @@ data class ScannerRun(
     @JsonSerialize(converter = ScanResultSortedSetConverter::class)
     val scanResults: Set<ScanResult>,
 
+    /**
+     * The scanners for each scanned package.
```
Comment (fviernau) [inline model/src/main/kotlin/ScannerRun.kt:77]: The scanners for a package can also be empty. 
So, it should contain also IDs for not scanned packages.
How about saying instead:

The names of the scanners which have been used to scan the package.

File: model/src/main/kotlin/ScannerRun.kt (hunk 15 above)
Comment (nnobelis) [reply model/src/main/kotlin/ScannerRun.kt:203]: This is `mapValues`, there is only one parameter.

Comment (fviernau) [reply model/src/main/kotlin/ScannerRun.kt:203]: Isn't the value a tuple `(path, scanResults)` so it can be decomposed ?

File: evaluator/src/test/kotlin/ProjectSourceRuleTest.kt [hunk 21]
```diff
@@ -229,6 +229,6 @@ private fun createOrtResult(
                     )
                 )
             )
-        )
+        ).copy(scanners = mapOf(id to setOf("")))
```
Comment (fviernau) [inline evaluator/src/test/kotlin/ProjectSourceRuleTest.kt:232]: Please remove this `copy()` call and adjust `scannRunOf` to assign the scanner names internally, so that the return `ScannerRun` is consistent. (This way all callers of `scannerRunOf` get fixed.

File: model/src/main/kotlin/ScannerRun.kt (hunk 20 above)
Comment (fviernau) [reply model/src/main/kotlin/ScannerRun.kt:77]: This is not addressed yet.

File: utils/test/src/main/kotlin/Utils.kt [hunk 22]
```diff
@@ -189,6 +189,12 @@ fun scannerRunOf(vararg pkgScanResults: Pair<Identifier, List<ScanResult>>): Sca
         )
     }
 
+    val scanners = mutableMapOf<Identifier, MutableSet<String>>()
```
Comment (fviernau) [inline utils/test/src/main/kotlin/Utils.kt:192]: This can be simplified to:

```
val scanners = pkgScanResults.map { (id, scanResultsForId) ->
        id to scanResultsForId.mapTo(mutableSetOf()) { it.scanner.name}
    }.toMap()
``

**Review by fviernau — CHANGES_REQUESTED** [review]

File: utils/test/src/main/kotlin/Utils.kt (hunk 22 above)
Comment (nnobelis) [reply utils/test/src/main/kotlin/Utils.kt]: IntelliJ suggested even the further optimization:

```
val scanners = pkgScanResults.associate { (id, scanResultsForId) ->
        id to scanResultsForId.mapTo(mutableSetOf()) { it.scanner.name }
}
```

**Review by fviernau — DISMISSED** [review]

**Review by fviernau — DISMISSED** [review]

**Review by mnonnenmacher — DISMISSED** [review]

**Review by fviernau — DISMISSED** [review]

**Review by fviernau — APPROVED** [review]
