### PR TITLE
Bugfix: Handle list-format sources in conandata.yml

### LINKED ISSUE #11685: Conan 2 conanfile format changed and cant be read anymore
## Describe the bug

When scanning our recent conan projects we get the following error:

```
05:12:26.315 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.PackageManager - Conan failed to resolve dependencies for path 'conanfile.py': IncorrectTypeException: Expected element to be YamlMap but is YamlList
```

This happens regardless of having a conanfile.py or conanfile.txt

## To Reproduce

Scanning a Conan 2 Project. We are using the official ORT Docker container

## Expected behavior

No Error and therefore found packages

## Environment

* ORT version: [83.1.0]
* OS: [Linux]

### PR DESCRIPTION
**Pull request by FabianRolfMatthiasNoll**
Closes #11685 

Some Conan recipes bundle multiple tarballs and list them under the version key. The previous code threw an `IncorrectTypeException` in that case. Fix this by dispatching on the YAML node type and log a warning when multiple archives are present, since ORT supports only a single source artifact per package.

### CODE REVIEW

**Comment by FabianRolfMatthiasNoll** [comment]
The funTest Jobs seem to have failed because of internal errors if i see that correctly.

**Comment by sschuberth** [comment]
Thanks for the PR @FabianRolfMatthiasNoll! However, as it doesn't first refactor the existing code to use data-class-based deserialization as proposed [here](https://github.com/oss-review-toolkit/ort/issues/11685#issuecomment-4265874694), it's now becoming more complex it will probably take longer to review.

File: plugins/package-managers/conan/src/main/kotlin/Conan.kt [hunk 1]
```diff
@@ -319,15 +318,26 @@ class Conan(
...
+        if (conanData.sources.size > 1) {
+            logger.warn {
+                "Package has ${conanData.sources.size} source archives (Format B / multiple assets). " +
+                    "Only the first archive will be used: ${conanData.sources.first().url}. " +
+                    "The following archives are ignored: " +
+                    conanData.sources.drop(1).joinToString { it.url }
+            }
+        }
+
+        val entry = conanData.sources.first()
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/main/kotlin/Conan.kt]: I believe this `first` logic should not go into this function, but the caller of the function should be responsible for picking the "right" `RemoteArtifact`. So this function itself should already be prepared for handling multiple sources.

File: plugins/package-managers/conan/src/main/kotlin/Conan.kt [hunk 2]
```diff
@@ -319,15 +318,26 @@ class Conan(
     }
 
     /**
-     * Return the source artifact contained in [conanData], or [RemoteArtifact.EMPTY] if no source artifact is
-     * available.
+     * Return the source artifacts contained in [conanData]. For packages with a single source archive (Format A),
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/main/kotlin/Conan.kt]: Are "Format A" and "Format B" official names? If not, are there official names (or versions) for the different formats that we could use here?

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt [hunk 3]
```diff
@@ -0,0 +1,114 @@
+/*
+ * Copyright (C) 2025 The ORT Project Copyright Holders <https://github.com/oss-review-toolkit/ort/blob/main/NOTICE>
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: This should say "2026".

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt [hunk 4]
```diff
@@ -0,0 +1,114 @@
...
+                    sha256: b1bfedcd5b289ff22aee87c9d600f515767ebf45f77168cb6d64f231f518a82e
+                    url: https://github.com/openssl/openssl/releases/download/openssl-3.6.1/openssl-3.6.1.tar.gz
+            """.trimIndent()
+
+            val conanData = parseConanDataYaml(yaml, "3.6.1")
+
+            conanData.sources shouldHaveSize 1
+            conanData.sources[0].url shouldBe
+                "https://github.com/openssl/openssl/releases/download/openssl-3.6.1/openssl-3.6.1.tar.gz"
+            conanData.sources[0].sha256 shouldBe "b1bfedcd5b289ff22aee87c9d600f515767ebf45f77168cb6d64f231f518a82e"
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: Prefer:

```kotlin
            conanData.sources.shouldBeSingleton {
                it.url shouldBe
                    "https://github.com/openssl/openssl/releases/download/openssl-3.6.1/openssl-3.6.1.tar.gz"
                it.sha256 shouldBe "b1bfedcd5b289ff22aee87c9d600f515767ebf45f77168cb6d64f231f518a82e"
            }
```

Similar below.

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt [hunk 5]
```diff
@@ -0,0 +1,114 @@
...
+            conanData.hasPatches shouldBe false
+        }
+
+        "parse a multi-source list (Format B) without throwing" {
+            val conanDataFile = File("src/test/assets/conandata-libselinux-3.6.yml")
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: Prefer `getAssetFile()`. Similar below.

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+            val yaml = """
+                sources:
+                  3.6.1:
+                    sha256: abc
+                    url: https://example.com/pkg-3.6.1.tar.gz
+            """.trimIndent()
+
+            val conanData = parseConanDataYaml(yaml, "9.9.9")
+
+            conanData.sources shouldHaveSize 0
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: Prefer `should beEmpty()`. Similar below.

File: plugins/package-managers/conan/build.gradle.kts [hunk 7]
```diff
@@ -43,4 +43,6 @@ dependencies {
 
     funTestImplementation(projects.utils.testUtils)
     funTestImplementation(testFixtures(projects.analyzer))
+
+    testImplementation(testFixtures(projects.analyzer))
```
Comment (sschuberth) [inline plugins/package-managers/conan/build.gradle.kts]: Why's that needed? I don't see any imports from that project in the test.

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: plugins/package-managers/conan/src/main/kotlin/Conan.kt (hunk 2 above)
Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/main/kotlin/Conan.kt]: No there are no official names that i could find and tried defining it somehow. But i guess just calling it single source and mult source list or something would fit better when referenced

Comment (sschuberth) [reply plugins/package-managers/conan/src/main/kotlin/Conan.kt]: Yes, I agree that would be better.

**Comment by FabianRolfMatthiasNoll** [comment]
Sorry i didnt want to pressure i was checking this PR and clicked stupidly on the button :) So no stress here sorry :)

**Comment by sschuberth** [comment]
> Sorry i didnt want to pressure i was checking this PR and clicked stupidly on the button :) So no stress here sorry :)

Re-requesting a review is fine (and actually encouraged in our contribution workflow) if you want reviewers to take another look. But please, put 👍🏻 under each review comment that you've addressed (but not mark them as resolved; that's for the reviewer to judge).

And also please rebase your PR onto latest `main` to benefit from some test fixes.

File: plugins/package-managers/conan/src/main/kotlin/Conan.kt [hunk 8]
```diff
@@ -349,42 +346,74 @@
...
+    val patchesForVersion = root.get<YamlMap>("patches")?.get<YamlList>(version)
+    val hasPatches = !patchesForVersion?.items.isNullOrEmpty()
 
-        val url = sourceForVersion?.get<YamlNode>("url")?.let {
-            when {
-                it is YamlList -> it.yamlList.items.firstOrNull()?.yamlScalar?.content
-                else -> it.yamlScalar.content
-            }
-        }
+    val sourcesForVersion = root.get<YamlMap>("sources")?.get<YamlNode>(version)
```
[the remark this answers is not in the document]
Comment (sschuberth) [reply plugins/package-managers/conan/src/main/kotlin/Conan.kt]: For readability, I'm fine to keep it as-is.

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+
+            val conanData = parseConanDataYaml(conanDataFile.readText(), "3.6")
+
+            conanData.sources[0].url shouldBe
+                "https://github.com/SELinuxProject/selinux/releases/download/3.6/libselinux-3.6.tar.gz"
+            conanData.sources[0].sha256 shouldBe "ba4e0ef34b270e7672a5e5f1b523fe2beab3a40bb33d9389f4ad3a8728f21b52"
+            conanData.sources[1].url shouldBe
+                "https://github.com/SELinuxProject/selinux/releases/download/3.6/libsepol-3.6.tar.gz"
+            conanData.sources[1].sha256 shouldBe "c9dc585ea94903d784d597c861cd5dce6459168f95e22b31a0eab1cdd800975a"
+        }
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: These tests use the same `conanData` and should be combined into

```kotlin
            conanData.sources should containExactly(
                ConanSourceEntry(
                    url = "https://github.com/SELinuxProject/selinux/releases/download/3.6/libselinux-3.6.tar.gz",
                    sha256 = "ba4e0ef34b270e7672a5e5f1b523fe2beab3a40bb33d9389f4ad3a8728f21b52"
                ),
                ConanSourceEntry(
                    url = "https://github.com/SELinuxProject/selinux/releases/download/3.6/libsepol-3.6.tar.gz",
                    sha256 = "c9dc585ea94903d784d597c861cd5dce6459168f95e22b31a0eab1cdd800975a"
                )
            )
```

Please judge for yourself whether `containExactly` is the desired matcher, or whether e.g. `containExactlyInAnyOrder` should be used instead.

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+
+        "detect patches alongside a multi-source list" {
+            val conanDataFile = getAssetFile("conandata-libselinux-3.6.yml")
+
+            val conanData = parseConanDataYaml(conanDataFile.readText(), "3.6")
+
+            conanData.hasPatches shouldBe true
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/test/kotlin/ConanTest.kt:69]: This line should also be merged into the above test. There is no need to have separate tests for each assertion.

Of course, the test name should be generalized accordingly, if needed.

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+            val conanDataFile = getAssetFile("conandata-libselinux-3.6.yml")
+            val conanData = parseConanDataYaml(conanDataFile.readText(), "3.6")
+
+            val artifacts = conan.parseSourceArtifacts(conanData)
+
+            artifacts shouldHaveSize 2
+            artifacts[0].url shouldBe
+                "https://github.com/SELinuxProject/selinux/releases/download/3.6/libselinux-3.6.tar.gz"
+            artifacts[0].hash.algorithm shouldBe HashAlgorithm.SHA256
+            artifacts[0].hash.value shouldBe "ba4e0ef34b270e7672a5e5f1b523fe2beab3a40bb33d9389f4ad3a8728f21b52"
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: This could be simplified a bit into

```kotlin
            with(artifacts.first()) {
                url shouldBe "https://github.com/SELinuxProject/selinux/releases/download/3.6/libselinux-3.6.tar.gz"
                hash.algorithm shouldBe HashAlgorithm.SHA256
                hash.value shouldBe "ba4e0ef34b270e7672a5e5f1b523fe2beab3a40bb33d9389f4ad3a8728f21b52"
            }
```

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt (hunk 9 above)
Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: Yeah that definitely makes sense

File: plugins/package-managers/conan/src/test/kotlin/ConanTest.kt (hunk 11 above)
Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/test/kotlin/ConanTest.kt]: way better readability will do

**Comment by sschuberth** [comment]
@FabianRolfMatthiasNoll, please squash the hunks from the last commit into that commit of this PR that introduces the actual code.

Background: We do not allow "fixup commits" to be made _within_ the PR that introduces the code to be fixed up. Instead, all review comments should get addressed in the relevant commit directly, to make a single PR a "perfect recipe". This also helps reviewers that review commit-by-commit, as otherwise there is a risk to comment on stuff that gets addressed in a later commit.

**Review by sschuberth — DISMISSED** [review]

**Review by sschuberth — APPROVED** [review]
