### PR TITLE
fix(analyzer): Add a test for dangling embed directives / GoMod

### LINKED ISSUE #5560: GoMod: go list -deps error: no matching files found
Hey,

We have an issue with the GoMod Package Manager

```
10:35:45.499 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.managers.GoMod - Resolving GoMod dependencies for path 'go.mod' failed with: 
IOException: Running 'go list -deps -f {{with .Module}}{{.Path}} {{.Version}}{{end}} ./...' in '/builds/some-go-app' failed with exit code 1:
XXXXXX.go:10:12: pattern some.file: no matching files found
```

Content of XXXXXX.go
```go
//go:generate cp ../../../some.file .
//go:embed some.file
```
some.file ist generated during build of another component in the project.

We don't want to run "go generate/go build" as a prequisite for ort. So, are there other ways to get this working?

Cheers,
Marco

### PR DESCRIPTION
**Pull request by fviernau**
The `GoMod` integration does not execute `go generate/go build`, so the embed directive in `main.go` points to a non-existing file. When `GoMod` executes [1] it failed [2] with the previously used Go version 1.20.5. As of [3], with Go version 1.21.1, that issue is fixed.

Add a test to ensure it keeps on working.

Note: It is essential to pass `json=Module` instead of not just
      `-json` [4], because otherwise the issue would still persist on
      Go 1.21.1.

Fixes #5560.

[1] `go list -deps -json=Module -buildvcs=false ./...`
[2] `pattern file.txt: no matching`
[3] 47e45202a2cd04396fe929b8ac856c98f1b94649
[4] 43ad3a777c6b4f59c487faf255ca590e7d48822d

Please ensure that your pull request adheres to our [contribution guidelines](https://github.com/oss-review-toolkit/.github/blob/main/CONTRIBUTING.md). Thank you!

### CODE REVIEW

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 1]
```diff
@@ -100,7 +100,7 @@ class GoMod(
 
     override fun transformVersion(output: String) = output.removePrefix("go version go").substringBefore(' ')
 
-    override fun getVersionRequirement(): RangesList = RangesListFactory.create(">=1.19.0")
+    override fun getVersionRequirement(): RangesList = RangesListFactory.create(">=1.21.1")
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt:103]: Commit message:
- "this projects" -> "the projects"

File: analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod [hunk 2]
```diff
@@ -0,0 +1,3 @@
+module gomod_dangling_embed
+
+go 1.19
```
Comment (sschuberth) [inline analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod:3]: Shouldn't this also be 1.21.1?

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod (hunk 2 above)
Comment (fviernau) [reply analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod:3]: Why exactly should it be? (As-is it is consistent with the other test cases in `GoModFunTest`).

One aspect of the bug fix is in the tooling of version 1.21, but that tooling can be used with 1.19 projects, so I do not see an issue here.

Comment (sschuberth) [reply analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod:3]: > One aspect of the bug fix is in the tooling of version 1.21, but that tooling can be used with 1.19 projects

That was the missing piece of information for me here.

**Comment by sschuberth** [comment]
Note that *commit-lint* still fails.

File: analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod (hunk 2 above)
Comment (fviernau) [reply analyzer/src/funTest/assets/projects/synthetic/gomod-dangling-embed/go.mod:3]: > That was the missing piece of information for me here.

Ok, so are we good to go?

**Comment by fviernau** [comment]
> Note that _commit-lint_ still fails.

It seems it flag references to issues in the middle of a sentence without a preceding keyword like "Fixes".

**Comment by sschuberth** [comment]
> My work around is to use a reference e.g. [5].

That's as well the only work-around I'm aware of.
