### PR TITLE
Git: Work around an issue with downloading submodules via Git protocol

### LINKED ISSUE #5899: Scanner: Runs into `NoSuchElementException`
While scanning ORT with ORT I noticed that ORT exits scanning with the following exception:

```
Exception in thread "main" java.util.NoSuchElementException: Key RepositoryProvenance(vcsInfo=VcsInfo(type=Git, url=https://github.com/square/okhttp.git, revision=parent-3.10.0, path=), resolvedRevision=c0739a419949a24d0c34cf38a25953c60871268b) is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.buildNestedProvenanceScanResult(ScanController.kt:280)
	at org.ossreviewtoolkit.scanner.experimental.ScanController.getNestedScanResultsByPackage(ScanController.kt:170)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner.scan(ExperimentalScanner.kt:158)
	at org.ossreviewtoolkit.scanner.experimental.ExperimentalScanner$scan$4.invokeSuspend(ExperimentalScanner.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.runExperimental(ScannerCommand.kt:373)
	at org.ossreviewtoolkit.cli.commands.ScannerCommand.run(ScannerCommand.kt:250)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.cli.OrtMainKt.main(OrtMain.kt:83)
```

### PR DESCRIPTION
**Pull request by fviernau**
Several VCS hosts including GitHub have disabled the use of the
unauthenticated Git protocol, see e.g. [1]. So,
`Git.updateSubmodules()` fails when run with `recursive=true` if at
least one submodule uses the Git protocol blocked by the respective
VCS host.

As result, the experimental scanner fails cloning recursively and
crashes, see [2]. Also the downloader is not capable of cloning
repositories recursively if any of its submodules exhibits that issue.

Work around that by instructing git to re-write the submodule
repository URLs to use `https` instead of `git` as protocol.

[1] https://github.com/heroku/heroku-buildpack-nodejs/issues/959
[2] https://github.com/oss-review-toolkit/ort/issues/5899

Fixes #5899.

### CODE REVIEW

File: downloader/src/main/kotlin/vcs/GitWorkingTree.kt [hunk 1]
```diff
@@ -94,7 +98,21 @@ open class GitWorkingTree(workingDir: File, vcsType: VcsType) : WorkingTree(work
             listSubmodulePaths(it).associateWith { path ->
                 GitWorkingTree(it.workTree.resolve(path), vcsType).getInfo()
             }
+        }.mapValues { it.value.replaceUrlPrefixes() }
+
+    private fun VcsInfo.replaceUrlPrefixes(): VcsInfo {
+        val patchedUrl = repositoryUrlPrefixReplacements.entries.fold(url) { cur, (prefix, replacement) ->
```
Comment (sschuberth) [inline downloader/src/main/kotlin/vcs/GitWorkingTree.kt:104]: Nit: May `url` instead of `cur`?

**Review by sschuberth — CHANGES_REQUESTED** [review]
General question to @oss-review-toolkit/core-devs: Should we maybe only do this if the host is GitHub?

File: downloader/src/main/kotlin/vcs/GitWorkingTree.kt [hunk 2]
```diff
@@ -94,8 +98,18 @@ open class GitWorkingTree(workingDir: File, vcsType: VcsType) : WorkingTree(work
             listSubmodulePaths(it).associateWith { path ->
                 GitWorkingTree(it.workTree.resolve(path), vcsType).getInfo()
             }
+        }.mapValues { it.value.replaceUrlPrefixes() }
+
+    private fun VcsInfo.replaceUrlPrefixes(): VcsInfo {
+        val patchedUrl = repositoryUrlPrefixReplacements.entries.fold(url) { url, (prefix, replacement) ->
+            if (url.startsWith(prefix)) {
+                "$replacement${url.removePrefix(prefix)}"
+            } else url
```
Comment (sschuberth) [inline downloader/src/main/kotlin/vcs/GitWorkingTree.kt:107]: Sorry for not noticing earlier, but this could also be

    url.withoutPrefix(prefix)?.let { "$replacement$it" } ?: url

**Comment by sschuberth** [comment]
> General question to @oss-review-toolkit/core-devs: Should we maybe only do this if the host is GitHub?

I gave this some thought, and I believe it to be very unlikely that any Git servers out there support `git://` but not `https://`, so I guess it's safe enough to do this generally, and not only for GitHub.

File: downloader/src/main/kotlin/vcs/GitWorkingTree.kt (hunk 2 above)
Comment (sschuberth) [reply downloader/src/main/kotlin/vcs/GitWorkingTree.kt:107]: This is optional, though, and I'll approve anyway.

**Review by sschuberth — APPROVED** [review]
