### PR TITLE
Subversion: Add authentication support via the Java Authenticator

### LINKED ISSUE #3301: Subversion checkout does not work for repositiories that require authentication
My scanner cannot checkout from a private SVN repo although I'm using the latest ORT version and I have set the `ORT_HTTP_USERNAME` and `ORT_HTTP_PASSWORD` environment variables.

I have added an extra info log at the beginning of the `OrtAuthenticator#getPasswordAuthentication` but I do not see it in the logs so I assume the method is not called a all. I do see the "Authenticator is already installed" message.

The auth error is:
```
"Caused by: SVNAuthenticationException: svn: E170001: Authentication required for '<http://my-repo.domain.com> Subversion Repository'".
```

Note that I have tried using a .netrc file as well but with no luck.

The `OrtSVNAuthenticationManager` class (see `Subversion.kt`) sets the `username` and `password` properties to `null` and does not seem to care about the environment variables or the `.netrc` file.

When I set username and password to the desired values in the `OrtSVNAuthenticationManager` class, the SVN checkout would work as expected.

### PR DESCRIPTION
**Pull request by sschuberth**
Fixes #3301.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

File: downloader/src/main/kotlin/vcs/Subversion.kt [hunk 1]
```diff
@@ -245,6 +251,37 @@ private class OrtSVNAuthenticationManager : DefaultSVNAuthenticationManager(
...
+                previousAuth: SVNAuthentication?,
+                authMayBeStored: Boolean
+            ): SVNAuthentication? {
+                val url = URL(svnurl.toDecodedString())
+
+                val auth = ortAuthenticator?.requestPasswordAuthenticationInstance(
+                    svnurl.host, null, svnurl.port, svnurl.protocol, null, null, url, Authenticator.RequestorType.SERVER
+                ) ?: return null
+
+                return SVNPasswordAuthentication.newInstance(
```
Comment (oheger-bosch) [inline downloader/src/main/kotlin/vcs/Subversion.kt:272]: Could this be made a single expression by using
 ```
?.let {  auth ->
  SVNPasswordAuthentication.newInstance( 
    auth.userName, auth.password, ...
  )
}
``` 
This would be more functional style, but maybe harder to grasp.

**Review by oheger-bosch — APPROVED** [review]

File: downloader/src/main/kotlin/vcs/Subversion.kt (hunk 1 above)
Comment (sschuberth) [reply downloader/src/main/kotlin/vcs/Subversion.kt:272]: Yes, and it also increases nesting / indentation a bit, which is usually something I usually try to avoid for clarity.
