### PR TITLE
GoMod: Do not filter out the main project package

### LINKED ISSUE #4139: GoMod: Expected exactly one unique package without version but got .
I'm trying to analyze a project which includes a Go module.

When running the analyzer, it outputs the following `ERROR`:

`Expected exactly one unique package without version but got .`

Which seems to indicate that the check in [this line](https://github.com/oss-review-toolkit/ort/blob/bd2494938a82843932738780ce27707900976334/analyzer/src/main/kotlin/managers/GoMod.kt#L101) failed.

<details>
  <summary>(partial) stacktrace</summary>

```
07:57:48 07:57:48.475 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.ProcessCapture - Running 'go mod vendor -v' in '/workspace/project/project'...
07:57:48 java.lang.IllegalArgumentException: Expected exactly one unique package without version but got .
07:57:48 	at org.ossreviewtoolkit.analyzer.managers.GoMod.resolveDependencies(GoMod.kt:101)
07:57:48 	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:237)
07:57:48 	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$1$1$1.invokeSuspend(Analyzer.kt:122)
07:57:48 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
07:57:48 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
07:57:48 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
07:57:48 07:57:48.623 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.OrtAuthenticator - Authenticator is already installed.
07:57:48 07:57:48.624 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.utils.OrtProxySelector - Proxy selector is already installed.
07:57:49 07:57:48.859 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.managers.GoMod - Resolving GoMod dependencies for 'project/go.mod' failed with: IllegalArgumentException: Expected exactly one unique package without version but got .
```
</details>

The reason seems to be that we filter out the root package of the project [a few lines before](https://github.com/oss-review-toolkit/ort/blob/bd2494938a82843932738780ce27707900976334/analyzer/src/main/kotlin/managers/GoMod.kt#L97) because the `go mod why` output contains the following:
```
# myproject.com/project
(main module does not need package myproject.com/project)
```
<details>
  <summary>Full `go mod why` output</summary>

 ```console
> go mod why myproject.com/project github.com/fsnotify/fsnotify github.com/go-playground/validator/v10 github.com/go-test/deep github.com/google/uuid github.com/sirupsen/logrus github.com/stretchr/testify github.com/davecgh/go-spew github.com/pmezard/go-difflib github.com/stretchr/testify golang.org/x/sys golang.org/x/sys github.com/davecgh/go-spew github.com/stretchr/objx gopkg.in/yaml.v2 gopkg.in/check.v1 github.com/go-playground/assert/v2 github.com/go-playground/locales github.com/go-playground/universal-translator github.com/leodido/go-urn golang.org/x/crypto golang.org/x/net golang.org/x/sys golang.org/x/crypto golang.org/x/text golang.org/x/sys golang.org/x/text golang.org/x/tools
# myproject.com/project
(main module does not need package myproject.com/project)

# github.com/fsnotify/fsnotify
myproject.com/project/internal/config
github.com/fsnotify/fsnotify

# github.com/go-playground/validator/v10
myproject.com/project/internal/config
github.com/go-playground/validator/v10

# github.com/go-test/deep
myproject.com/project/internal/config
github.com/go-test/deep

# github.com/google/uuid
myproject.com/project/internal/project
myproject.com/project/internal/project.test
github.com/google/uuid

# github.com/sirupsen/logrus
myproject.com/project/cmd/cli
github.com/sirupsen/logrus

# github.com/stretchr/testify
(main module does not need package github.com/stretchr/testify)

# github.com/davecgh/go-spew
(main module does not need package github.com/davecgh/go-spew)

# github.com/pmezard/go-difflib
(main module does not need package github.com/pmezard/go-difflib)

# github.com/stretchr/testify
(main module does not need package github.com/stretchr/testify)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# github.com/davecgh/go-spew
(main module does not need package github.com/davecgh/go-spew)

# github.com/stretchr/objx
(main module does not need package github.com/stretchr/objx)

# gopkg.in/yaml.v2
myproject.com/project/internal/config
myproject.com/project/internal/config.test
github.com/stretchr/testify/assert
gopkg.in/yaml.v2

# gopkg.in/check.v1
myproject.com/project/internal/config
myproject.com/project/internal/config.test
github.com/stretchr/testify/assert
gopkg.in/yaml.v2
gopkg.in/yaml.v2.test
gopkg.in/check.v1

# github.com/go-playground/assert/v2
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/go-playground/validator/v10.test
github.com/go-playground/assert/v2

# github.com/go-playground/locales
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/go-playground/universal-translator
github.com/go-playground/locales

# github.com/go-playground/universal-translator
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/go-playground/universal-translator

# github.com/leodido/go-urn
myproject.com/project/internal/config
github.com/go-playground/validator/v10
github.com/leodido/go-urn

# golang.org/x/crypto
(main module does not need package golang.org/x/crypto)

# golang.org/x/net
(main module does not need package golang.org/x/net)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# golang.org/x/crypto
(main module does not need package golang.org/x/crypto)

# golang.org/x/text
(main module does not need package golang.org/x/text)

# golang.org/x/sys
(main module does not need package golang.org/x/sys)

# golang.org/x/text
(main module does not need package golang.org/x/text)

# golang.org/x/tools
(main module does not need package golang.org/x/tools)
```
</details>

That's because the root package doesn't contain any code by itself.
The code is split into sub-packages in  `cmd`, `internal` and `pkg` as demonstrated by https://github.com/golang-standards/project-layout

### PR DESCRIPTION
**Pull request by oheger-bosch**
This is a fix for a regression introduced in f2793cd. If the project's
root package does not contain any source code, it is reported to be
unused by "go mod why", and was therefore filtered out. This caused
an exception later because the project identifier could not be
determined.

Fix this by ensuring that the project package is always included in
the dependency graph.

Resolves #4139.

### CODE REVIEW

File: analyzer/src/main/kotlin/managers/GoMod.kt [hunk 1]
```diff
@@ -282,6 +279,19 @@ private class Graph(private val nodeMap: MutableMap<Identifier, Set<Identifier>>
...
+     * Search for the single package that represents the main project. This is the only package without a version.
+     * Fail if no single package with this criterion can be found.
+     */
+    fun projectId(): Identifier =
+        nodes().filter { it.version.isBlank() }.let { idsWithoutVersion ->
+            require(idsWithoutVersion.size == 1) {
+                "Expected exactly one unique package without version but got ${idsWithoutVersion.joinToString()}."
+            }
+
+            idsWithoutVersion.first()
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/GoMod.kt:292]: Just out of curiosity, are you deliberately not using `idsWithoutVersion.single()` here because you want to customize the exception message?

Comment (oheger-bosch) [reply analyzer/src/main/kotlin/managers/GoMod.kt:292]: This was the original way this check was implemented before my changes. So I just restored it.

**Review by sschuberth — APPROVED** [review]

File: analyzer/src/funTest/kotlin/managers/GoModFunTest.kt [hunk 2]
```diff
@@ -32,13 +32,34 @@ import org.ossreviewtoolkit.utils.test.USER_DIR
...
+                url = normalizeVcsUrl(vcsUrl)
+            )
+
+            val result = createGoMod().resolveSingleProject(definitionFile)
+
+            result.toYaml() shouldBe expectedResult
+        }
+
+        "Project dependencies are detected correctly if the main package does not contain any code" {
+            val projectDir = testDir.resolve("gomod-subpkg")
```
Comment (fviernau) [inline analyzer/src/funTest/kotlin/managers/GoModFunTest.kt:59]: Would it make sense to only assert that the main package is included? (or make it in any other way more obvious which package the "main" one is?

**Review by fviernau — CHANGES_REQUESTED** [review]

**Review by fviernau — APPROVED** [review]

File: analyzer/src/funTest/kotlin/managers/GoModFunTest.kt (hunk 2 above)
Comment (oheger-bosch) [reply analyzer/src/funTest/kotlin/managers/GoModFunTest.kt:59]: Do you mean the test should not check the whole result, but only if the result contains this main package? Then it should probably also be renamed to something like "The main package is not removed if it does not contain any code".

Comment (fviernau) [reply analyzer/src/funTest/kotlin/managers/GoModFunTest.kt:59]: Hm, thinking again - I believe it's just fine as-is.
