### PR TITLE
fix(node): Ignore dangling linked dependencies

### LINKED ISSUE #10618: Yarn: NoSuchElementException: Key @vector-im/matrix-wysiwyg-wasm@link:.cache/yarn/v6/npm- is missing in the map.
### Describe the bug

License scanning fails in one of our projects with the following error message:

```
Yarn failed to resolve dependencies for path 'package.json': NoSuchElementException: Key @vector-im/matrix-wysiwyg-wasm@link:.cache/yarn/v6/npm- is missing in the map.
```

The cause is the dependency @vector-im/matrix-wysiwyg, which links WebAssembly bindings locally. Excerpt from the dependency's [package.json](https://github.com/element-hq/matrix-rich-text-editor/blob/2.38.3/platforms/web/package.json):
```
"dependencies": {
"@vector-im/matrix-wysiwyg-wasm": "link:../../bindings/wysiwyg-wasm"
}
```

This results in the generated yarn.lock pointing to Yarn's cache (the path depends on the machine on which the lock file is generated). was):

`@vector-im/matrix-wysiwyg-wasm@link:../../../.cache/yarn/v6/npm-@vector-im-matrix-wysiwyg-2.38.3-cc54d8b3e9472bcd8e622126ba364ee31952cd8a-integrity/node_modules/bindings/wysiwyg-wasm`

The OSS Review Toolkit analyzer cannot resolve the dependency and aborts.

### Environment

* ORT version: 62.2.0

### PR DESCRIPTION
**Pull request by fviernau**
`Yarn.kt` lacks support for linked dependencies. A special case for linked dependencies is when a node module generates another bundled package during install times and refers to it as "linked" dependency. That generate for unknown reason might not take place, so the path to the directory where the linked dependency should reside is a dangling reference. Simply ignore such dangling reference to avoid that the entire analysis fails running into a NoSuchElementException in the `Map.getValue()` call within `resolveVersions()`. While this adds some fault tolerance, it does not implement general support for linked dependencies.

Note: In the case of the function test, the package to be generated are
      Rust bindings.

Fixes #10618.

### CODE REVIEW

**Comment by sschuberth** [comment]
Commit message comments:

> `Yarn.kt` lacks support for linked dependencies.

Can this statement be backed-up with some reference link? Maybe even a link that explains what "linked dependencies" generally are?

> That generate for unknown reason might not take place, so the path

Maybe: "As that generation might not happen in some cases, the path"

Maybe: Put `NoSuchElementException` in backticks.

File: plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt [hunk 1]
```diff
@@ -211,10 +211,20 @@ private fun getNonDeduplicatedModuleInfosForId(moduleInfos: Collection<YarnListN
 private data class ModuleReference(
     val alias: String?,
     val name: String,
-    val version: String
+    val version: String,
+    val linkPath: String?
 )
 
 private val YarnListNode.moduleReference: ModuleReference get() {
+    if (name.contains("@link:")) {
```
Comment (sschuberth) [inline plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt]: Prefer Kotlin's `in` operator.

**Review by sschuberth — CHANGES_REQUESTED** [review]

**Comment by sschuberth** [comment]
Commit message nit:

> example [1]..

Double `.` at the end.

File: plugins/package-managers/node/src/funTest/kotlin/yarn/YarnFunTest.kt [hunk 2]
```diff
@@ -92,4 +92,15 @@ class YarnFunTest : StringSpec({
 
         result.toYaml() should matchExpectedResult(expectedResultFile, definitionFile)
     }
+
+    "Resolve bundled dependencies" {
```
Comment (sschuberth) [inline plugins/package-managers/node/src/funTest/kotlin/yarn/YarnFunTest.kt]: I'm a bit confused about the test / test title: Does this now test for
1. the feature to handle bundled dependencies, or
2. the feature to handle linked dependencies, or
3. the feature to handle dangling references for either of the above?

Comment (fviernau) [reply plugins/package-managers/node/src/funTest/kotlin/yarn/YarnFunTest.kt]: I've adjusted it for bullet point 3. above.

File: plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt [hunk 3]
```diff
@@ -235,6 +246,15 @@ internal val YarnListNode.moduleName: String get() = moduleReference.name
 
 internal val YarnListNode.moduleVersion: String get() = moduleReference.version
 
+internal val YarnListNode.linkPath: String? get() = moduleReference.linkPath
+
+private fun List<YarnListNode>.removeDanglingLinks(workingDir: File): List<YarnListNode> =
+    map {
+        it.copy(children = it.children?.removeDanglingLinks(workingDir))
+    }.filterNot { node ->
+        node.linkPath?.let { workingDir.resolve(it).isDirectory } ?: false
```
Comment (sschuberth) [inline plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt:255]: Optional nit: Maybe change to

    node.linkPath?.let { workingDir.resolve(it) }?.isDirectory ?: false

to make `let` only do the mapping to an absolute directory, and to highlight that `false` somewhat belongs to the `isDirectory` boolean.

Comment (fviernau) [reply plugins/package-managers/node/src/main/kotlin/yarn/Yarn.kt:255]: I've addressed this with https://github.com/oss-review-toolkit/ort/pull/10645
