### PR TITLE
downloader: Return a Result object from updateWorkingTree()

### LINKED ISSUE #3952: Provide more information when VCS download fails
The [`updateWorkingTree`](https://github.com/oss-review-toolkit/ort/blob/ce30534806361486097700fb0c0fbab611a2d239/downloader/src/main/kotlin/VersionControlSystem.kt#L308) function only returns a `Boolean` to describe if the update was successful or not. If it fails, the actual errors get only written to the logs. For example, if Git fails to checkout a revision because it does not exist, this error is written to the logs, but will not be visible in the result files and reports, these will only contain a generic error message.

This makes the investigation of VCS download issues unnecessarily hard. It could be improved by either throwing an exception in `updateWorking` that provides more details in the message, or by returning a result object with more information instead of a `Boolean`.

### PR DESCRIPTION
**Pull request by sschuberth**
Instead of just a Boolean, return a Result object encapsulating the
originally requested revsion for convenience, or any occurred exception.
This eases the debugging of download failures.

Resolves #3952.

Signed-off-by: Sebastian Schuberth <sebastian.schuberth@bosch.io>

### CODE REVIEW

File: downloader/src/main/kotlin/VersionControlSystem.kt [hunk 1]
```diff
@@ -283,11 +283,17 @@ abstract class VersionControlSystem {
...
-        } ?: throw DownloadException("$type failed to download from URL '${pkg.vcsProcessed.url}'.")
+        val results = mutableListOf<Result<String>>()
+
+        revisionCandidates.forEachIndexed { index, revision ->
+            log.info { "Trying revision candidate '$revision' (${index + 1} of ${revisionCandidates.size})..." }
+            results += updateWorkingTree(workingTree, revision, pkg.vcsProcessed.path, recursive)
+            if (results.last().isSuccess) return@forEachIndexed
+        }
+
+        val workingTreeRevision = results.last().getOrElse {
```
Comment (fviernau) [inline downloader/src/main/kotlin/VersionControlSystem.kt:294]: I believe that in case `results.last() is Failure == true` the handling is now missing and needs to be added.

File: downloader/src/main/kotlin/vcs/GitRepo.kt [hunk 2]
```diff
@@ -189,17 +189,15 @@ class GitRepo : VersionControlSystem(), CommandLineTool {
             runRepo(workingTree.workingDir, *syncArgs.toTypedArray())
 
             log.debug { runRepo(workingTree.workingDir, "info").stdout }
-
-            true
-        } catch (e: IOException) {
-            e.showStackTrace()
+        }.onFailure {
+            it.showStackTrace()
```
Comment (fviernau) [inline downloader/src/main/kotlin/vcs/GitRepo.kt:193]: Consider renaming `it` to `e`, same above.

File: downloader/src/main/kotlin/vcs/Subversion.kt [hunk 3]
```diff
@@ -226,15 +226,15 @@ class Subversion : VersionControlSystem() {
             }
 
             true
-        } catch (e: SVNException) {
-            e.showStackTrace()
+        }.onFailure {
+            it.showStackTrace()
```
Comment (fviernau) [inline downloader/src/main/kotlin/vcs/Subversion.kt:230]: commit-msg: Would it make sense to mention that the DownloadExceptions are not changed?

**Review by fviernau — CHANGES_REQUESTED** [review]

File: downloader/src/main/kotlin/vcs/GitRepo.kt (hunk 2 above)
Comment (sschuberth) [reply downloader/src/main/kotlin/vcs/GitRepo.kt:193]: I actually thought about this when @oheger-bosch did a [similar change](https://github.com/oss-review-toolkit/ort/pull/3894/files#diff-439602bba9d79021802c46707b56c056fdb9f49373dac17ba938cdc4552605cdR88), but in exactly the opposite way: I tend to prefer `it` for rather simple code (esp. one-liners) where there's no clash with another (nested) `it`. For the special case of `runCatching` I tend to only use a named lambda parameter for `onFailure` if also done so for an `onSuccess`.

I *do* see a small point here to use `e` to keep the diff a bit smaller, but then again `e` is not much more telling than `it` anyway (`exception` would have been more telling). So I chose to stick to `it`.

But I'm open to get overruled here. Any opinion from @oheger-bosch?

File: downloader/src/main/kotlin/vcs/Subversion.kt (hunk 3 above)
Comment (sschuberth) [reply downloader/src/main/kotlin/vcs/Subversion.kt:230]: I'm not exactly sure what you're after, but doesn't "or any occurred exception" imply that?

File: downloader/src/main/kotlin/VersionControlSystem.kt (hunk 1 above)
Comment (sschuberth) [reply downloader/src/main/kotlin/VersionControlSystem.kt:294]: The "OrElse" part is what gets executed in that case.

Comment (fviernau) [reply downloader/src/main/kotlin/VersionControlSystem.kt:294]: If result contains more than zero elements and all elements are of the type `Failure`, then, you say, `orElse` gets executed?

File: downloader/src/main/kotlin/vcs/GitRepo.kt (hunk 2 above)
Comment (fviernau) [reply downloader/src/main/kotlin/vcs/GitRepo.kt:193]: I'm ok with `it`.

File: downloader/src/main/kotlin/vcs/Subversion.kt (hunk 3 above)
Comment (fviernau) [reply downloader/src/main/kotlin/vcs/Subversion.kt:230]: Right.

File: downloader/src/main/kotlin/VersionControlSystem.kt (hunk 1 above)
Comment (sschuberth) [reply downloader/src/main/kotlin/VersionControlSystem.kt:294]: Yes. But only the message of the last failure is included into the `DownloadException`.

What probably confuses you is that the `getOrElse` here is not the function on a collection, but the function on a `Result` object.

Comment (sschuberth) [reply downloader/src/main/kotlin/VersionControlSystem.kt:294]: And `results` cannot be empty as `revisionCandidates` is ensured to not be empty.

Comment (fviernau) [reply downloader/src/main/kotlin/VersionControlSystem.kt:294]: > What probably confuses you is that the getOrElse here is not the function on a collection, but the function on a Result object.

Argh, yes that was exactly what was confusing me. Thanks for pointing it out.

**Review by fviernau — APPROVED** [review]

File: downloader/src/main/kotlin/vcs/GitRepo.kt (hunk 2 above)
Comment (oheger-bosch) [reply downloader/src/main/kotlin/vcs/GitRepo.kt:193]: IMHO we should not be too dogmatic, but give the developers a certain freedom to follow their preferred style. I am fine with both.

File: downloader/src/main/kotlin/VersionControlSystem.kt [hunk 4]
```diff
@@ -283,11 +283,17 @@ abstract class VersionControlSystem {
...
+            throw DownloadException("$type failed to download from URL '${pkg.vcsProcessed.url}'.", it)
```
Comment (mnonnenmacher) [inline downloader/src/main/kotlin/VersionControlSystem.kt:295]: In the `if (revisionCandidates.isEmpty())` case we still don't propagate the exceptions that could have happened before (lines 233 and 253). I think it would be good to add them to the exception thrown in line 283 to completely address #3952 . Also I wonder if it is sufficient to figure out the problem to only propagate the last exception. But it probably is, at least I have no idea currently in which situation it wouldn't be.

**Review by mnonnenmacher — CHANGES_REQUESTED** [review]

File: downloader/src/main/kotlin/VersionControlSystem.kt (hunk 4 above)
Comment (sschuberth) [reply downloader/src/main/kotlin/VersionControlSystem.kt:295]: Issue #3952 specifically talks about `updateWorkingTree`, so that's what I was looking at, and the current changes already properly provide the "too long path" root cause I'm looking at in #4024. But let's see what I can do about the other exceptions...

Comment (mnonnenmacher) [reply downloader/src/main/kotlin/VersionControlSystem.kt:295]: Thanks.

**Review by mnonnenmacher — APPROVED** [review]
