### PR TITLE
fix(scancode): No ScanCode license texts in disclosure document

### LINKED ISSUE #8147: Cannot find ScanCode license texts in Docker image
ORT cannot find the ScanCode license texts in the Docker image:

```bash
$ docker run --rm ghcr.io/oss-review-toolkit/ort:13.0.0 requirements
[...]
ScanCode license texts not found.
```

The locations of the ScanCode binary and the license texts within the image are:
`/opt/python/shims/scancode`
`/opt/python/versions/3.11.5/lib/python3.11/site-packages/licensedcode/data/licenses`

The heuristic to find the license texts based on the path of the ScanCode binary fails for this:
https://github.com/oss-review-toolkit/ort/blob/f88041afc23b1950583efac0b396f41504e1c8ee/utils/spdx/src/main/kotlin/Utils.kt#L47-L54

### PR DESCRIPTION
**Pull request by wkl3nk**
Dump the ScanCode license texts to directory _/opt/scancode-license-data_ when creating the ORT docker container. Use this directory as fallback option if the ScanCode license texts cannot be located by the existing heuristic algorithm.

Fixes #8147.

### CODE REVIEW

File: utils/spdx/src/main/kotlin/Utils.kt [hunk 1]
```diff
@@ -49,7 +49,9 @@ val scanCodeLicenseTextDir by lazy {
     val pythonBinDir = listOf("bin", "Scripts")
     val scanCodeBaseDir = scanCodeExeDir?.takeUnless { it.name in pythonBinDir } ?: scanCodeExeDir?.parentFile
 
-    scanCodeBaseDir?.walkTopDown()?.find { it.isDirectory && it.endsWith("licensedcode/data/licenses") }
+    scanCodeBaseDir?.walkTopDown()?.find { it.isDirectory && it.endsWith("licensedcode/data/licenses") } ?:
+        // In cases where Python version management tools like Pyenv are used, the directory structure differs.
+        scanCodeBaseDir?.parentFile?.walkTopDown()?.find { it.isDirectory && it.endsWith("licensedcode/data/licenses") }
```
Comment (sschuberth) [inline utils/spdx/src/main/kotlin/Utils.kt:54]: As this would also search `scanCodeBaseDir` again, maybe even before other siblings are searched and thus wastes time to search something that has already been searched, I believe we should either

a. only search `scanCodeBaseDir?.parentFile`,
b. search `scanCodeBaseDir?.parentFile` as a fallback but exclude `scanCodeBaseDir` then,
c. look into a solution based on running the `scancode-license-data` command as mentioned [here](https://github.com/oss-review-toolkit/ort/issues/8147#issuecomment-1902743430).

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: utils/spdx/src/main/kotlin/Utils.kt (hunk 1 above)
Comment (sschuberth) [reply utils/spdx/src/main/kotlin/Utils.kt:54]: > c. look into a solution based on running the `scancode-license-data` command as mentioned [here](https://github.com/oss-review-toolkit/ort/issues/8147#issuecomment-1902743430).

I guess we can scratch this option due to https://github.com/aboutcode-org/scancode-toolkit/issues/4024.

Comment (sschuberth) [reply utils/spdx/src/main/kotlin/Utils.kt:54]: Ok, `scancode-license-data --path license-data` actually works to dump the data to the `license-data`. Theoretically, we could run this as part of the Docker build to put the data into a known location, and just add that known location to the paths to search here.

Comment (sschuberth) [reply utils/spdx/src/main/kotlin/Utils.kt:54]: And I'd propose to use `/opt/scancode-license-data` as that path.

Comment (wkl3nk) [reply utils/spdx/src/main/kotlin/Utils.kt]: @sschuberth I understand the reasoning behind the proposal to use the ScanCode script `scancode-license-data` to dump the license texts to a known location. But on the other side, I think we should go for a **quick bug fix first**, knowing there are potentially OSS Disclosure Documents out there that don't list the license texts and instead show grey empty boxes, potentially not fulfilling license obligations and getting people into trouble. A solution involving the `scancode-license-data` script would possibly also require to integrate this in the `ort requirements` command, would create new risks/errors that need to be handled during execution and so on. Can't we say _"let's do this quick bug fix to remove the compliance risks as fast as possible"_, and then do a more extensive solution in a future refactoring?

Comment (wkl3nk) [reply utils/spdx/src/main/kotlin/Utils.kt]: Adapted the heuristic search algorithm in a way that the `scanCodeBaseDir` is not searched twice.

Comment (sschuberth) [reply utils/spdx/src/main/kotlin/Utils.kt]: > I think we should go for a **quick bug fix first**

The bug report has been open for almost one year. I don't think that spending a few more hours on a cleaner fix makes a difference.

> A solution involving the `scancode-license-data` script would possibly also require to integrate this in the `ort requirements` command

I don't think so. As `ort requirements` just makes use of `scanCodeLicenseTextDir`, it would only be a matter of adding the hard-coded path as a fallback to the logic in there.

> would create new risks/errors that need to be handled during execution and so on.

I don't get what you mean. `scancode-license-data` would be executed at Docker build time, and `scanCodeLicenseTextDir` would be extended to also look in `/opt/scancode-license-data` as a fallback. That's it, if I'm not overlooking something.

> Can't we say _"let's do this quick bug fix to remove the compliance risks as fast as possible"_, and then do a more extensive solution in a future refactoring?

Again, what's your rationale why this is urgent *now* out of a sudden, after having the bug lingering around for one year?

Comment (wkl3nk) [reply utils/spdx/src/main/kotlin/Utils.kt]: Thanks for pointing out the alternative solution about provisioning a directory /opt/scan-code-license-data at Docker build time. I guess this is the best alternative.

File: Dockerfile [hunk 2]
```diff
@@ -157,6 +157,11 @@ RUN ARCH=$(arch | sed s/aarch64/arm64/) \
     rm requirements.txt; \
     fi
 
+# Extract ScanCode license texts to a directory
```
Comment (sschuberth) [inline Dockerfile:160]: Nit: Please end comment sentences with a dot. Similar below.

File: Dockerfile [hunk 3]
```diff
@@ -157,6 +157,11 @@ RUN ARCH=$(arch | sed s/aarch64/arm64/) \
...
+RUN scancode-license-data --path=/opt/scancode-license-data \
```
Comment (sschuberth) [inline Dockerfile:161]: Nit: `scancode-license-data --help` says to use `--path` without `=`, so I'd drop that here.

File: Dockerfile [hunk 4]
```diff
@@ -157,6 +157,11 @@ RUN ARCH=$(arch | sed s/aarch64/arm64/) \
...
+    && find /opt/scancode-license-data -type f ! -name "*.LICENSE" -exec rm -f {} + \
```
Comment (sschuberth) [inline Dockerfile:162]: Nit: Please use the more speaking `-not` instead of `!` (as the latter also has a special meaning in Bash).

**Review by sschuberth — CHANGES_REQUESTED** [review]

**Comment by sschuberth** [comment]
> fix(scancode): No ScanCode license texts in disclosure document

Also the commit message title should not be the one of the bug getting fixed, but say what's being done:

    fix(scancode): Ensure to find license texts in the Docker image

File: Dockerfile (hunk 4 above)
Comment (wkl3nk) [reply Dockerfile]: I had a second thought on it: If _scancode-license-data_ is the "API" way to access the license texts, then I don't want to put implementation-specific knowledge into the Dockerfile like what files I expect to be there, and which ones to delete. Because that might change over time, even without notice.

File: Dockerfile [hunk 5]
```diff
@@ -493,6 +499,9 @@ ENV GEM_HOME=/var/tmp/gem
 ENV PATH=$PATH:$RBENV_ROOT/bin:$RBENV_ROOT/shims:$RBENV_ROOT/plugins/ruby-install/bin
 COPY --from=ruby --chown=$USER:$USER $RBENV_ROOT $RBENV_ROOT
 
+# ScanCode license texts directory
+COPY --from=scancode-license-data --chown=$USER:$USER /opt/scancode-license-data /opt/scancode-license-data
```
Comment (sschuberth) [inline Dockerfile:503]: Why did you remove the previous removal of unneeded files? Can we maybe elegantly replace that with only copying `/opt/scancode-license-data/*.LICENSE` here?

File: Dockerfile [hunk 6]
```diff
@@ -493,6 +499,9 @@ ENV GEM_HOME=/var/tmp/gem
 ENV PATH=$PATH:$RBENV_ROOT/bin:$RBENV_ROOT/shims:$RBENV_ROOT/plugins/ruby-install/bin
 COPY --from=ruby --chown=$USER:$USER $RBENV_ROOT $RBENV_ROOT
 
+# ScanCode license texts directory
```
Comment (sschuberth) [inline Dockerfile:502]: Still missing a dot at the end of this sentence 😉

**Review by sschuberth — CHANGES_REQUESTED** [review]

File: Dockerfile (hunk 5 above)
Comment (sschuberth) [reply Dockerfile:503]: Ah, I missed [your comment](https://github.com/oss-review-toolkit/ort/pull/9622#discussion_r1891394271) as you already resolved / collapsed the conversation. So, still, what do you think about just copying needed files here?

File: Dockerfile (hunk 4 above)
Comment (sschuberth) [reply Dockerfile]: > If scancode-license-data is the "API" way to access the license texts

Well, the `scancode-license-data` command was originally designed to dump the data for a static website. In that sense, we're just "misusing" it here, and it's by-design that it does more than what we need.

Comment (sschuberth) [reply Dockerfile]: > Because that might change over time, even without notice.

True. But to guard against that, I was planning to make a follow-up change that runs `ort requirements` as part of the Docker image build, to fail if ORT cannot find any licenses. We already were doing that at some point, but apparently it got dropped during some Docker image build process refactoring.

File: Dockerfile (hunk 6 above)
Comment (wkl3nk) [reply Dockerfile:502]: This is not a sentence, because it has no verb :)

File: Dockerfile (hunk 5 above)
Comment (wkl3nk) [reply Dockerfile:503]: Copying the needed stuff is more complicated than expected, so I went back deleting the files we don't need.

File: Dockerfile (hunk 6 above)
Comment (wkl3nk) [reply Dockerfile]: Removed the comment completely, because it is rather obvious what is happening there.

File: Dockerfile (hunk 5 above)
Comment (sschuberth) [reply Dockerfile:503]: > Copying the needed stuff is more complicated than expected

Oh, interesting, mind sharing the details? Why does

    COPY --from=scancode-license-data --chown=$USER:$USER /opt/scancode-license-data/*.LICENSE /opt/scancode-license-data

not work?

> I went back deleting the files we don't need.

Unfortunately, that now seems to miss deleting the `static` directory, or?

Comment (sschuberth) [reply Dockerfile:503]: Ping @wkl3nk just in case you overlooked this comment.

**Review by sschuberth — APPROVED** [review]
