### PR TITLE
Bugfix conan 2 handler filters to strict

### LINKED ISSUE #11350: Conan 2 Handler filters out Header Libraries
## Describe the bug

The conan 2 handler has a filter build in which the conan 1 handler doesnt

```
 private fun parsePackages(pkgInfos: List<PackageInfoV2>): Map<String, Package> =
        // Package types are filtered because "conan graph info" return too many packages.
        pkgInfos.filter { it.packageType == PackageType.STATIC_LIBRARY }.associate { pkgInfo ->
            val pkg = parsePackage(pkgInfo)
            "${pkg.id.name}:${pkg.id.version}" to pkg
        }
```

This filters out any other type like HEADER_LIBRARY, SHARED_LIBRARY and whatever other interesting types there are. I dont know which packages are intended or not. But the conan 1 handler didnt have any filter at all:

```
    private fun parsePackages(pkgInfos: List<PackageInfoV1>, workingDir: File): Map<String, Package> =
        pkgInfos.associate { pkgInfo ->
            val pkg = parsePackage(pkgInfo, workingDir)
            "${pkg.id.name}:${pkg.id.version}" to pkg
        }
```

Given the following conanfile.txt
```
[requires]
fmt/10.2.1
cxxopts/3.2.0
spdlog/1.14.1
nlohmann_json/3.11.3
freetype/2.13.3
gtest/1.15.0
```
and the following produced conan.lock
```
{
    "version": "0.5",
    "requires": [
        "zlib/1.3.1#cac0f6daea041b0ccf42934163defb20%1765284699.337",
        "spdlog/1.14.1#0c58e5559d0409d1fadfc39f51393c11%1767604741.016",
        "nlohmann_json/3.11.3#45828be26eb619a2e04ca517bb7b828d%1746533495.304",
        "libpng/1.6.54#b3ee4845d09981511d04205c52d78de1%1768574561.963",
        "gtest/1.15.0#9eb07f548819215e766e41399858454f%1746533493.745",
        "freetype/2.13.3#75ca69fb4dc1a016c91b7f422ae58adc%1756828313.132",
        "fmt/10.2.1#8d582aeebdf05b6f0abe2911b926c3f4%1746533492.207",
        "cxxopts/3.2.0#8026d4f53938b476b36288e5d006bcfb%1746533491.431",
        "bzip2/1.0.8#c470882369c2d95c5c77e970c0c7e321%1762886692.465",
        "brotli/1.1.0#3f631ef77008f7b5eb388780116371a3%1764862343.045"
    ],
    "build_requires": [
        "pkgconf/2.5.1#93c2051284cba1279494a43a4fcfeae2%1757684701.089",
        "ninja/1.13.2#c8c5dc2a52ed6e4e42a66d75b4717ceb%1764096931.974",
        "meson/1.10.0#60786758ea978964c24525de19603cf4%1768294926.103"
    ],
    "python_requires": [],
    "config_requires": []
}
```

The packages nlohmann_json and cxxopts are missing from the analyzer result and any consecutive steps.

## Expected behavior

The packages are included not excluded

## Console / log output

No special output

## Environment

ORT Version 76.0.0 in the Docker Container

### PR DESCRIPTION
**Pull request by FabianRolfMatthiasNoll**
closes #11350

### CODE REVIEW

File: plugins/package-managers/conan/src/main/kotlin/PackageInfo.kt [hunk 1]
```diff
@@ -92,7 +92,8 @@ internal data class PackageInfoV2(
     val name: String,
     val version: String,
     val binaryRemote: String? = null,
-    val packageType: PackageType
+    val packageType: PackageType,
+    val context: String = "host"
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/main/kotlin/PackageInfo.kt]: Do we really need a default value here, i.e. is the field not mandatory (always present)? Similar below.

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/main/kotlin/PackageInfo.kt]: yes you are absolutely right. I found some discussion if its mandatory and didnt read correctly. But i just looked into the docks and the value should always be set to either host or build. good find

Comment (fviernau) [reply plugins/package-managers/conan/src/main/kotlin/PackageInfo.kt]: > set to either host or build. good find

If this is guaranteed, maybe consider even an enum?

(This would allow also moving the new KDoc from `parsePackages()` to the enum elements.

File: plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt [hunk 2]
```diff
@@ -171,11 +171,11 @@ internal class ConanV2Handler(private val conan: Conan) : ConanVersionHandler {
...
 
     /**
-     * Return the map of packages and their identifiers which are contained in [pkgInfos].
+     * Return the map of packages and their identifiers which are contained in [pkgInfos]. Only
+     * packages with host context are included, as build context packages are build-time tools.
      */
     private fun parsePackages(pkgInfos: List<PackageInfoV2>): Map<String, Package> =
-        // Package types are filtered because "conan graph info" return too many packages.
-        pkgInfos.filter { it.packageType == PackageType.STATIC_LIBRARY }.associate { pkgInfo ->
+        pkgInfos.filter { it.context == "host" }.associate { pkgInfo ->
```
Comment (fviernau) [inline plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: Is the property `context` the one added in the following commit? (If so, the commit order should be swapped?)

Comment (sschuberth) [reply plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: > If so, the commit order should be swapped?

I actually believe all commits could be squashed.

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: Yeah because after the commit linter failed because i forgot the type in the commit message i messed up trying to fix it. Original commits were correct so a squash would be the best option

File: plugins/package-managers/conan/src/main/kotlin/PackageInfo.kt (hunk 1 above)
Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/main/kotlin/PackageInfo.kt]: yeah good point. done

**Comment by FabianRolfMatthiasNoll** [comment]
I dont understand why the windows build and test failed. It looks to me like it doesnt have to do with my changes or do i oversee something here?

**Comment by mnonnenmacher** [comment]
> I dont understand why the windows build and test failed. It looks to me like it doesnt have to do with my changes or do i oversee something here?

No, the error seems unrelated, I have retriggered the test.

File: plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt (hunk 2 above)
Comment (sschuberth) [reply plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: I still see 5 commits in the PR, of which several should be either squashed or reordered. Note that we have a policy of each and every single commit in a PR being atomic, in the sense that each commit should be buildable and pass tests.

So you must not make use of the `context` property before actually adding it to the data model, as that would not build.

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: Yes thats why i thought we could just squash it at the end. Because i messed up by fixing my commits. But if thats not a policy here i will fix that

Comment (sschuberth) [reply plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: > we could just squash it at the end.

We don't do GitHub's "squash merge" upon merging, if that's what you mean, as it messes up commit messages by simply concatenating them.

So please do any squashing / commit reordering manually, so it's reflected in the PR, so that also commit history can be reviewed.

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: So this should be better. Because it wasnt a big change i decide to make it one clean commit

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/main/kotlin/ConanV2Handler.kt]: > We don't do GitHub's "squash merge" upon merging, if that's what you mean, as it messes up commit messages by simply concatenating them.

Oh didnt know that sorry. In the company we use gitlab and there squashing is quite nice

**Comment by FabianRolfMatthiasNoll** [comment]
[Build and Test / funTest-no-external-tools (pull_request)](https://github.com/oss-review-toolkit/ort/actions/runs/21281732381/job/61253670700?pr=11352)  failed but again i dont think of the changes. sadly it doesnt seem like i can retrigger it

**Comment by sschuberth** [comment]
> sadly it doesnt seem like i can retrigger it

That's fine. We'll take care of such things.

**Comment by sschuberth** [comment]
> closes #11350

Please put this as `Closes #11350.` to the bottom of the commit message, between the last paragraph and the footer.

File: plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml [hunk 3]
```diff
@@ -62,123 +62,6 @@ packages:
     url: ""
     revision: ""
     path: ""
-- id: "Conan::libiconv:1.17"
```
Comment (sschuberth) [inline plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: Something is now inconsistent here: These packages are removed from the flat set of packages, but they are still present in the project's dependency tree.

So it seems like excluding `Context.BUILD` packages effectively is like a scope-exclude for `build_requires`, which is not desired. So I'm unsure whether the idea to filter by `context` is feasible here at all.

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: yeah but build requires is not something that would appear in a sbom because its not shipped with the product. For the conan 1 handler i think this is also the current approach because it naturally doesnt list the build requires packages. But i could be wrong here

Comment (sschuberth) [reply plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: > build requires is not something that would appear in a sbom because its not shipped with the product.

That depends on the scope of the SBOM. No one says that SBOMs must (or even should) _generally_ be limited to what is shipped with the product. Otherwise formats like SPDX wouldn't have something like a [build profile](https://spdx.github.io/spdx-spec/v3.0.1/model/Build/Build/).

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: in this case i would be open to suggestions how to handle this best. We could tie this to a scope exclude so that in standard settings everything gets scanned or the other way arround having the build dependencies standard excluded but with a scope include?
Im happy to implement any suggestions because the current behaviour is not good and incomplete. Maybe we could in a first step even just include any dependency and work up from that?

Comment (sschuberth) [reply plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: > in standard settings everything gets scanned

ORT's policy is exactly that: Discover all by default, and filter down via configuration to what's relevant to your use-case.

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: So can we use any of the existing scopes or would we need a new one for conan? 
Or should we follow up in a new issue and here just remove the filtering?

Comment (sschuberth) [reply plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: > So can we use any of the existing scopes or would we need a new one for conan?

I don't understand that question. Scope names in ORT are package manager specific, i.e. how a scope for dependencies only used at build time is called varies, and ORT uses the name the underlying package manager provides.

> Or should we follow up in a new issue and here just remove the filtering?

Also here, I'm not sure what else needs to be done than just removing the filtering.

So if @nnobelis agrees, given the newest arguments, I'd just remove the filtering in this PR. Also see my question [here](https://github.com/oss-review-toolkit/ort/issues/11350#issuecomment-3783233466), which I believe was never fully answered by @nnobelis: Which "too much" packages are being reported without filtering? Do we really have over-reporting within a scope, or just more scopes than "usually needed"?

Comment (FabianRolfMatthiasNoll) [reply plugins/package-managers/conan/src/funTest/assets/projects/synthetic/conan2-expected-output-txt.yml:65]: > I don't understand that question. Scope names in ORT are package manager specific, i.e. how a scope for dependencies only used at build time is called varies, and ORT uses the name the underlying package manager provides.

Im sorry i didnt know that im still not familiar enough with the inner workings of ORT. I guessed that scopes are defined by the ORT Toolchain.

Hence also the second question is therefore answered because the suggestion was to remove filtering here and then follow up with a new scope or something but in this case its irrelevant

**Comment by FabianRolfMatthiasNoll** [comment]
Based on the discussion in the Issue the filtering was now completely removed. The Context was also reverted from the package model because it currently has no usage for us. 
Thanks for the discussions and insight @sschuberth @nnobelis

**Comment by sschuberth** [comment]
> Based on the discussion in the Issue the filtering was now completely removed.

Please see [this](https://github.com/oss-review-toolkit/ort/issues/11350#issuecomment-3809883561) for my newest thoughts on this, after having the time to debug this myself. Long story sgould, IMO we should replace the current filtering with

```kotlin
    private fun parsePackages(pkgInfos: List<PackageInfoV2>): Map<String, Package> =
        pkgInfos
            .filterNot { it.packageType == PackageType.APPLICATION || it.packageType == PackageType.BUILD_SCRIPTS }
            .associate { pkgInfo ->
                val pkg = parsePackage(pkgInfo)
                "${pkg.id.name}:${pkg.id.version}" to pkg
            }
```
