### PR TITLE
fix(node): Deserialize `repository: {}` in `package.json` to `null`

### LINKED ISSUE #9378: NPM failed to resolve dependencies for path 'package.json': MissingFieldException: Field 'url' is required for type with serial name 'org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJson.Repository', but it was missing
After updating OSS Review Toolkit to v37.0.0 and with v38.0.0 we are facing the following issue:

> NPM failed to resolve dependencies for path 'package.json': MissingFieldException: Field 'url' is required for type with serial name 'org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJson.Repository', but it was missing

Error probably occurs because of an empty repository property in the package.json file of this dependency: https://www.npmjs.com/package/@sap/xsenv/v/5.3.0?activeTab=code

```
{
   "name": "@sap/xsenv",
  "version": "5.3.0",
  "description": "Utility for easy setup and access of SAP HANA XS Advanced environment variables",
  "repository": {},
  "license": "SEE LICENSE IN LICENSE file",
  "main": "index.js",
  "engines": {
    "node": "^18.0.0 || ^20.0.0"
  },
...
```

I can reproduce it with:

```
{
	"name": "test",
	"version": "1.2.0",
	"private": true,
	"engines": {
		"node": "20"
	},
	"dependencies": {
		"@sap/xsenv": "5.3.0"
	}
}

```

BTW: The debug log doesn't say anything about the dependency where this happens, but I could find it by searching the potential successor of the last successful npm info ProcessCapture.
```
...
09:08:54.758 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.plugins.packagemanagers.node.Npm - Parsing module info from '/builds/foo/test/npm/node_modules/opossum/package.json'.
09:08:54.760 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.plugins.packagemanagers.node.Npm - Parsing module info from '/builds/foo/test/npm/node_modules/@sap/xsenv/package.json'.
...
09:10:07.171 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'npm info --json opossum@8.1.4' in '/builds/dvelop/compliance/license-scanning/test/npm/node_modules/opossum'...
09:10:07.454 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - {
09:10:07.454 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture -   "_id": "opossum@8.1.4",
...
09:10:07.454 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture -   "support": true,
09:10:07.454 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture -   "_nodeVersion": "18.20.2"
09:10:07.454 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - }
09:10:07.454 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - 
09:10:07.454 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - (Above output is limited to each 20 heading and tailing lines.)
09:10:08.448 [DefaultDispatcher-worker-1] ERROR org.ossreviewtoolkit.analyzer.PackageManager - NPM failed to resolve dependencies for path 'test/npm/package.json': MissingFieldException: Field 'url' is required for type with serial name 'org.ossreviewtoolkit.plugins.packagemanagers.node.PackageJson.Repository', but it was missing
```

### PR DESCRIPTION
**Pull request by fviernau**
A repository node wihtout a `url` does not make any sense. So, simply discard such nodes to not throw a `MissingFieldException` while keeping `Repository.url` non-nullable.

Fixes #9378.

### CODE REVIEW

File: plugins/package-managers/node/src/main/kotlin/PackageJson.kt [hunk 1]
```diff
@@ -74,6 +74,13 @@ private fun transformPackageJson(element: JsonElement): JsonElement {
     val entries = obj.entries.associateTo(mutableMapOf()) { it.toPair() }.apply {
         remove("license")
         put("licenses", JsonArray(licenses.map { JsonPrimitive(it) }))
+
```
Comment (mnonnenmacher) [inline plugins/package-managers/node/src/main/kotlin/PackageJson.kt:77]: Commit message: Typo in "without".

File: plugins/package-managers/node/src/main/kotlin/PackageJson.kt [hunk 2]
```diff
@@ -74,6 +74,13 @@ private fun transformPackageJson(element: JsonElement): JsonElement {
...
+        if ("url" !in (obj["repository"] as? JsonObject)?.keys.orEmpty()) {
+            // A repository node without a `url` does not make sense. However, some package use 'repository: {}' to
+            // describe the absence of repository, see https://github.com/oss-review-toolkit/ort/issues/9378. Simply
+            // remove the repository node, so that Repository.url can remain non-nullable.
```
Comment (mnonnenmacher) [inline plugins/package-managers/node/src/main/kotlin/PackageJson.kt:81]: Nits:
* "some package**s**"
* "of **a** repository"
* "Simply" is redundant

**Review by mnonnenmacher — DISMISSED** [review]

File: plugins/package-managers/node/src/main/kotlin/PackageJson.kt [hunk 3]
```diff
@@ -74,6 +74,13 @@ private fun transformPackageJson(element: JsonElement): JsonElement {
     val entries = obj.entries.associateTo(mutableMapOf()) { it.toPair() }.apply {
         remove("license")
         put("licenses", JsonArray(licenses.map { JsonPrimitive(it) }))
+
+        if ("url" !in (obj["repository"] as? JsonObject)?.keys.orEmpty()) {
```
Comment (sschuberth) [inline plugins/package-managers/node/src/main/kotlin/PackageJson.kt:78]: This condition would remove the element also if other fields than `url` *are* present. So how about using `(obj["repository"] as? JsonObject)?.isEmpty() == true` instead which emphasizes that the whole object is empty?

Comment (fviernau) [reply plugins/package-managers/node/src/main/kotlin/PackageJson.kt:78]: > This condition would remove the element also if other fields than `url` _are_ present.

The reason I decided for this is to also fix crashing in the same way in this case. As written in the
commit message, I believe repository nodes without `url` do not make sense (also looking at the specs) and should be discarded.

> So how about using (obj["repository"] as? JsonObject)?.isEmpty() == true instead which emphasizes that the whole object is empty?

This has a different effect. Would you prefer to keep on crashing in the above case? 

What do you think?

Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/PackageJson.kt:78]: > Would you prefer to keep on crashing in the above case?

Ideally we would not really crash, but create an issue about it, as I believe there's value in informing the user about broken definition files. However, as it's not easy to create an ORT issue from here without stopping deserialization, let's keep our existing code.

Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/PackageJson.kt:78]: > I believe there's value in informing the user about broken definition files.

I've created the more general https://github.com/oss-review-toolkit/ort/issues/9383 for this.

**Review by sschuberth — APPROVED** [review]

**Comment by sschuberth** [comment]
@fviernau can you please have a look at the `NpmFunTest` failures? At a first glance I do not understand why the URLs change there.

**Comment by fviernau** [comment]
> @fviernau can you please have a look at the `NpmFunTest` failures? At a first glance I do not understand why the URLs change there.

My fix did not distinguish between textual and object repository nodes. (Now it does.)

**Review by sschuberth — APPROVED** [review]
