### PR TITLE
fix(node): Do not follow cyclic directory links

### LINKED ISSUE #6531: Docker Analyzer runs forever for project particle-emitter
`The OSS Review Toolkit, version e57fed5.` docker build

OSS Project: https://github.com/pixijs/particle-emitter/
```
Found 1 Yarn definition file(s) at:
        package.json
Found 1 definition file(s) from 1 package manager(s) in total.
...
15:09:54.014 [main] INFO  org.ossreviewtoolkit.analyzer.Analyzer - Starting Yarn analysis.
...
15:09:54.418 [DefaultDispatcher-worker-1] INFO  org.ossreviewtoolkit.utils.common.ProcessCapture - Running 'yarn install --ignore-scripts --ignore-engines' in '/ort'...
15:10:12.999 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - yarn install v1.22.17
15:10:12.999 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - [1/4] Resolving packages...
15:10:12.999 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - [2/4] Fetching packages...
15:10:13.000 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - [3/4] Linking dependencies...
15:10:13.000 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - [4/4] Building fresh packages...
15:10:13.000 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - success Saved lockfile.
15:10:13.000 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - Done in 18.39s.
15:10:13.000 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture -
15:10:13.000 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture - warning Ignored scripts due to flag.
15:10:13.000 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.utils.common.ProcessCapture -
15:10:13.084 [DefaultDispatcher-worker-1] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - Parsing project info from '/ort/package.json'.
```

after a couple hundred MB of logs:

```
17:12:37.115 [DefaultDispatcher-worker-2] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - Starting to parse '/ort/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/@pixi/particle-emitter/package.json'...
17:12:37.115 [DefaultDispatcher-worker-27] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - Found a 'package.json' file in '/ort/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/@pixi/particle-emitter'.
17:12:37.116 [DefaultDispatcher-worker-27] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - The package directory '/ort/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/@pixi/particle-emitter' links to '/ort'.
17:12:37.116 [DefaultDispatcher-worker-27] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - Resolving the package info for 'NPM:@pixi:particle-emitter:5.0.8' locally from '/ort'.
17:12:37.119 [DefaultDispatcher-worker-27] DEBUG org.ossreviewtoolkit.analyzer.managers.Npm - Finished parsing '/ort/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/pixi-v6-iife/node_modules/@pixi/particle-emitter/node_modules/@pixi/particle-emitter/package.json' to 'NPM:@pixi:particle-emitter:5.0.8'.
```

Something is amiss and I can't figure it what/why. 🙏🏻 

tried with:
```
$ ort -P ort.analyzer.allowDynamicVersions=true --debug analyze -i /ort -o /ort -f JSON
$ ort --debug analyze -m yarn -i /ort -o /ort
```

### PR DESCRIPTION
**Pull request by sschuberth**
This generalizes the `maxDepth`-related work-around done for PNPM to fix a similar issue for Yarn if the `node_modules` directory hierarchy contains cyclic links. This is done by maintaining a temporary set of visited "real" directories.

The issue was interesting to debug as the infinite loop caused by circular links was only triggered when actually evaluating the lazy sequence created by `File.walk()`.

While at it, make the filtering for `package.json` a bit more strict by requiring it to be a file.

Fixes #6531.

### CODE REVIEW

File: plugins/package-managers/node/src/main/kotlin/Npm.kt [hunk 1]
```diff
@@ -246,8 +240,13 @@ open class Npm(
...
 
-        val nodeModulesFiles = nodeModulesDir.walk().maxDepth(modulesSearchDepth).filter {
-            it.name == "package.json" && isValidNodeModulesDirectory(nodeModulesDir, nodeModulesDirForPackageJson(it))
+        val visitedDirs = mutableSetOf<File>()
+
+        val nodeModulesFiles = nodeModulesDir.walk().onEnter { dir ->
+            !dir.isSymbolicLink() || visitedDirs.add(dir.realFile())
+        }.filter {
+            it.isFile && it.name == "package.json" &&
+                isValidNodeModulesDirectory(nodeModulesDir, nodeModulesDirForPackageJson(it))
```
Comment (fviernau) [inline plugins/package-managers/node/src/main/kotlin/Npm.kt:249]: It could be just me: it seems the area of code is complicated and there I believe it would be worth making a separate preceding commit for the `it.IsFile` check, just minimize the diff of the bug fix.

File: plugins/package-managers/node/src/main/kotlin/Npm.kt [hunk 2]
```diff
@@ -246,8 +240,13 @@ open class Npm(
 
         logger.info { "Searching for 'package.json' files in '$nodeModulesDir'..." }
 
-        val nodeModulesFiles = nodeModulesDir.walk().maxDepth(modulesSearchDepth).filter {
-            it.name == "package.json" && isValidNodeModulesDirectory(nodeModulesDir, nodeModulesDirForPackageJson(it))
+        val visitedDirs = mutableSetOf<File>()
+
+        val nodeModulesFiles = nodeModulesDir.walk().onEnter { dir ->
+            !dir.isSymbolicLink() || visitedDirs.add(dir.realFile())
```
Comment (fviernau) [inline plugins/package-managers/node/src/main/kotlin/Npm.kt:246]: I'm not sure if `!dir.isSymbolicLink()` is correct. Would it work to only work with "realDirs" like with the following (to be beautified) code:

```
onEnter { dir ->
    val realDir  = dir.realFile()
    if (realDir in visitedDirs) {
       false
    } else {
        visitedDirs += realDir
        true
    }
```

File: plugins/package-managers/node/src/main/kotlin/Npm.kt [hunk 3]
```diff
@@ -246,8 +240,13 @@ open class Npm(
 
         logger.info { "Searching for 'package.json' files in '$nodeModulesDir'..." }
 
-        val nodeModulesFiles = nodeModulesDir.walk().maxDepth(modulesSearchDepth).filter {
-            it.name == "package.json" && isValidNodeModulesDirectory(nodeModulesDir, nodeModulesDirForPackageJson(it))
+        val visitedDirs = mutableSetOf<File>()
```
Comment (fviernau) [inline plugins/package-managers/node/src/main/kotlin/Npm.kt:243]: commit-message: Is this really a generalization for the mentioned max depth work around, or is it a different work around (or maybe even a proper solution) for the same underlying problem.

Also, would it make sense to link the commit for that Pnpm work around. I wasn't unable to find this quickly.

**Review by fviernau — CHANGES_REQUESTED** [review]

File: plugins/package-managers/node/src/main/kotlin/Npm.kt (hunk 2 above)
Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:246]: > I'm not sure if `!dir.isSymbolicLink()` is correct.

What makes you doubt? IMO that's exactly the check we want to perform, and it's short and precise. Also, I've verified it to work with the project mentioned in #6531.

File: plugins/package-managers/node/src/main/kotlin/Npm.kt (hunk 3 above)
Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:243]: > or maybe even a proper solution

I believe it's indeed a proper solution. The `maxDepth`-based approach did not really break the cycles, but just followed them until a maximum depth (that was set just so that all packages are found in the created directory hierachry). The solution in this PR really breaks the cycle.

> Also, would it make sense to link the commit for that Pnpm work around. I wasn't unable to find this quickly.

The work-around was there from the start, when PNPM support was introduced in 18d8903f43f4a8a7b77e87f4042fd38514a4436e. I've mentioned it in the commit message.

File: plugins/package-managers/node/src/main/kotlin/Npm.kt (hunk 2 above)
Comment (fviernau) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:246]: In order to understand whether not following symlinks is correct, one needs to have a full understanding 
of 1. the link symlink structure of the multiple NPM package managers and 2. the directory structure.

Not proccessing a realDir twice in my view is (more) obvioulsy correct. (isn't that short an precise as well) ?

Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:246]: > Not proccessing a realDir twice in my view is (more) obvioulsy correct.

My thinking is: You can never process a realdir twice if never following symbolic links. That is, the realdir check only needs to be performed when a symlink has been followed.

> isn't that short an precise as well

It's easy to phrase in prose, but you yourself admitted that [the code is not](https://github.com/oss-review-toolkit/ort/pull/8156#discussion_r1464948455).

Comment (fviernau) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:246]: > My thinking is: You can never process a realdir twice if never following symbolic links. That is, the realdir check only needs to be performed when a symlink has been followed.

That's clear. Do you also have an explanation why you wouldn't miss a realDir, if not following symlinks?

Comment (sschuberth) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:246]: > Do you also have an explanation why you wouldn't miss a realDir, if not following symlinks?

I'm not sure I follow why the question is relevant. My code does not *never* follow symlinks, but it only follows a symlink if it does not point to a realdir that has been visited before (`Set.add()` returns `true` only if the realdir was actually added, i.e. not yet present in the set).

Comment (fviernau) [reply plugins/package-managers/node/src/main/kotlin/Npm.kt:246]: Argh, sorry. I mis-read that expression in line 246. Now it's clear. Thanks!

**Review by fviernau — APPROVED** [review]
