### PR TITLE
Flutter: Ensure that flutter generates required file for Android project

### LINKED ISSUE #4651: Analyzing a simple Flutter project fails
### To reproduce
Create a new project:
```bash
❯ flutter create flutter_example
Creating project flutter_example...
...
All done!
In order to run your application, type:

  $ cd flutter_example
  $ flutter run

Your application code is in flutter_example/lib/main.dart.
```

Setup Git repo:
```bash
git init && git add . && git commit -m "Initial commit"
```

Delete all gitignored files:
```bash
git clean -fdx
```

Run ORT analyzer:
```bash
ort --info --stacktrace analyze -i . -o ort/analyzer
```

This analyzer run fails with 2 Errors:
<details>
  <summary>ORT log</summary>

```sh
❯ ort --info --stacktrace analyze -i . -o ort/analyzer
10:04:01.204 [main] INFO  org.ossreviewtoolkit.model.config.OrtConfiguration - Using ORT configuration file '/Users/bom1wa3/.ort/config/ort.conf'.
________ _____________________
\_____  \\______   \__    ___/ the OSS Review Toolkit, version 6892f99.
 /   |   \|       _/ |    |
/    |    \    |   \ |    |    Running 'analyze' under Java 11.0.13 on Mac OS X with
\_______  /____|_  / |____|    12 CPUs and a maximum of 8192 MiB of memory.
        \/       \/
Environment variables:
ORT_CONFIG_DIR = /Users/bom1wa3/.ort/config
ORT_DATA_DIR = /Users/bom1wa3/.ort
SHELL = /opt/local/bin/zsh
TERM = xterm-256color
JAVA_HOME = /Library/Java/JavaVirtualMachines/openjdk11-zulu/Contents/Home
ANDROID_HOME = /Users/bom1wa3/.android
GOPATH = /Users/bom1wa3/work/go

The following configuration files and directories are used:
	/Users/bom1wa3/.ort/config/curations.yml
	/Users/bom1wa3/.ort/config/curations
The following package managers are activated:
	Bower, Bundler, Cargo, Carthage, CocoaPods, Composer, Conan, DotNet, GoDep, GoMod, Gradle, Maven, NPM, NuGet, PIP, Pipenv, Pub, SBT, SpdxDocumentFile, Stack, Yarn
Analyzing project path:
	/Users/bom1wa3/work/playground/flutter_example
10:04:01.581 [main] INFO  org.ossreviewtoolkit.analyzer.PackageManager - Not analyzing directory '/Users/bom1wa3/work/playground/flutter_example/.git' as it is hard-coded to be ignored.
10:04:02.330 [main] INFO  org.ossreviewtoolkit.utils.core.OrtAuthenticator - Authenticator was successfully installed.
10:04:02.343 [main] INFO  org.ossreviewtoolkit.utils.core.OrtProxySelector - Proxy selector was successfully installed.
Found 2 Gradle project(s) at:
	android/build.gradle
	android/app/build.gradle
Found 1 Pub project(s) at:
	pubspec.yaml
Found 2 project(s) in total.
10:04:02.412 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Skipping to bootstrap flutter as it was found in /Users/bom1wa3/.homebrew/bin.
10:04:02.413 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Resolving Pub dependencies for 'pubspec.yaml'...
10:04:02.413 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Gradle - Resolving Gradle dependencies for 'android/build.gradle'...
10:04:02.469 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.core.ProcessCapture - Running '/Users/bom1wa3/.homebrew/bin/dart pub get' in '/Users/bom1wa3/work/playground/flutter_example'...
10:04:03.437 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Reading pubspec.lock file in /Users/bom1wa3/work/playground/flutter_example.
10:04:03.445 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Successfully read lockfile.
10:04:03.446 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Parsing installed Pub packages...
10:04:03.508 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Successfully parsed installed packages.
10:04:03.509 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Parsing scope 'dependencies' for package 'flutter_example'.
10:04:03.509 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - buildDependencyTree for package flutter_example
10:04:03.510 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - buildDependencyTree for package cupertino_icons
10:04:03.512 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Parsing scope 'dev_dependencies' for package 'flutter_example'.
10:04:03.512 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - buildDependencyTree for package flutter_example
10:04:03.513 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - buildDependencyTree for package flutter_lints
10:04:03.514 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - buildDependencyTree for package lints
10:04:03.514 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Reading pubspec.yaml file in /Users/bom1wa3/work/playground/flutter_example.
10:04:03.546 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.core.OrtAuthenticator - Authenticator is already installed.
10:04:03.546 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.utils.core.OrtProxySelector - Proxy selector is already installed.
10:04:03.849 [DefaultDispatcher-worker-3] INFO  org.ossreviewtoolkit.analyzer.managers.Pub - Resolving Pub dependencies for 'pubspec.yaml' took 1s.
org.gradle.tooling.BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.7-all.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:51)
	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:203)
	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:189)
	at org.ossreviewtoolkit.utils.core.UtilsKt.temporaryProperties(Utils.kt:307)
	at org.ossreviewtoolkit.analyzer.managers.Gradle.resolveDependencies(Gradle.kt:189)
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:241)
	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$1$1$1.invokeSuspend(Analyzer.kt:132)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Settings file '/Users/bom1wa3/work/playground/flutter_example/android/settings.gradle' line: 6
A problem occurred evaluating settings 'android'.
	at org.gradle.initialization.exception.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:103)
	at org.gradle.initialization.exception.DefaultExceptionAnalyser.collectFailures(DefaultExceptionAnalyser.java:67)
	at org.gradle.initialization.exception.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:48)
	at org.gradle.initialization.exception.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:190)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:153)
	at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:115)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:72)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:67)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:178)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
	at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:61)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:56)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:67)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:54)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:87)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:53)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:49)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:27)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating settings 'android'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
	at org.gradle.configuration.DefaultScriptTarget.addConfiguration(DefaultScriptTarget.java:74)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
	at org.gradle.configuration.BuildOperationScriptPlugin.lambda$apply$0(BuildOperationScriptPlugin.java:62)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:43)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:62)
	at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.applySettingsScript(ScriptEvaluatingSettingsProcessor.java:74)
	at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:67)
	at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)
	at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:50)
	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.initialization.BuildOperationSettingsProcessor.process(BuildOperationSettingsProcessor.java:47)
	at org.gradle.initialization.DefaultSettingsLoader.findSettingsAndLoadIfAppropriate(DefaultSettingsLoader.java:120)
	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:58)
	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
	at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
	at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:52)
	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
	at org.gradle.initialization.BuildOperationFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperationFiringSettingsPreparer.java:59)
	at org.gradle.initialization.BuildOperationFiringSettingsPreparer$LoadBuild.run(BuildOperationFiringSettingsPreparer.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
	at org.gradle.initialization.BuildOperationFiringSettingsPreparer.prepareSettings(BuildOperationFiringSettingsPreparer.java:42)
	at org.gradle.initialization.DefaultGradleLauncher.prepareSettings(DefaultGradleLauncher.java:220)
	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:161)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
	... 77 more
Caused by: Assertion failed:

assert localPropertiesFile.exists()
       |                   |
       |                   false
       /Users/bom1wa3/work/playground/flutter_example/android/local.properties

	at settings_231aomr5f7n10pvqn5izsjqb1.run(/Users/bom1wa3/work/playground/flutter_example/android/settings.gradle:6)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 134 more
10:04:06.389 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.managers.Gradle - Resolving Gradle dependencies for 'android/build.gradle' failed with: BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.7-all.zip'.
Caused by: LocationAwareException: Settings file '/Users/bom1wa3/work/playground/flutter_example/android/settings.gradle' line: 6
A problem occurred evaluating settings 'android'.
Caused by: GradleScriptException: A problem occurred evaluating settings 'android'.
Caused by: PowerAssertionError: assert localPropertiesFile.exists()
       |                   |
       |                   false
       /Users/bom1wa3/work/playground/flutter_example/android/local.properties
10:04:06.389 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Gradle - Resolving Gradle dependencies for 'android/build.gradle' took 3s.
10:04:06.389 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Gradle - Resolving Gradle dependencies for 'android/app/build.gradle'...
org.gradle.tooling.BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.7-all.zip'.
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:51)
	at org.gradle.tooling.internal.consumer.ExceptionTransformer.transform(ExceptionTransformer.java:29)
	at org.gradle.tooling.internal.consumer.ResultHandlerAdapter.onFailure(ResultHandlerAdapter.java:43)
	at org.gradle.tooling.internal.consumer.async.DefaultAsyncConsumerActionExecutor$1$1.run(DefaultAsyncConsumerActionExecutor.java:69)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
	at org.gradle.tooling.internal.consumer.BlockingResultHandler.getResult(BlockingResultHandler.java:46)
	at org.gradle.tooling.internal.consumer.DefaultModelBuilder.get(DefaultModelBuilder.java:51)
	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:203)
	at org.ossreviewtoolkit.analyzer.managers.Gradle$resolveDependencies$5.invoke(Gradle.kt:189)
	at org.ossreviewtoolkit.utils.core.UtilsKt.temporaryProperties(Utils.kt:307)
	at org.ossreviewtoolkit.analyzer.managers.Gradle.resolveDependencies(Gradle.kt:189)
	at org.ossreviewtoolkit.analyzer.PackageManager.resolveDependencies(PackageManager.kt:241)
	at org.ossreviewtoolkit.analyzer.Analyzer$analyzeInParallel$1$1$1.invokeSuspend(Analyzer.kt:132)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: org.gradle.internal.exceptions.LocationAwareException: Settings file '/Users/bom1wa3/work/playground/flutter_example/android/settings.gradle' line: 6
A problem occurred evaluating settings 'android'.
	at org.gradle.initialization.exception.DefaultExceptionAnalyser.transform(DefaultExceptionAnalyser.java:103)
	at org.gradle.initialization.exception.DefaultExceptionAnalyser.collectFailures(DefaultExceptionAnalyser.java:67)
	at org.gradle.initialization.exception.MultipleBuildFailuresExceptionAnalyser.transform(MultipleBuildFailuresExceptionAnalyser.java:48)
	at org.gradle.initialization.exception.StackTraceSanitizingExceptionAnalyser.transform(StackTraceSanitizingExceptionAnalyser.java:30)
	at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:190)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:153)
	at org.gradle.initialization.DefaultGradleLauncher.getConfiguredBuild(DefaultGradleLauncher.java:115)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:72)
	at org.gradle.internal.invocation.GradleBuildController$1.create(GradleBuildController.java:67)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:178)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:67)
	at org.gradle.internal.invocation.GradleBuildController.configure(GradleBuildController.java:61)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:56)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.BuildOutcomeReportingBuildActionRunner.run(BuildOutcomeReportingBuildActionRunner.java:63)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.tooling.internal.provider.FileSystemWatchingBuildActionRunner.run(FileSystemWatchingBuildActionRunner.java:67)
	at org.gradle.launcher.exec.BuildCompletionNotifyingBuildActionRunner.run(BuildCompletionNotifyingBuildActionRunner.java:41)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:49)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$3.call(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:44)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.lambda$execute$0(InProcessBuildActionExecuter.java:54)
	at org.gradle.composite.internal.DefaultRootBuildState.run(DefaultRootBuildState.java:87)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:53)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.lambda$execute$0(BuildTreeScopeLifecycleBuildActionExecuter.java:33)
	at org.gradle.internal.buildtree.BuildTreeState.run(BuildTreeState.java:49)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:32)
	at org.gradle.launcher.exec.BuildTreeScopeLifecycleBuildActionExecuter.execute(BuildTreeScopeLifecycleBuildActionExecuter.java:27)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:104)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionExecuter.execute(SubscribableBuildActionExecuter.java:37)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.lambda$execute$0(SessionScopeLifecycleBuildActionExecuter.java:54)
	at org.gradle.internal.session.BuildSessionState.run(BuildSessionState.java:67)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:50)
	at org.gradle.tooling.internal.provider.SessionScopeLifecycleBuildActionExecuter.execute(SessionScopeLifecycleBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:59)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:31)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:41)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:47)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:31)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:65)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:39)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:29)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:35)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:78)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.create(ForwardClientInput.java:75)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:75)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:63)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:84)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:104)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:52)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleScriptException: A problem occurred evaluating settings 'android'.
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
	at org.gradle.configuration.DefaultScriptTarget.addConfiguration(DefaultScriptTarget.java:74)
	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
	at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
	at org.gradle.configuration.BuildOperationScriptPlugin.lambda$apply$0(BuildOperationScriptPlugin.java:62)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.apply(DefaultUserCodeApplicationContext.java:43)
	at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:62)
	at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.applySettingsScript(ScriptEvaluatingSettingsProcessor.java:74)
	at org.gradle.initialization.ScriptEvaluatingSettingsProcessor.process(ScriptEvaluatingSettingsProcessor.java:67)
	at org.gradle.initialization.SettingsEvaluatedCallbackFiringSettingsProcessor.process(SettingsEvaluatedCallbackFiringSettingsProcessor.java:34)
	at org.gradle.initialization.RootBuildCacheControllerSettingsProcessor.process(RootBuildCacheControllerSettingsProcessor.java:36)
	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:50)
	at org.gradle.initialization.BuildOperationSettingsProcessor$2.call(BuildOperationSettingsProcessor.java:47)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:76)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:76)
	at org.gradle.initialization.BuildOperationSettingsProcessor.process(BuildOperationSettingsProcessor.java:47)
	at org.gradle.initialization.DefaultSettingsLoader.findSettingsAndLoadIfAppropriate(DefaultSettingsLoader.java:120)
	at org.gradle.initialization.DefaultSettingsLoader.findAndLoadSettings(DefaultSettingsLoader.java:58)
	at org.gradle.initialization.SettingsAttachingSettingsLoader.findAndLoadSettings(SettingsAttachingSettingsLoader.java:35)
	at org.gradle.internal.composite.CommandLineIncludedBuildSettingsLoader.findAndLoadSettings(CommandLineIncludedBuildSettingsLoader.java:34)
	at org.gradle.internal.composite.ChildBuildRegisteringSettingsLoader.findAndLoadSettings(ChildBuildRegisteringSettingsLoader.java:52)
	at org.gradle.internal.composite.CompositeBuildSettingsLoader.findAndLoadSettings(CompositeBuildSettingsLoader.java:35)
	at org.gradle.initialization.DefaultSettingsPreparer.prepareSettings(DefaultSettingsPreparer.java:36)
	at org.gradle.initialization.BuildOperationFiringSettingsPreparer$LoadBuild.doLoadBuild(BuildOperationFiringSettingsPreparer.java:59)
	at org.gradle.initialization.BuildOperationFiringSettingsPreparer$LoadBuild.run(BuildOperationFiringSettingsPreparer.java:54)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$run$1(DefaultBuildOperationExecutor.java:71)
	at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.runWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:45)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:71)
	at org.gradle.initialization.BuildOperationFiringSettingsPreparer.prepareSettings(BuildOperationFiringSettingsPreparer.java:42)
	at org.gradle.initialization.DefaultGradleLauncher.prepareSettings(DefaultGradleLauncher.java:220)
	at org.gradle.initialization.DefaultGradleLauncher.doClassicBuildStages(DefaultGradleLauncher.java:161)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
	... 77 more
Caused by: Assertion failed:

assert localPropertiesFile.exists()
       |                   |
       |                   false
       /Users/bom1wa3/work/playground/flutter_example/android/local.properties

	at settings_231aomr5f7n10pvqn5izsjqb1.run(/Users/bom1wa3/work/playground/flutter_example/android/settings.gradle:6)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
	... 134 more
10:04:06.530 [DefaultDispatcher-worker-2] ERROR org.ossreviewtoolkit.analyzer.managers.Gradle - Resolving Gradle dependencies for 'android/app/build.gradle' failed with: BuildException: Could not fetch model of type 'DependencyTreeModel' using connection to Gradle distribution 'https://services.gradle.org/distributions/gradle-6.7-all.zip'.
Caused by: LocationAwareException: Settings file '/Users/bom1wa3/work/playground/flutter_example/android/settings.gradle' line: 6
A problem occurred evaluating settings 'android'.
Caused by: GradleScriptException: A problem occurred evaluating settings 'android'.
Caused by: PowerAssertionError: assert localPropertiesFile.exists()
       |                   |
       |                   false
       /Users/bom1wa3/work/playground/flutter_example/android/local.properties
10:04:06.530 [DefaultDispatcher-worker-2] INFO  org.ossreviewtoolkit.analyzer.managers.Gradle - Resolving Gradle dependencies for 'android/app/build.gradle' took 0s.
10:04:06.606 [main] INFO  org.ossreviewtoolkit.utils.core.ProcessCapture - Running '/Users/bom1wa3/.homebrew/bin/dart --version' in '/Users/bom1wa3/work/playground/flutter_example'...
Writing analyzer result to '/Users/bom1wa3/work/playground/flutter_example/ort/analyzer/analyzer-result.yml'.
Resolved issues: 0 errors, 0 warnings, 0 hints.
Unresolved issues: 2 errors, 0 warnings, 0 hints.
There are 2 unresolved issues with a severity equal to or greater than the WARNING threshold.
```

</details>

### Used flutter version

```bash
❯ flutter --version
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 weeks ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

### First analysis

This issue is caused by a missing `local.properties` file in the android project created by flutter.
This is normally created by running `flutter pub get`.
However, in ORT's case the 3 projects (Pub, Gradle, Cocoapods) are analysed in parallel and therefore it's not possible to guarantee that `flutter pub get` was run before the Gradle project is analysed.

### PR DESCRIPTION
**Pull request by MarcelBochtler**
This ensures that the `local.properties` file for Android Gradle
projects is generated before Gradle analyzes this project.

Resolves #4651.

The created dependency tree adds the child Gradle project as a dependency of the Flutter project:
image

Two things to note in this implementation:
1. The printed analyzer information is not completely correct. i.e. the child Gradle project(s) will not be printed, and the count is wrong:
```
Found 1 Pub project(s) at:
	pubspec.yaml
Found 1 project(s) in total.
```

As a workaround I added an additional print to show the child Gradle project(s):
```
Found 2 Gradle project(s) at:
	android/build.gradle
	android/app/build.gradle
```

2. Running the Analyzer using the `-m Pub` option, will now also run Gradle for Gradle projects managed by Flutter.

### CODE REVIEW

File: analyzer/src/main/kotlin/Analyzer.kt [hunk 1]
```diff
@@ -133,9 +134,15 @@ class Analyzer(private val config: AnalyzerConfiguration, private val labels: Ma
                 async {
                     val results = manager.resolveDependencies(files, labels)
 
-                    // By convention, project ids must be of the type of the respective package manager.
+                    // By convention, project ids must be of the type of the respective package manager. An exception
+                    // for this is Flutter with Pub, which internally calls Gradle.
                     results.projectResults.forEach { (_, result) ->
-                        val invalidProjects = result.filter { it.project.id.type != manager.managerName }
+                        val invalidProjects = result.filterNot {
+                            val typeById = it.project.id.type
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/Analyzer.kt:141]: What does the "ById" suffix refer to? How about just "projectType"?

File: analyzer/src/main/kotlin/Analyzer.kt [hunk 2]
```diff
@@ -133,9 +134,15 @@ class Analyzer(private val config: AnalyzerConfiguration, private val labels: Ma
                 async {
                     val results = manager.resolveDependencies(files, labels)
 
-                    // By convention, project ids must be of the type of the respective package manager.
+                    // By convention, project ids must be of the type of the respective package manager. An exception
+                    // for this is Flutter with Pub, which internally calls Gradle.
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/Analyzer.kt:138]: Nit: Shouldn't it be "Pub with Flutter"?

File: analyzer/src/main/kotlin/managers/Pub.kt [hunk 3]
```diff
@@ -241,20 +243,72 @@ class Pub(
...
+                        val relativePath = it.toRelativeString(workingDir).takeIf { it.isNotEmpty() } ?: "."
+
+                        println("\t$relativePath")
+                    }
+                }
+
+                log.info { "Running Gradle analysis for Flutter project." }
+
+                // TODO: This ignores the AnalyzerCommand's `--package-managers` option and always runs Gradle for
+                //  Flutter projects.
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/Pub.kt:268]: Indentation is off. But anyway, I believe we drop this TODO, as I'd argue that anyone who enabled Pub but disabled Gradle (or enabled Pub only) still wants Gradle projects as part of Pub projects to be analyzed.

File: analyzer/src/main/kotlin/managers/Pub.kt [hunk 4]
```diff
@@ -241,20 +243,72 @@ class Pub(
...
+                val gradleAnalyzerResult = Gradle(
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/Pub.kt:269]: It's a bit unfortunate that we're using both the Gradle factory (see above) and a custom Gradle instance here. Can somehow align on using only either one?

File: analyzer/src/main/kotlin/managers/Gradle.kt [hunk 5]
```diff
@@ -134,6 +135,13 @@ class Gradle(
     // The path to the root project. In a single-project, just points to the project path.
     private lateinit var rootProjectDir: File
 
+    // Filter Gradle projects that are managed via Flutter / Pub. These projects are analyzed from within Pub.
+    override fun mapDefinitionFiles(definitionFiles: List<File>) = definitionFiles.filter { gradleDefinitionFile ->
```
Comment (sschuberth) [inline analyzer/src/main/kotlin/managers/Gradle.kt:139]: Nit: The part after `=` should start in the next line.

**Review by sschuberth — DISMISSED** [review]

File: analyzer/src/main/kotlin/managers/Pub.kt (hunk 3 above)
Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/managers/Pub.kt:268]: Removed. But for future reference: How should this be indented?
If both lines are are indented on the same level I don't get IDE highlighting for the whole TODO.

File: analyzer/src/main/kotlin/Analyzer.kt (hunk 1 above)
Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/Analyzer.kt:141]: I wanted to differentiation between the "type" from `manager.managerName` and the type from `it.project.id.type`.
But thinking about it again `managerName` <-> `projectType` is better.

File: analyzer/src/main/kotlin/managers/Pub.kt (hunk 3 above)
Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/Pub.kt:268]: See existing `TODO` statements 😉 All lines have to start their text in the column of the "T" from "This".

File: analyzer/src/main/kotlin/Analyzer.kt [hunk 6]
```diff
@@ -133,9 +134,16 @@ class Analyzer(private val config: AnalyzerConfiguration, private val labels: Ma
                 async {
                     val results = manager.resolveDependencies(files, labels)
 
-                    // By convention, project ids must be of the type of the respective package manager.
+                    // By convention, project ids must be of the type of the respective package manager. An exception
```
Comment (fviernau) [inline analyzer/src/main/kotlin/Analyzer.kt:137]: Would it make sense to just map the type inside the flutter implementation from "Gradle" to "Flutter", so this special case can be avoided?

**Review by fviernau — CHANGES_REQUESTED** [review]

File: analyzer/src/main/kotlin/Analyzer.kt (hunk 6 above)
Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: This would hide some information what the actual package manager of the project is.
However, that might be ok, because it doesn't really make sense to scan a Gradle / CocoaPods project managed by Flutter by their own.
But in extension would this also mean to map the `Pub` and the `CococaPods` project to the type `Flutter`?

All these projects would end up in the dependency tree:
```
Flutter:gradle-subproject:bbb
Flutter:pub-project:aaa
    dependencies
        Flutter:gradle-subproject:bbb
```

IMO it's better to have this special case in this check, than to change the result.
What do you think?

File: analyzer/src/main/kotlin/managers/Gradle.kt [hunk 7]
```diff
@@ -134,6 +135,14 @@ class Gradle(
     // The path to the root project. In a single-project, just points to the project path.
     private lateinit var rootProjectDir: File
 
+    // Filter Gradle projects that are managed via Flutter / Pub. These projects are analyzed from within Pub.
+    override fun mapDefinitionFiles(definitionFiles: List<File>) =
+        definitionFiles.filter { gradleDefinitionFile ->
+            Pub.Factory().globsForDefinitionFiles.none { pubDefinitionFile ->
```
Comment (oheger-bosch) [inline analyzer/src/main/kotlin/managers/Gradle.kt:141]: The Pub Factory should not be instantiated for each definition file inside the `filter` expression; just create it once.

Usage of this factory creates a rather tight and cyclic coupling  between the `Pub` and the `Gradle` package manager implementations. It would be good if that cycle could be broken, so that only `Pub` knows `Gradle`, but not the other way around. But I do not know how this could be achieved with the current mechanism to identify definition files.

Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/managers/Gradle.kt]: I removed the Factory instantiation in the loop.

**Review by oheger-bosch — APPROVED** [review]

File: analyzer/src/funTest/kotlin/managers/PubFunTest.kt [hunk 8]
```diff
@@ -113,4 +141,34 @@ class PubFunTest : WordSpec() {
...
         return Pub("Pub", USER_DIR, config, DEFAULT_REPOSITORY_CONFIGURATION)
     }
+
+    /**
+     * Replace aapt2 URL and hash value with dummy values, as these are platform dependant.
+     */
+    private fun OrtResult.patchAapt2Result(): OrtResult {
+        val packages = analyzer?.result?.packages?.toMutableSet()
+        val aapt2Package =
+            packages?.find { it.pkg.id == Identifier("Maven:com.android.tools.build:aapt2:4.1.0-6503028") }
```
Comment (mnonnenmacher) [inline analyzer/src/funTest/kotlin/managers/PubFunTest.kt:151]: Should this match any version of the library in case someone has a different SDK version installed or is this version defined by the project?

File: analyzer/src/main/kotlin/Analyzer.kt (hunk 6 above)
Comment (fviernau) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: Are the `Pup` and `CocoaPods` types used for `projects` or just for `packages` / dependencies?

File: analyzer/src/funTest/kotlin/managers/PubFunTest.kt (hunk 8 above)
Comment (MarcelBochtler) [reply analyzer/src/funTest/kotlin/managers/PubFunTest.kt]: Removed the version from the comparison.

File: analyzer/src/main/kotlin/Analyzer.kt (hunk 6 above)
Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: At least `Pub` is also used for projects. See screenshot in the PR description.

Comment (fviernau) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: Oh, thanks for pointing to the screenshot. I missed that. I believe I'm fine as-is with the returned identifier types.

I'm lacking the flutter development knowledge in this question, maybe you can help: Is the parent child relation as-is now now in the right direction, or should the flutter project be a child project of the Gradle android app project?

For the use case "make a review for just the Android App (not the iOS one)" is it possible (as-is) to setup path excludes such that 
CocoaPods project is excluded, but not the shared Flutter one nor the Android one?

Comment (fviernau) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: Oh, thanks for pointing to the screenshot. I missed that. I believe I'm fine as-is with the returned identifier types.

I'm lacking the flutter development knowledge in this question, maybe you can help: Is the parent child relation as-is now now in the right direction, or should the flutter project be a child project of the Gradle android app project?

For the use case "make a review for just the Android App (not the iOS one)" is it possible (as-is) to setup path excludes such that CocoaPods project is excluded, but not the shared Flutter one nor the Android one?

**Review by fviernau — CHANGES_REQUESTED** [review]

**Review by mnonnenmacher — APPROVED** [review]

File: analyzer/src/main/kotlin/Analyzer.kt (hunk 6 above)
Comment (mnonnenmacher) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: > I'm lacking the flutter development knowledge in this question, maybe you can help: Is the parent child relation as-is now now in the right direction, or should the flutter project be a child project of the Gradle android app project?

Yes, at least to my understanding that's correct. The final Android app is a combination of the code and dependencies from the Flutter project and the Android project.

> For the use case "make a review for just the Android App (not the iOS one)" is it possible (as-is) to setup path excludes such that CocoaPods project is excluded, but not the shared Flutter one nor the Android one?

The definition file path of the Gradle and CocoaPods projects is still relative to the analyzer root, so all path excludes should work as expected. However, as both are added to the same scope of the Pub project this could be an issue. Because if I'm right to completely exclude a project in a multi-module setup it's not enough to exclude the project with a path exclude, but also all dependencies on that project need to be excluded?

One option is to add the Gradle and CocoaPods projects not to the "dependencies" scope of the Pub project but to separate scopes, e.g. "android" and "ios" or "gradle" and "cocoapods", then it would be possible to use a combination of path and scope excludes. But maybe in a separate PR.

Comment (fviernau) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: Thanks @mnonnenmacher . I'd be ok with a separate PR. But I think that should be mandatory to do this as follow up to not loose the possibility to make separate reviews for iOS and Android releases. Does it make sense?

Comment (mnonnenmacher) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: @MarcelBochtler What's your preference?

Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: I'll change the scope of the child Gradle project to `android` in this PR.

Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: @fviernau, @mnonnenmacher The Gradle project is now added to the `android` scope.
I also updated the screenshot in https://github.com/oss-review-toolkit/ort/pull/4831#issue-798872331 to reflect the changes.
Can you please have a look if that is what you expected?

Hint: For Cocoapods / iOS, this will be done in a separate PR, as the `Pub` implementation currently doesn't support CocoaPods at all.

Comment (fviernau) [reply analyzer/src/main/kotlin/Analyzer.kt:137]: Thanks @MarcelBochtler !

File: analyzer/src/main/kotlin/managers/Gradle.kt [hunk 9]
```diff
@@ -134,6 +135,17 @@ class Gradle(
...
+    // Filter Gradle projects that are managed via Flutter / Pub. These projects are analyzed from within Pub.
+    override fun mapDefinitionFiles(definitionFiles: List<File>): List<File> {
+        val pubFactory = Pub.Factory()
+
+        return definitionFiles.filter { gradleDefinitionFile ->
+            pubFactory.globsForDefinitionFiles.none { pubDefinitionFile ->
+                gradleDefinitionFile.parentFile.searchUpwardsForFile(pubDefinitionFile) != null
+            }
+        }
+    }
```
Comment (fviernau) [inline analyzer/src/main/kotlin/managers/Gradle.kt:147]: Just a note: it's not considering whether the package manager 'Flutter' is actually enabled.
IMO that's ok, just wanted to make sure it's considered.

File: analyzer/src/main/kotlin/managers/Pub.kt [hunk 10]
```diff
@@ -242,20 +244,67 @@ class Pub(
...
+
+            if (containsFlutterSdk(workingDir)) {
+                // Run Gradle dependency resolution. This is required because for Flutter projects, Pub needs to run
+                // first to generate the local.properties file by using `flutter pub get`.
+                val gradleFactory = Gradle.Factory()
+                val gradleDefinitionFiles =
+                    findManagedFiles(analysisRoot, listOf(gradleFactory)).getOrDefault(gradleFactory, emptyList())
+
+                if (gradleDefinitionFiles.isNotEmpty()) {
+                    println("Found ${gradleDefinitionFiles.size} ${gradleFactory.managerName} project(s) at:")
```
Comment (fviernau) [inline analyzer/src/main/kotlin/managers/Pub.kt:257]: Forgot to turn the `println()` statements into `log()` ones? (also in line 263)

**Review by fviernau — CHANGES_REQUESTED** [review]

File: analyzer/src/main/kotlin/managers/Gradle.kt (hunk 9 above)
Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/Gradle.kt:147]: AFAIU that's because Flutter is not package manager, but a framework.

File: analyzer/src/main/kotlin/managers/Pub.kt (hunk 10 above)
Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/managers/Pub.kt:257]: No, this is intended.
See the notes at the end of this comment: https://github.com/oss-review-toolkit/ort/pull/4831#issue-1075626935.

Comment (sschuberth) [reply analyzer/src/main/kotlin/managers/Pub.kt:257]: However, @fviernau is right that we should not call `println()` in library code, as we cannot be sure to have a console attached. So we might need to turn this into a `log` after all.

Comment (MarcelBochtler) [reply analyzer/src/main/kotlin/managers/Pub.kt]: Thanks for the explanation. Replaced it with info logs.

**Review by fviernau — DISMISSED** [review]

**Comment by MarcelBochtler** [comment]
@fviernau I inlined `scopes += parseScope("dependencies", manifest, lockFile, parsePackagesResult.packages, labels)` again.
Accidentally added some test files, that's why the force-push diffs are a bit messed up.
Sorry for that.

**Review by fviernau — APPROVED** [review]
