### PR TITLE
helper-cli: Fix the command for importing copyright garbage

### LINKED ISSUE #6676: ImportCobyrightGarbageCommand crashes
```
Exception in thread "main" java.util.IllformedLocaleException: Ill-formed region: US.utf-8 [at index 0]
	at java.base/java.util.Locale$Builder.setRegion(Locale.java:2671)
	at org.ossreviewtoolkit.helper.commands.ImportCopyrightGarbageCommand.run(ImportCopyrightGarbageCommand.kt:68)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:198)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:211)
	at com.github.ajalt.clikt.parsers.Parser.parse(Parser.kt:18)
	at com.github.ajalt.clikt.core.CliktCommand.parse(CliktCommand.kt:400)
	at com.github.ajalt.clikt.core.CliktCommand.parse$default(CliktCommand.kt:397)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:415)
	at com.github.ajalt.clikt.core.CliktCommand.main(CliktCommand.kt:440)
	at org.ossreviewtoolkit.helper.HelperMainKt.main(HelperMain.kt:53)

```

Attempt to read a file with content:
```
(c) self.assertEqual http://ns1
```

### PR DESCRIPTION
**Pull request by fviernau**
Fixes #6676.

### CODE REVIEW

File: helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt [hunk 1]
```diff
@@ -65,8 +65,7 @@ internal class ImportCopyrightGarbageCommand : CliktCommand(
             emptySet<String>()
         }
 
-        val locale = Locale.Builder().setLanguage("en").setRegion("US.utf-8").setVariant("POSIX").build()
-        val collator = Collator.getInstance(locale)
+        val collator = Collator.getInstance(Locale("en", "US.utf-8", "POSIX"))
```
Comment (sschuberth) [inline helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt:68]: Looks like this could instead be fixed by changing `"US.utf-8"` to `"US"` in the current code. Not sure what the encoding has to do with the locale anyway; the `Locale` constructor seems to have been tolerant about this. Does stripping the ".utf-8" part work for you, too?

Comment (fviernau) [reply helper-cli/src/main/kotlin/commands/ImportCopyrightGarbageCommand.kt]: Thanks. That works for me too. I've updated the commit accordingly!

**Review by sschuberth — APPROVED** [review]
