### PR TITLE
WebApp: Display the custom how-to-fix messages

### LINKED ISSUE #2347: Allow setting scriptable HowToFix texts for Analyzer and Scanner errors
Propose we implement a mechanism to allow defining HowToFix texts for Analyzer and Scanner errors similar to Evaluator to provide user instructions how they can fix their errors.

Making it scriptable versus a config file will allow use of conditions and variables.

Thought a basic implementation would be simply a string matcher on error message similar to error/rule violation resolutions.

### PR DESCRIPTION
**Pull request by fviernau**
This PR follows up on #2966 by handling the `HowToFixTextProvider` in the `evaluated model` and in the `WebApp`.

Fixes #2347.

### CODE REVIEW

File: reporter/src/funTest/kotlin/reporters/EvaluatedModelReporterTest.kt [hunk 1]
```diff
@@ -22,10 +22,9 @@ package org.ossreviewtoolkit.reporter.reporters
 import io.kotest.core.spec.style.WordSpec
 import io.kotest.matchers.shouldBe
 
-import org.ossreviewtoolkit.model.OrtIssue
-
 import java.io.File
 
+import org.ossreviewtoolkit.model.OrtIssue
```
Comment (mnonnenmacher) [inline reporter/src/funTest/kotlin/reporters/EvaluatedModelReporterTest.kt:27]: That change belongs to the previous commit.

**Review by mnonnenmacher — CHANGES_REQUESTED** [review]

File: reporter/src/funTest/kotlin/reporters/EvaluatedModelReporterTest.kt (hunk 1 above)
Comment (fviernau) [reply reporter/src/funTest/kotlin/reporters/EvaluatedModelReporterTest.kt:27]: Done.

**Review by mnonnenmacher — APPROVED** [review]
